; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.22 = private unnamed_addr constant [7 x i8] c"] Done\00"
@.str.18 = private unnamed_addr constant [61 x i8] c"Server running! Test with: curl http://localhost:8888/health\00"
@.str.19 = private unnamed_addr constant [36 x i8] c"Handled 10 requests, shutting down.\00"
@.str.2 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.9 = private unnamed_addr constant [33 x i8] c"Content-Type: application/json\0D\0A\00"
@.str.12 = private unnamed_addr constant [22 x i8] c"{\22error\22:\22not found\22}\00"
@.str.15 = private unnamed_addr constant [44 x i8] c"Starting simple HTTP server on port 8888...\00"
@.str.6 = private unnamed_addr constant [16 x i8] c"{\22status\22:\22ok\22}\00"
@.str.5 = private unnamed_addr constant [8 x i8] c"/health\00"
@.str.0 = private unnamed_addr constant [1 x i8] c"\00"
@.str.4 = private unnamed_addr constant [7 x i8] c"[REQ] \00"
@.str.17 = private unnamed_addr constant [25 x i8] c"Failed to create server!\00"
@.str.14 = private unnamed_addr constant [20 x i8] c"Connection: close\0D\0A\00"
@.str.8 = private unnamed_addr constant [18 x i8] c"HTTP/1.1 200 OK\0D\0A\00"
@.str.20 = private unnamed_addr constant [2 x i8] c"[\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"\0D\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"\0D\0A\00"
@.str.3 = private unnamed_addr constant [2 x i8] c" \00"
@.str.21 = private unnamed_addr constant [21 x i8] c"] Handling client...\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"/\00"
@.str.10 = private unnamed_addr constant [17 x i8] c"Content-Length: \00"
@.str.11 = private unnamed_addr constant [18 x i8] c"Hello from Roast!\00"
@.str.16 = private unnamed_addr constant [8 x i8] c"0.0.0.0\00"

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_104() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  br label %bb0
bb0:
  %v26 = getelementptr [44 x i8], [44 x i8]* @.str.15, i64 0, i64 0
  %v27 = call i8* @roast_str_new(i8* %v26, i64 43)
  %v28 = ptrtoint i8* %v27 to i64
  %v29 = call i64 @roast_print(i64 %v28)
  store i64 %v29, i64* %v0
  br label %bb1
bb1:
  %v30 = getelementptr [8 x i8], [8 x i8]* @.str.16, i64 0, i64 0
  %v31 = call i8* @roast_str_new(i8* %v30, i64 7)
  %v32 = ptrtoint i8* %v31 to i64
  %v34 = inttoptr i64 %v32 to i8*
  %v33 = call i64 @roast_tcp_server_create(i8* %v34, i64 8888)
  store i64 %v33, i64* %v2
  br label %bb2
bb2:
  %v35 = load i64, i64* %v2
  store i64 %v35, i64* %v1
  %v36 = load i64, i64* %v1
  %v38 = icmp slt i64 %v36, 0
  %v37 = zext i1 %v38 to i64
  store i64 %v37, i64* %v3
  %v39 = load i64, i64* %v3
  store i64 %v39, i64* %v4
  %v40 = load i64, i64* %v4
  %v41 = icmp eq i64 %v40, 1
  br i1 %v41, label %bb3, label %bb4
bb3:
  %v42 = getelementptr [25 x i8], [25 x i8]* @.str.17, i64 0, i64 0
  %v43 = call i8* @roast_str_new(i8* %v42, i64 24)
  %v44 = ptrtoint i8* %v43 to i64
  %v45 = call i64 @roast_print(i64 %v44)
  store i64 %v45, i64* %v5
  br label %bb5
bb4:
  %v46 = getelementptr [61 x i8], [61 x i8]* @.str.18, i64 0, i64 0
  %v47 = call i8* @roast_str_new(i8* %v46, i64 60)
  %v48 = ptrtoint i8* %v47 to i64
  %v49 = call i64 @roast_print(i64 %v48)
  store i64 %v49, i64* %v6
  br label %bb6
bb5:
  ret i64 1
bb6:
  store i64 0, i64* %v7
  br label %bb7
bb7:
  %v50 = load i64, i64* %v7
  %v52 = icmp slt i64 %v50, 10
  %v51 = zext i1 %v52 to i64
  store i64 %v51, i64* %v8
  %v53 = load i64, i64* %v8
  store i64 %v53, i64* %v9
  %v54 = load i64, i64* %v9
  %v55 = icmp eq i64 %v54, 1
  br i1 %v55, label %bb8, label %bb9
bb8:
  %v56 = load i64, i64* %v1
  %v57 = call i64 @roast_tcp_server_accept(i64 %v56)
  store i64 %v57, i64* %v11
  br label %bb10
bb9:
  %v58 = getelementptr [36 x i8], [36 x i8]* @.str.19, i64 0, i64 0
  %v59 = call i8* @roast_str_new(i8* %v58, i64 35)
  %v60 = ptrtoint i8* %v59 to i64
  %v61 = call i64 @roast_print(i64 %v60)
  store i64 %v61, i64* %v24
  br label %bb18
bb10:
  %v62 = load i64, i64* %v11
  store i64 %v62, i64* %v10
  %v63 = load i64, i64* %v10
  %v65 = icmp sge i64 %v63, 0
  %v64 = zext i1 %v65 to i64
  store i64 %v64, i64* %v12
  %v66 = load i64, i64* %v12
  store i64 %v66, i64* %v13
  %v67 = load i64, i64* %v13
  %v68 = icmp eq i64 %v67, 1
  br i1 %v68, label %bb11, label %bb12
bb11:
  %v69 = load i64, i64* %v7
  %v70 = add i64 %v69, 1
  store i64 %v70, i64* %v14
  %v71 = load i64, i64* %v14
  store i64 %v71, i64* %v7
  %v72 = load i64, i64* %v7
  %v73 = call i64 @roast_str(i64 %v72)
  store i64 %v73, i64* %v16
  br label %bb13
bb12:
  br label %bb7
bb13:
  %v74 = getelementptr [2 x i8], [2 x i8]* @.str.20, i64 0, i64 0
  %v75 = call i8* @roast_str_new(i8* %v74, i64 1)
  %v76 = ptrtoint i8* %v75 to i64
  %v77 = load i64, i64* %v16
  %v79 = inttoptr i64 %v76 to i8*
  %v80 = inttoptr i64 %v77 to i8*
  %v81 = call i8* @roast_str_concat(i8* %v79, i8* %v80)
  %v78 = ptrtoint i8* %v81 to i64
  store i64 %v78, i64* %v17
  %v82 = load i64, i64* %v17
  %v83 = getelementptr [21 x i8], [21 x i8]* @.str.21, i64 0, i64 0
  %v84 = call i8* @roast_str_new(i8* %v83, i64 20)
  %v85 = ptrtoint i8* %v84 to i64
  %v87 = inttoptr i64 %v82 to i8*
  %v88 = inttoptr i64 %v85 to i8*
  %v89 = call i8* @roast_str_concat(i8* %v87, i8* %v88)
  %v86 = ptrtoint i8* %v89 to i64
  store i64 %v86, i64* %v18
  %v90 = load i64, i64* %v18
  %v91 = call i64 @roast_print(i64 %v90)
  store i64 %v91, i64* %v15
  br label %bb14
bb14:
  %v92 = load i64, i64* %v10
  %v93 = call i64 @roast_fn_87(i64 %v92)
  store i64 %v93, i64* %v19
  br label %bb15
bb15:
  %v94 = load i64, i64* %v7
  %v95 = call i64 @roast_str(i64 %v94)
  store i64 %v95, i64* %v21
  br label %bb16
bb16:
  %v96 = getelementptr [2 x i8], [2 x i8]* @.str.20, i64 0, i64 0
  %v97 = call i8* @roast_str_new(i8* %v96, i64 1)
  %v98 = ptrtoint i8* %v97 to i64
  %v99 = load i64, i64* %v21
  %v101 = inttoptr i64 %v98 to i8*
  %v102 = inttoptr i64 %v99 to i8*
  %v103 = call i8* @roast_str_concat(i8* %v101, i8* %v102)
  %v100 = ptrtoint i8* %v103 to i64
  store i64 %v100, i64* %v22
  %v104 = load i64, i64* %v22
  %v105 = getelementptr [7 x i8], [7 x i8]* @.str.22, i64 0, i64 0
  %v106 = call i8* @roast_str_new(i8* %v105, i64 6)
  %v107 = ptrtoint i8* %v106 to i64
  %v109 = inttoptr i64 %v104 to i8*
  %v110 = inttoptr i64 %v107 to i8*
  %v111 = call i8* @roast_str_concat(i8* %v109, i8* %v110)
  %v108 = ptrtoint i8* %v111 to i64
  store i64 %v108, i64* %v23
  %v112 = load i64, i64* %v23
  %v113 = call i64 @roast_print(i64 %v112)
  store i64 %v113, i64* %v20
  br label %bb17
bb17:
  br label %bb12
bb18:
  %v114 = load i64, i64* %v1
  call void @roast_tcp_server_close(i64 %v114)
  %v115 = add i64 0, 0
  store i64 %v115, i64* %v25
  br label %bb19
bb19:
  ret i64 0
}

define i64 @roast_fn_87(i64 %arg0) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i64
  %v41 = alloca i64
  %v42 = alloca i64
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i64
  %v53 = alloca i64
  %v54 = alloca i64
  %v55 = alloca i64
  %v56 = alloca i64
  %v57 = alloca i64
  %v58 = alloca i64
  %v59 = alloca i64
  %v60 = alloca i64
  %v61 = alloca i64
  %v62 = alloca i64
  %v63 = alloca i64
  %v64 = alloca i64
  store i64 %arg0, i64* %v0
  br label %bb0
bb0:
  %v65 = load i64, i64* %v0
  %v67 = call i8* @roast_tcp_client_read(i64 %v65, i64 4096)
  %v66 = ptrtoint i8* %v67 to i64
  store i64 %v66, i64* %v2
  br label %bb1
bb1:
  %v68 = load i64, i64* %v2
  store i64 %v68, i64* %v1
  %v69 = inttoptr i64 %v68 to i8*
  call void @roast_incref(i8* %v69)
  %v70 = load i64, i64* %v1
  %v71 = call i64 @roast_len(i64 %v70)
  store i64 %v71, i64* %v3
  br label %bb2
bb2:
  %v72 = load i64, i64* %v3
  %v74 = icmp eq i64 %v72, 0
  %v73 = zext i1 %v74 to i64
  store i64 %v73, i64* %v4
  %v75 = load i64, i64* %v4
  store i64 %v75, i64* %v5
  %v76 = load i64, i64* %v5
  %v77 = icmp eq i64 %v76, 1
  br i1 %v77, label %bb3, label %bb4
bb3:
  %v78 = load i64, i64* %v0
  call void @roast_tcp_client_close(i64 %v78)
  %v79 = add i64 0, 0
  store i64 %v79, i64* %v6
  br label %bb5
bb4:
  %v80 = getelementptr [1 x i8], [1 x i8]* @.str.0, i64 0, i64 0
  %v81 = call i8* @roast_str_new(i8* %v80, i64 0)
  %v82 = ptrtoint i8* %v81 to i64
  store i64 %v82, i64* %v7
  %v83 = load i64, i64* %v1
  store i64 %v83, i64* %v8
  br label %bb6
bb5:
  ret i64 0
bb6:
  %v84 = load i64, i64* %v1
  %v85 = inttoptr i64 %v84 to i8*
  %v86 = call i8* @roast_iter_new(i8* %v85)
  %v87 = ptrtoint i8* %v86 to i64
  store i64 %v87, i64* %v9
  br label %bb7
bb7:
  %v88 = load i64, i64* %v9
  %v89 = inttoptr i64 %v88 to i8*
  %v90 = alloca i1
  %v91 = call i64 @roast_iter_next(i8* %v89, i1* %v90)
  %v92 = load i1, i1* %v90
  store i64 %v91, i64* %v10
  br i1 %v92, label %bb9, label %bb8
bb8:
  %v93 = load i64, i64* %v10
  %v94 = getelementptr [2 x i8], [2 x i8]* @.str.1, i64 0, i64 0
  %v95 = call i8* @roast_str_new(i8* %v94, i64 1)
  %v96 = ptrtoint i8* %v95 to i64
  %v98 = inttoptr i64 %v93 to i8*
  %v99 = inttoptr i64 %v96 to i8*
  %v100 = call i1 @roast_str_eq(i8* %v98, i8* %v99)
  %v97 = zext i1 %v100 to i64
  store i64 %v97, i64* %v11
  %v101 = load i64, i64* %v10
  %v102 = getelementptr [2 x i8], [2 x i8]* @.str.2, i64 0, i64 0
  %v103 = call i8* @roast_str_new(i8* %v102, i64 1)
  %v104 = ptrtoint i8* %v103 to i64
  %v106 = inttoptr i64 %v101 to i8*
  %v107 = inttoptr i64 %v104 to i8*
  %v108 = call i1 @roast_str_eq(i8* %v106, i8* %v107)
  %v105 = zext i1 %v108 to i64
  store i64 %v105, i64* %v12
  %v109 = load i64, i64* %v11
  %v110 = load i64, i64* %v12
  %v111 = or i64 %v109, %v110
  store i64 %v111, i64* %v13
  %v112 = load i64, i64* %v13
  store i64 %v112, i64* %v14
  %v113 = load i64, i64* %v14
  %v114 = icmp eq i64 %v113, 1
  br i1 %v114, label %bb10, label %bb11
bb9:
  %v115 = call i8* @roast_list_new(i64 0)
  %v116 = ptrtoint i8* %v115 to i64
  store i64 %v116, i64* %v17
  %v117 = load i64, i64* %v17
  store i64 %v117, i64* %v16
  %v118 = inttoptr i64 %v117 to i8*
  call void @roast_incref(i8* %v118)
  %v119 = getelementptr [1 x i8], [1 x i8]* @.str.0, i64 0, i64 0
  %v120 = call i8* @roast_str_new(i8* %v119, i64 0)
  %v121 = ptrtoint i8* %v120 to i64
  store i64 %v121, i64* %v18
  %v122 = load i64, i64* %v7
  store i64 %v122, i64* %v19
  br label %bb12
bb10:
  br label %bb9
bb11:
  %v123 = load i64, i64* %v7
  %v124 = load i64, i64* %v10
  %v126 = inttoptr i64 %v123 to i8*
  %v127 = inttoptr i64 %v124 to i8*
  %v128 = call i8* @roast_str_concat(i8* %v126, i8* %v127)
  %v125 = ptrtoint i8* %v128 to i64
  store i64 %v125, i64* %v15
  %v129 = load i64, i64* %v15
  store i64 %v129, i64* %v7
  %v130 = inttoptr i64 %v129 to i8*
  call void @roast_incref(i8* %v130)
  br label %bb7
bb12:
  %v131 = load i64, i64* %v19
  %v132 = inttoptr i64 %v131 to i8*
  %v133 = call i8* @roast_iter_new(i8* %v132)
  %v134 = ptrtoint i8* %v133 to i64
  store i64 %v134, i64* %v20
  br label %bb13
bb13:
  %v135 = load i64, i64* %v20
  %v136 = inttoptr i64 %v135 to i8*
  %v137 = alloca i1
  %v138 = call i64 @roast_iter_next(i8* %v136, i1* %v137)
  %v139 = load i1, i1* %v137
  store i64 %v138, i64* %v21
  br i1 %v139, label %bb15, label %bb14
bb14:
  %v140 = load i64, i64* %v21
  %v141 = getelementptr [2 x i8], [2 x i8]* @.str.3, i64 0, i64 0
  %v142 = call i8* @roast_str_new(i8* %v141, i64 1)
  %v143 = ptrtoint i8* %v142 to i64
  %v145 = inttoptr i64 %v140 to i8*
  %v146 = inttoptr i64 %v143 to i8*
  %v147 = call i1 @roast_str_eq(i8* %v145, i8* %v146)
  %v144 = zext i1 %v147 to i64
  store i64 %v144, i64* %v22
  %v148 = load i64, i64* %v22
  store i64 %v148, i64* %v23
  %v149 = load i64, i64* %v23
  %v150 = icmp eq i64 %v149, 1
  br i1 %v150, label %bb16, label %bb17
bb15:
  %v151 = load i64, i64* %v18
  %v152 = call i64 @roast_len(i64 %v151)
  store i64 %v152, i64* %v29
  br label %bb23
bb16:
  %v153 = load i64, i64* %v18
  %v154 = call i64 @roast_len(i64 %v153)
  store i64 %v154, i64* %v24
  br label %bb19
bb17:
  %v155 = load i64, i64* %v18
  %v156 = load i64, i64* %v21
  %v158 = inttoptr i64 %v155 to i8*
  %v159 = inttoptr i64 %v156 to i8*
  %v160 = call i8* @roast_str_concat(i8* %v158, i8* %v159)
  %v157 = ptrtoint i8* %v160 to i64
  store i64 %v157, i64* %v28
  %v161 = load i64, i64* %v28
  store i64 %v161, i64* %v18
  %v162 = inttoptr i64 %v161 to i8*
  call void @roast_incref(i8* %v162)
  br label %bb18
bb18:
  br label %bb13
bb19:
  %v163 = load i64, i64* %v24
  %v165 = icmp sgt i64 %v163, 0
  %v164 = zext i1 %v165 to i64
  store i64 %v164, i64* %v25
  %v166 = load i64, i64* %v25
  store i64 %v166, i64* %v26
  %v167 = load i64, i64* %v26
  %v168 = icmp eq i64 %v167, 1
  br i1 %v168, label %bb20, label %bb21
bb20:
  %v169 = load i64, i64* %v16
  %v171 = inttoptr i64 %v169 to i8*
  %v172 = load i64, i64* %v18
  call void @roast_list_append(i8* %v171, i64 %v172)
  %v170 = add i64 0, 0
  store i64 %v170, i64* %v27
  br label %bb22
bb21:
  %v173 = getelementptr [1 x i8], [1 x i8]* @.str.0, i64 0, i64 0
  %v174 = call i8* @roast_str_new(i8* %v173, i64 0)
  %v175 = ptrtoint i8* %v174 to i64
  store i64 %v175, i64* %v18
  br label %bb18
bb22:
  br label %bb21
bb23:
  %v176 = load i64, i64* %v29
  %v178 = icmp sgt i64 %v176, 0
  %v177 = zext i1 %v178 to i64
  store i64 %v177, i64* %v30
  %v179 = load i64, i64* %v30
  store i64 %v179, i64* %v31
  %v180 = load i64, i64* %v31
  %v181 = icmp eq i64 %v180, 1
  br i1 %v181, label %bb24, label %bb25
bb24:
  %v182 = load i64, i64* %v16
  %v184 = inttoptr i64 %v182 to i8*
  %v185 = load i64, i64* %v18
  call void @roast_list_append(i8* %v184, i64 %v185)
  %v183 = add i64 0, 0
  store i64 %v183, i64* %v32
  br label %bb26
bb25:
  %v186 = getelementptr [1 x i8], [1 x i8]* @.str.0, i64 0, i64 0
  %v187 = call i8* @roast_str_new(i8* %v186, i64 0)
  %v188 = ptrtoint i8* %v187 to i64
  store i64 %v188, i64* %v33
  %v189 = getelementptr [1 x i8], [1 x i8]* @.str.0, i64 0, i64 0
  %v190 = call i8* @roast_str_new(i8* %v189, i64 0)
  %v191 = ptrtoint i8* %v190 to i64
  store i64 %v191, i64* %v34
  %v192 = load i64, i64* %v16
  %v193 = call i64 @roast_len(i64 %v192)
  store i64 %v193, i64* %v35
  br label %bb27
bb26:
  br label %bb25
bb27:
  %v194 = load i64, i64* %v35
  %v196 = icmp sge i64 %v194, 2
  %v195 = zext i1 %v196 to i64
  store i64 %v195, i64* %v36
  %v197 = load i64, i64* %v36
  store i64 %v197, i64* %v37
  %v198 = load i64, i64* %v37
  %v199 = icmp eq i64 %v198, 1
  br i1 %v199, label %bb28, label %bb29
bb28:
  %v200 = load i64, i64* %v16
  store i64 %v200, i64* %v38
  %v201 = inttoptr i64 %v200 to i8*
  call void @roast_incref(i8* %v201)
  store i64 0, i64* %v39
  %v202 = load i64, i64* %v38
  %v203 = load i64, i64* %v39
  %v205 = inttoptr i64 %v202 to i8*
  %v204 = call i64 @roast_list_get(i8* %v205, i64 %v203)
  store i64 %v204, i64* %v33
  %v206 = inttoptr i64 %v204 to i8*
  call void @roast_incref(i8* %v206)
  %v207 = load i64, i64* %v16
  store i64 %v207, i64* %v40
  %v208 = inttoptr i64 %v207 to i8*
  call void @roast_incref(i8* %v208)
  store i64 1, i64* %v41
  %v209 = load i64, i64* %v40
  %v210 = load i64, i64* %v41
  %v212 = inttoptr i64 %v209 to i8*
  %v211 = call i64 @roast_list_get(i8* %v212, i64 %v210)
  store i64 %v211, i64* %v34
  %v213 = inttoptr i64 %v211 to i8*
  call void @roast_incref(i8* %v213)
  br label %bb29
bb29:
  %v214 = load i64, i64* %v33
  %v215 = call i64 @roast_str(i64 %v214)
  store i64 %v215, i64* %v43
  br label %bb30
bb30:
  %v216 = getelementptr [7 x i8], [7 x i8]* @.str.4, i64 0, i64 0
  %v217 = call i8* @roast_str_new(i8* %v216, i64 6)
  %v218 = ptrtoint i8* %v217 to i64
  %v219 = load i64, i64* %v43
  %v221 = inttoptr i64 %v218 to i8*
  %v222 = inttoptr i64 %v219 to i8*
  %v223 = call i8* @roast_str_concat(i8* %v221, i8* %v222)
  %v220 = ptrtoint i8* %v223 to i64
  store i64 %v220, i64* %v44
  %v224 = load i64, i64* %v44
  %v225 = getelementptr [2 x i8], [2 x i8]* @.str.3, i64 0, i64 0
  %v226 = call i8* @roast_str_new(i8* %v225, i64 1)
  %v227 = ptrtoint i8* %v226 to i64
  %v229 = inttoptr i64 %v224 to i8*
  %v230 = inttoptr i64 %v227 to i8*
  %v231 = call i8* @roast_str_concat(i8* %v229, i8* %v230)
  %v228 = ptrtoint i8* %v231 to i64
  store i64 %v228, i64* %v45
  %v232 = load i64, i64* %v34
  %v233 = call i64 @roast_str(i64 %v232)
  store i64 %v233, i64* %v46
  br label %bb31
bb31:
  %v234 = load i64, i64* %v45
  %v235 = load i64, i64* %v46
  %v237 = inttoptr i64 %v234 to i8*
  %v238 = inttoptr i64 %v235 to i8*
  %v239 = call i8* @roast_str_concat(i8* %v237, i8* %v238)
  %v236 = ptrtoint i8* %v239 to i64
  store i64 %v236, i64* %v47
  %v240 = load i64, i64* %v47
  %v241 = call i64 @roast_print(i64 %v240)
  store i64 %v241, i64* %v42
  br label %bb32
bb32:
  %v242 = getelementptr [1 x i8], [1 x i8]* @.str.0, i64 0, i64 0
  %v243 = call i8* @roast_str_new(i8* %v242, i64 0)
  %v244 = ptrtoint i8* %v243 to i64
  store i64 %v244, i64* %v48
  %v245 = load i64, i64* %v34
  %v246 = getelementptr [8 x i8], [8 x i8]* @.str.5, i64 0, i64 0
  %v247 = call i8* @roast_str_new(i8* %v246, i64 7)
  %v248 = ptrtoint i8* %v247 to i64
  %v250 = inttoptr i64 %v245 to i8*
  %v251 = inttoptr i64 %v248 to i8*
  %v252 = call i1 @roast_str_eq(i8* %v250, i8* %v251)
  %v249 = zext i1 %v252 to i64
  store i64 %v249, i64* %v49
  %v253 = load i64, i64* %v49
  store i64 %v253, i64* %v50
  %v254 = load i64, i64* %v50
  %v255 = icmp eq i64 %v254, 1
  br i1 %v255, label %bb33, label %bb34
bb33:
  %v256 = getelementptr [16 x i8], [16 x i8]* @.str.6, i64 0, i64 0
  %v257 = call i8* @roast_str_new(i8* %v256, i64 15)
  %v258 = ptrtoint i8* %v257 to i64
  store i64 %v258, i64* %v48
  br label %bb35
bb34:
  %v259 = load i64, i64* %v34
  %v260 = getelementptr [2 x i8], [2 x i8]* @.str.7, i64 0, i64 0
  %v261 = call i8* @roast_str_new(i8* %v260, i64 1)
  %v262 = ptrtoint i8* %v261 to i64
  %v264 = inttoptr i64 %v259 to i8*
  %v265 = inttoptr i64 %v262 to i8*
  %v266 = call i1 @roast_str_eq(i8* %v264, i8* %v265)
  %v263 = zext i1 %v266 to i64
  store i64 %v263, i64* %v51
  %v267 = load i64, i64* %v51
  store i64 %v267, i64* %v52
  %v268 = load i64, i64* %v52
  %v269 = icmp eq i64 %v268, 1
  br i1 %v269, label %bb36, label %bb37
bb35:
  %v270 = getelementptr [18 x i8], [18 x i8]* @.str.8, i64 0, i64 0
  %v271 = call i8* @roast_str_new(i8* %v270, i64 17)
  %v272 = ptrtoint i8* %v271 to i64
  store i64 %v272, i64* %v53
  %v273 = load i64, i64* %v53
  %v274 = getelementptr [33 x i8], [33 x i8]* @.str.9, i64 0, i64 0
  %v275 = call i8* @roast_str_new(i8* %v274, i64 32)
  %v276 = ptrtoint i8* %v275 to i64
  %v278 = inttoptr i64 %v273 to i8*
  %v279 = inttoptr i64 %v276 to i8*
  %v280 = call i8* @roast_str_concat(i8* %v278, i8* %v279)
  %v277 = ptrtoint i8* %v280 to i64
  store i64 %v277, i64* %v54
  %v281 = load i64, i64* %v54
  store i64 %v281, i64* %v53
  %v282 = inttoptr i64 %v281 to i8*
  call void @roast_incref(i8* %v282)
  %v283 = load i64, i64* %v53
  %v284 = getelementptr [17 x i8], [17 x i8]* @.str.10, i64 0, i64 0
  %v285 = call i8* @roast_str_new(i8* %v284, i64 16)
  %v286 = ptrtoint i8* %v285 to i64
  %v288 = inttoptr i64 %v283 to i8*
  %v289 = inttoptr i64 %v286 to i8*
  %v290 = call i8* @roast_str_concat(i8* %v288, i8* %v289)
  %v287 = ptrtoint i8* %v290 to i64
  store i64 %v287, i64* %v55
  %v291 = load i64, i64* %v48
  %v292 = call i64 @roast_len(i64 %v291)
  store i64 %v292, i64* %v57
  br label %bb39
bb36:
  %v293 = getelementptr [18 x i8], [18 x i8]* @.str.11, i64 0, i64 0
  %v294 = call i8* @roast_str_new(i8* %v293, i64 17)
  %v295 = ptrtoint i8* %v294 to i64
  store i64 %v295, i64* %v48
  br label %bb38
bb37:
  %v296 = getelementptr [22 x i8], [22 x i8]* @.str.12, i64 0, i64 0
  %v297 = call i8* @roast_str_new(i8* %v296, i64 21)
  %v298 = ptrtoint i8* %v297 to i64
  store i64 %v298, i64* %v48
  br label %bb38
bb38:
  br label %bb35
bb39:
  %v299 = load i64, i64* %v57
  %v300 = call i64 @roast_str(i64 %v299)
  store i64 %v300, i64* %v56
  br label %bb40
bb40:
  %v301 = load i64, i64* %v55
  %v302 = load i64, i64* %v56
  %v304 = inttoptr i64 %v301 to i8*
  %v305 = inttoptr i64 %v302 to i8*
  %v306 = call i8* @roast_str_concat(i8* %v304, i8* %v305)
  %v303 = ptrtoint i8* %v306 to i64
  store i64 %v303, i64* %v58
  %v307 = load i64, i64* %v58
  %v308 = getelementptr [3 x i8], [3 x i8]* @.str.13, i64 0, i64 0
  %v309 = call i8* @roast_str_new(i8* %v308, i64 2)
  %v310 = ptrtoint i8* %v309 to i64
  %v312 = inttoptr i64 %v307 to i8*
  %v313 = inttoptr i64 %v310 to i8*
  %v314 = call i8* @roast_str_concat(i8* %v312, i8* %v313)
  %v311 = ptrtoint i8* %v314 to i64
  store i64 %v311, i64* %v59
  %v315 = load i64, i64* %v59
  store i64 %v315, i64* %v53
  %v316 = inttoptr i64 %v315 to i8*
  call void @roast_incref(i8* %v316)
  %v317 = load i64, i64* %v53
  %v318 = getelementptr [20 x i8], [20 x i8]* @.str.14, i64 0, i64 0
  %v319 = call i8* @roast_str_new(i8* %v318, i64 19)
  %v320 = ptrtoint i8* %v319 to i64
  %v322 = inttoptr i64 %v317 to i8*
  %v323 = inttoptr i64 %v320 to i8*
  %v324 = call i8* @roast_str_concat(i8* %v322, i8* %v323)
  %v321 = ptrtoint i8* %v324 to i64
  store i64 %v321, i64* %v60
  %v325 = load i64, i64* %v60
  store i64 %v325, i64* %v53
  %v326 = inttoptr i64 %v325 to i8*
  call void @roast_incref(i8* %v326)
  %v327 = load i64, i64* %v53
  %v328 = getelementptr [3 x i8], [3 x i8]* @.str.13, i64 0, i64 0
  %v329 = call i8* @roast_str_new(i8* %v328, i64 2)
  %v330 = ptrtoint i8* %v329 to i64
  %v332 = inttoptr i64 %v327 to i8*
  %v333 = inttoptr i64 %v330 to i8*
  %v334 = call i8* @roast_str_concat(i8* %v332, i8* %v333)
  %v331 = ptrtoint i8* %v334 to i64
  store i64 %v331, i64* %v61
  %v335 = load i64, i64* %v61
  store i64 %v335, i64* %v53
  %v336 = inttoptr i64 %v335 to i8*
  call void @roast_incref(i8* %v336)
  %v337 = load i64, i64* %v53
  %v338 = load i64, i64* %v48
  %v340 = inttoptr i64 %v337 to i8*
  %v341 = inttoptr i64 %v338 to i8*
  %v342 = call i8* @roast_str_concat(i8* %v340, i8* %v341)
  %v339 = ptrtoint i8* %v342 to i64
  store i64 %v339, i64* %v62
  %v343 = load i64, i64* %v62
  store i64 %v343, i64* %v53
  %v344 = inttoptr i64 %v343 to i8*
  call void @roast_incref(i8* %v344)
  %v345 = load i64, i64* %v0
  %v346 = load i64, i64* %v53
  %v348 = inttoptr i64 %v346 to i8*
  %v347 = call i64 @roast_tcp_client_write(i64 %v345, i8* %v348)
  store i64 %v347, i64* %v63
  br label %bb41
bb41:
  %v349 = load i64, i64* %v0
  call void @roast_tcp_client_close(i64 %v349)
  %v350 = add i64 0, 0
  store i64 %v350, i64* %v64
  br label %bb42
bb42:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_166()
    ret i32 0
}

define i64 @roast_fn_166() {
entry:
  %v0 = alloca i64
  br label %bb0
bb0:
  %v1 = call i64 @roast_fn_104()
  store i64 %v1, i64* %v0
  br label %bb1
bb1:
  ret i64 0
}

