; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.2 = private unnamed_addr constant [19 x i8] c"2. Server handle: \00"
@.str.13 = private unnamed_addr constant [23 x i8] c"8b. Data has content: \00"
@.str.1 = private unnamed_addr constant [8 x i8] c"0.0.0.0\00"
@.str.9 = private unnamed_addr constant [32 x i8] c"7. Checking if data is empty...\00"
@.str.0 = private unnamed_addr constant [26 x i8] c"1. Creating TCP server...\00"
@.str.6 = private unnamed_addr constant [24 x i8] c"Failed to accept client\00"
@.str.8 = private unnamed_addr constant [23 x i8] c"6. Read complete, len=\00"
@.str.12 = private unnamed_addr constant [23 x i8] c"9. Sending response...\00"
@.str.15 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.20 = private unnamed_addr constant [22 x i8] c"11. Closing client...\00"
@.str.21 = private unnamed_addr constant [22 x i8] c"12. Closing server...\00"
@.str.19 = private unnamed_addr constant [18 x i8] c"10. Wrote bytes: \00"
@.str.3 = private unnamed_addr constant [24 x i8] c"Failed to create server\00"
@.str.10 = private unnamed_addr constant [1 x i8] c"\00"
@.str.7 = private unnamed_addr constant [26 x i8] c"5. Reading from client...\00"
@.str.11 = private unnamed_addr constant [18 x i8] c"8a. Data is empty\00"
@.str.22 = private unnamed_addr constant [10 x i8] c"13. Done!\00"
@.str.5 = private unnamed_addr constant [19 x i8] c"4. Client handle: \00"
@.str.14 = private unnamed_addr constant [7 x i8] c" bytes\00"
@.str.17 = private unnamed_addr constant [13 x i8] c"First line: \00"
@.str.16 = private unnamed_addr constant [2 x i8] c"\0D\00"
@.str.4 = private unnamed_addr constant [29 x i8] c"3. Waiting for connection...\00"
@.str.18 = private unnamed_addr constant [60 x i8] c"HTTP/1.1 200 OK\0D\0AContent-Length: 2\0D\0AConnection: close\0D\0A\0D\0AOK\00"

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_159() {
entry:
  %v0 = alloca i64
  br label %bb0
bb0:
  %v1 = call i64 @roast_fn_87()
  store i64 %v1, i64* %v0
  br label %bb1
bb1:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_159()
    ret i32 0
}

define i64 @roast_fn_87() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i64
  %v41 = alloca i64
  %v42 = alloca i64
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i64
  %v53 = alloca i64
  %v54 = alloca i64
  %v55 = alloca i64
  %v56 = alloca i64
  %v57 = alloca i64
  br label %bb0
bb0:
  %v58 = getelementptr [26 x i8], [26 x i8]* @.str.0, i64 0, i64 0
  %v59 = call i8* @roast_str_new(i8* %v58, i64 25)
  %v60 = ptrtoint i8* %v59 to i64
  %v61 = call i64 @roast_print(i64 %v60)
  store i64 %v61, i64* %v0
  br label %bb1
bb1:
  %v62 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %v63 = call i8* @roast_str_new(i8* %v62, i64 7)
  %v64 = ptrtoint i8* %v63 to i64
  %v66 = inttoptr i64 %v64 to i8*
  %v65 = call i64 @roast_tcp_server_create(i8* %v66, i64 9999)
  store i64 %v65, i64* %v2
  br label %bb2
bb2:
  %v67 = load i64, i64* %v2
  store i64 %v67, i64* %v1
  %v68 = load i64, i64* %v1
  %v69 = call i64 @roast_str(i64 %v68)
  store i64 %v69, i64* %v4
  br label %bb3
bb3:
  %v70 = getelementptr [19 x i8], [19 x i8]* @.str.2, i64 0, i64 0
  %v71 = call i8* @roast_str_new(i8* %v70, i64 18)
  %v72 = ptrtoint i8* %v71 to i64
  %v73 = load i64, i64* %v4
  %v75 = inttoptr i64 %v72 to i8*
  %v76 = inttoptr i64 %v73 to i8*
  %v77 = call i8* @roast_str_concat(i8* %v75, i8* %v76)
  %v74 = ptrtoint i8* %v77 to i64
  store i64 %v74, i64* %v5
  %v78 = load i64, i64* %v5
  %v79 = call i64 @roast_print(i64 %v78)
  store i64 %v79, i64* %v3
  br label %bb4
bb4:
  %v80 = load i64, i64* %v1
  %v82 = icmp slt i64 %v80, 0
  %v81 = zext i1 %v82 to i64
  store i64 %v81, i64* %v6
  %v83 = load i64, i64* %v6
  store i64 %v83, i64* %v7
  %v84 = load i64, i64* %v7
  %v85 = icmp eq i64 %v84, 1
  br i1 %v85, label %bb5, label %bb6
bb5:
  %v86 = getelementptr [24 x i8], [24 x i8]* @.str.3, i64 0, i64 0
  %v87 = call i8* @roast_str_new(i8* %v86, i64 23)
  %v88 = ptrtoint i8* %v87 to i64
  %v89 = call i64 @roast_print(i64 %v88)
  store i64 %v89, i64* %v8
  br label %bb7
bb6:
  %v90 = getelementptr [29 x i8], [29 x i8]* @.str.4, i64 0, i64 0
  %v91 = call i8* @roast_str_new(i8* %v90, i64 28)
  %v92 = ptrtoint i8* %v91 to i64
  %v93 = call i64 @roast_print(i64 %v92)
  store i64 %v93, i64* %v9
  br label %bb8
bb7:
  ret i64 1
bb8:
  %v94 = load i64, i64* %v1
  %v95 = call i64 @roast_tcp_server_accept(i64 %v94)
  store i64 %v95, i64* %v11
  br label %bb9
bb9:
  %v96 = load i64, i64* %v11
  store i64 %v96, i64* %v10
  %v97 = load i64, i64* %v10
  %v98 = call i64 @roast_str(i64 %v97)
  store i64 %v98, i64* %v13
  br label %bb10
bb10:
  %v99 = getelementptr [19 x i8], [19 x i8]* @.str.5, i64 0, i64 0
  %v100 = call i8* @roast_str_new(i8* %v99, i64 18)
  %v101 = ptrtoint i8* %v100 to i64
  %v102 = load i64, i64* %v13
  %v104 = inttoptr i64 %v101 to i8*
  %v105 = inttoptr i64 %v102 to i8*
  %v106 = call i8* @roast_str_concat(i8* %v104, i8* %v105)
  %v103 = ptrtoint i8* %v106 to i64
  store i64 %v103, i64* %v14
  %v107 = load i64, i64* %v14
  %v108 = call i64 @roast_print(i64 %v107)
  store i64 %v108, i64* %v12
  br label %bb11
bb11:
  %v109 = load i64, i64* %v10
  %v111 = icmp slt i64 %v109, 0
  %v110 = zext i1 %v111 to i64
  store i64 %v110, i64* %v15
  %v112 = load i64, i64* %v15
  store i64 %v112, i64* %v16
  %v113 = load i64, i64* %v16
  %v114 = icmp eq i64 %v113, 1
  br i1 %v114, label %bb12, label %bb13
bb12:
  %v115 = getelementptr [24 x i8], [24 x i8]* @.str.6, i64 0, i64 0
  %v116 = call i8* @roast_str_new(i8* %v115, i64 23)
  %v117 = ptrtoint i8* %v116 to i64
  %v118 = call i64 @roast_print(i64 %v117)
  store i64 %v118, i64* %v17
  br label %bb14
bb13:
  %v119 = getelementptr [26 x i8], [26 x i8]* @.str.7, i64 0, i64 0
  %v120 = call i8* @roast_str_new(i8* %v119, i64 25)
  %v121 = ptrtoint i8* %v120 to i64
  %v122 = call i64 @roast_print(i64 %v121)
  store i64 %v122, i64* %v19
  br label %bb16
bb14:
  %v123 = load i64, i64* %v1
  call void @roast_tcp_server_close(i64 %v123)
  %v124 = add i64 0, 0
  store i64 %v124, i64* %v18
  br label %bb15
bb15:
  ret i64 1
bb16:
  %v125 = load i64, i64* %v10
  %v127 = call i8* @roast_tcp_client_read(i64 %v125, i64 4096)
  %v126 = ptrtoint i8* %v127 to i64
  store i64 %v126, i64* %v21
  br label %bb17
bb17:
  %v128 = load i64, i64* %v21
  store i64 %v128, i64* %v20
  %v129 = inttoptr i64 %v128 to i8*
  call void @roast_incref(i8* %v129)
  %v130 = load i64, i64* %v20
  %v131 = call i64 @roast_len(i64 %v130)
  store i64 %v131, i64* %v24
  br label %bb18
bb18:
  %v132 = load i64, i64* %v24
  %v133 = call i64 @roast_str(i64 %v132)
  store i64 %v133, i64* %v23
  br label %bb19
bb19:
  %v134 = getelementptr [23 x i8], [23 x i8]* @.str.8, i64 0, i64 0
  %v135 = call i8* @roast_str_new(i8* %v134, i64 22)
  %v136 = ptrtoint i8* %v135 to i64
  %v137 = load i64, i64* %v23
  %v139 = inttoptr i64 %v136 to i8*
  %v140 = inttoptr i64 %v137 to i8*
  %v141 = call i8* @roast_str_concat(i8* %v139, i8* %v140)
  %v138 = ptrtoint i8* %v141 to i64
  store i64 %v138, i64* %v25
  %v142 = load i64, i64* %v25
  %v143 = call i64 @roast_print(i64 %v142)
  store i64 %v143, i64* %v22
  br label %bb20
bb20:
  %v144 = getelementptr [32 x i8], [32 x i8]* @.str.9, i64 0, i64 0
  %v145 = call i8* @roast_str_new(i8* %v144, i64 31)
  %v146 = ptrtoint i8* %v145 to i64
  %v147 = call i64 @roast_print(i64 %v146)
  store i64 %v147, i64* %v26
  br label %bb21
bb21:
  %v148 = load i64, i64* %v20
  %v149 = getelementptr [1 x i8], [1 x i8]* @.str.10, i64 0, i64 0
  %v150 = call i8* @roast_str_new(i8* %v149, i64 0)
  %v151 = ptrtoint i8* %v150 to i64
  %v153 = inttoptr i64 %v148 to i8*
  %v154 = inttoptr i64 %v151 to i8*
  %v155 = call i1 @roast_str_eq(i8* %v153, i8* %v154)
  %v152 = zext i1 %v155 to i64
  store i64 %v152, i64* %v27
  %v156 = load i64, i64* %v27
  store i64 %v156, i64* %v28
  %v157 = load i64, i64* %v28
  %v158 = icmp eq i64 %v157, 1
  br i1 %v158, label %bb22, label %bb23
bb22:
  %v159 = getelementptr [18 x i8], [18 x i8]* @.str.11, i64 0, i64 0
  %v160 = call i8* @roast_str_new(i8* %v159, i64 17)
  %v161 = ptrtoint i8* %v160 to i64
  %v162 = call i64 @roast_print(i64 %v161)
  store i64 %v162, i64* %v29
  br label %bb25
bb23:
  %v163 = load i64, i64* %v20
  %v164 = call i64 @roast_len(i64 %v163)
  store i64 %v164, i64* %v32
  br label %bb26
bb24:
  %v165 = getelementptr [23 x i8], [23 x i8]* @.str.12, i64 0, i64 0
  %v166 = call i8* @roast_str_new(i8* %v165, i64 22)
  %v167 = ptrtoint i8* %v166 to i64
  %v168 = call i64 @roast_print(i64 %v167)
  store i64 %v168, i64* %v46
  br label %bb36
bb25:
  br label %bb24
bb26:
  %v169 = load i64, i64* %v32
  %v170 = call i64 @roast_str(i64 %v169)
  store i64 %v170, i64* %v31
  br label %bb27
bb27:
  %v171 = getelementptr [23 x i8], [23 x i8]* @.str.13, i64 0, i64 0
  %v172 = call i8* @roast_str_new(i8* %v171, i64 22)
  %v173 = ptrtoint i8* %v172 to i64
  %v174 = load i64, i64* %v31
  %v176 = inttoptr i64 %v173 to i8*
  %v177 = inttoptr i64 %v174 to i8*
  %v178 = call i8* @roast_str_concat(i8* %v176, i8* %v177)
  %v175 = ptrtoint i8* %v178 to i64
  store i64 %v175, i64* %v33
  %v179 = load i64, i64* %v33
  %v180 = getelementptr [7 x i8], [7 x i8]* @.str.14, i64 0, i64 0
  %v181 = call i8* @roast_str_new(i8* %v180, i64 6)
  %v182 = ptrtoint i8* %v181 to i64
  %v184 = inttoptr i64 %v179 to i8*
  %v185 = inttoptr i64 %v182 to i8*
  %v186 = call i8* @roast_str_concat(i8* %v184, i8* %v185)
  %v183 = ptrtoint i8* %v186 to i64
  store i64 %v183, i64* %v34
  %v187 = load i64, i64* %v34
  %v188 = call i64 @roast_print(i64 %v187)
  store i64 %v188, i64* %v30
  br label %bb28
bb28:
  %v189 = getelementptr [1 x i8], [1 x i8]* @.str.10, i64 0, i64 0
  %v190 = call i8* @roast_str_new(i8* %v189, i64 0)
  %v191 = ptrtoint i8* %v190 to i64
  store i64 %v191, i64* %v35
  %v192 = load i64, i64* %v20
  store i64 %v192, i64* %v36
  br label %bb29
bb29:
  %v193 = load i64, i64* %v20
  %v194 = inttoptr i64 %v193 to i8*
  %v195 = call i8* @roast_iter_new(i8* %v194)
  %v196 = ptrtoint i8* %v195 to i64
  store i64 %v196, i64* %v37
  br label %bb30
bb30:
  %v197 = load i64, i64* %v37
  %v198 = inttoptr i64 %v197 to i8*
  %v199 = alloca i1
  %v200 = call i64 @roast_iter_next(i8* %v198, i1* %v199)
  %v201 = load i1, i1* %v199
  store i64 %v200, i64* %v38
  br i1 %v201, label %bb32, label %bb31
bb31:
  %v202 = load i64, i64* %v38
  %v203 = getelementptr [2 x i8], [2 x i8]* @.str.15, i64 0, i64 0
  %v204 = call i8* @roast_str_new(i8* %v203, i64 1)
  %v205 = ptrtoint i8* %v204 to i64
  %v207 = inttoptr i64 %v202 to i8*
  %v208 = inttoptr i64 %v205 to i8*
  %v209 = call i1 @roast_str_eq(i8* %v207, i8* %v208)
  %v206 = zext i1 %v209 to i64
  store i64 %v206, i64* %v39
  %v210 = load i64, i64* %v38
  %v211 = getelementptr [2 x i8], [2 x i8]* @.str.16, i64 0, i64 0
  %v212 = call i8* @roast_str_new(i8* %v211, i64 1)
  %v213 = ptrtoint i8* %v212 to i64
  %v215 = inttoptr i64 %v210 to i8*
  %v216 = inttoptr i64 %v213 to i8*
  %v217 = call i1 @roast_str_eq(i8* %v215, i8* %v216)
  %v214 = zext i1 %v217 to i64
  store i64 %v214, i64* %v40
  %v218 = load i64, i64* %v39
  %v219 = load i64, i64* %v40
  %v220 = or i64 %v218, %v219
  store i64 %v220, i64* %v41
  %v221 = load i64, i64* %v41
  store i64 %v221, i64* %v42
  %v222 = load i64, i64* %v42
  %v223 = icmp eq i64 %v222, 1
  br i1 %v223, label %bb33, label %bb34
bb32:
  %v224 = getelementptr [13 x i8], [13 x i8]* @.str.17, i64 0, i64 0
  %v225 = call i8* @roast_str_new(i8* %v224, i64 12)
  %v226 = ptrtoint i8* %v225 to i64
  %v227 = load i64, i64* %v35
  %v229 = inttoptr i64 %v226 to i8*
  %v230 = inttoptr i64 %v227 to i8*
  %v231 = call i8* @roast_str_concat(i8* %v229, i8* %v230)
  %v228 = ptrtoint i8* %v231 to i64
  store i64 %v228, i64* %v45
  %v232 = load i64, i64* %v45
  %v233 = call i64 @roast_print(i64 %v232)
  store i64 %v233, i64* %v44
  br label %bb35
bb33:
  br label %bb32
bb34:
  %v234 = load i64, i64* %v35
  %v235 = load i64, i64* %v38
  %v237 = inttoptr i64 %v234 to i8*
  %v238 = inttoptr i64 %v235 to i8*
  %v239 = call i8* @roast_str_concat(i8* %v237, i8* %v238)
  %v236 = ptrtoint i8* %v239 to i64
  store i64 %v236, i64* %v43
  %v240 = load i64, i64* %v43
  store i64 %v240, i64* %v35
  %v241 = inttoptr i64 %v240 to i8*
  call void @roast_incref(i8* %v241)
  br label %bb30
bb35:
  br label %bb24
bb36:
  %v242 = getelementptr [60 x i8], [60 x i8]* @.str.18, i64 0, i64 0
  %v243 = call i8* @roast_str_new(i8* %v242, i64 59)
  %v244 = ptrtoint i8* %v243 to i64
  store i64 %v244, i64* %v47
  %v245 = load i64, i64* %v10
  %v246 = load i64, i64* %v47
  %v248 = inttoptr i64 %v246 to i8*
  %v247 = call i64 @roast_tcp_client_write(i64 %v245, i8* %v248)
  store i64 %v247, i64* %v49
  br label %bb37
bb37:
  %v249 = load i64, i64* %v49
  store i64 %v249, i64* %v48
  %v250 = load i64, i64* %v48
  %v251 = call i64 @roast_str(i64 %v250)
  store i64 %v251, i64* %v51
  br label %bb38
bb38:
  %v252 = getelementptr [18 x i8], [18 x i8]* @.str.19, i64 0, i64 0
  %v253 = call i8* @roast_str_new(i8* %v252, i64 17)
  %v254 = ptrtoint i8* %v253 to i64
  %v255 = load i64, i64* %v51
  %v257 = inttoptr i64 %v254 to i8*
  %v258 = inttoptr i64 %v255 to i8*
  %v259 = call i8* @roast_str_concat(i8* %v257, i8* %v258)
  %v256 = ptrtoint i8* %v259 to i64
  store i64 %v256, i64* %v52
  %v260 = load i64, i64* %v52
  %v261 = call i64 @roast_print(i64 %v260)
  store i64 %v261, i64* %v50
  br label %bb39
bb39:
  %v262 = getelementptr [22 x i8], [22 x i8]* @.str.20, i64 0, i64 0
  %v263 = call i8* @roast_str_new(i8* %v262, i64 21)
  %v264 = ptrtoint i8* %v263 to i64
  %v265 = call i64 @roast_print(i64 %v264)
  store i64 %v265, i64* %v53
  br label %bb40
bb40:
  %v266 = load i64, i64* %v10
  call void @roast_tcp_client_close(i64 %v266)
  %v267 = add i64 0, 0
  store i64 %v267, i64* %v54
  br label %bb41
bb41:
  %v268 = getelementptr [22 x i8], [22 x i8]* @.str.21, i64 0, i64 0
  %v269 = call i8* @roast_str_new(i8* %v268, i64 21)
  %v270 = ptrtoint i8* %v269 to i64
  %v271 = call i64 @roast_print(i64 %v270)
  store i64 %v271, i64* %v55
  br label %bb42
bb42:
  %v272 = load i64, i64* %v1
  call void @roast_tcp_server_close(i64 %v272)
  %v273 = add i64 0, 0
  store i64 %v273, i64* %v56
  br label %bb43
bb43:
  %v274 = getelementptr [10 x i8], [10 x i8]* @.str.22, i64 0, i64 0
  %v275 = call i8* @roast_str_new(i8* %v274, i64 9)
  %v276 = ptrtoint i8* %v275 to i64
  %v277 = call i64 @roast_print(i64 %v276)
  store i64 %v277, i64* %v57
  br label %bb44
bb44:
  ret i64 0
}

