; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.2 = private unnamed_addr constant [28 x i8] c"Inner: returning list with \00"
@.str.3 = private unnamed_addr constant [7 x i8] c" items\00"
@.str.1 = private unnamed_addr constant [7 x i8] c"  i = \00"
@.str.4 = private unnamed_addr constant [24 x i8] c"Outer: calling inner...\00"
@.str.0 = private unnamed_addr constant [18 x i8] c"Inner: counter = \00"
@.str.5 = private unnamed_addr constant [12 x i8] c"Outer: got \00"
@.str.6 = private unnamed_addr constant [3 x i8] c"OK\00"
@.str.7 = private unnamed_addr constant [23 x i8] c"Main: calling outer...\00"
@.str.8 = private unnamed_addr constant [16 x i8] c"Main: result = \00"

; Module-level global variables
@roast_global_87 = global i64 0

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_96() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  br label %bb0
bb0:
  %v6 = getelementptr [23 x i8], [23 x i8]* @.str.7, i64 0, i64 0
  %v7 = call i8* @roast_str_new(i8* %v6, i64 22)
  %v8 = ptrtoint i8* %v7 to i64
  %v9 = call i64 @roast_print(i64 %v8)
  store i64 %v9, i64* %v0
  br label %bb1
bb1:
  %v10 = call i64 @roast_fn_94()
  store i64 %v10, i64* %v2
  br label %bb2
bb2:
  %v11 = load i64, i64* %v2
  store i64 %v11, i64* %v1
  %v12 = inttoptr i64 %v11 to i8*
  call void @roast_incref(i8* %v12)
  %v13 = load i64, i64* %v1
  %v14 = call i64 @roast_str(i64 %v13)
  store i64 %v14, i64* %v4
  br label %bb3
bb3:
  %v15 = getelementptr [16 x i8], [16 x i8]* @.str.8, i64 0, i64 0
  %v16 = call i8* @roast_str_new(i8* %v15, i64 15)
  %v17 = ptrtoint i8* %v16 to i64
  %v18 = load i64, i64* %v4
  %v20 = inttoptr i64 %v17 to i8*
  %v21 = inttoptr i64 %v18 to i8*
  %v22 = call i8* @roast_str_concat(i8* %v20, i8* %v21)
  %v19 = ptrtoint i8* %v22 to i64
  store i64 %v19, i64* %v5
  %v23 = load i64, i64* %v5
  %v24 = call i64 @roast_print(i64 %v23)
  store i64 %v24, i64* %v3
  br label %bb4
bb4:
  ret i64 0
}

define i64 @roast_fn_88() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  br label %bb0
bb0:
  %v18 = load i64, i64* @roast_global_87
  %v19 = call i64 @roast_str(i64 %v18)
  store i64 %v19, i64* %v1
  br label %bb1
bb1:
  %v20 = getelementptr [18 x i8], [18 x i8]* @.str.0, i64 0, i64 0
  %v21 = call i8* @roast_str_new(i8* %v20, i64 17)
  %v22 = ptrtoint i8* %v21 to i64
  %v23 = load i64, i64* %v1
  %v25 = inttoptr i64 %v22 to i8*
  %v26 = inttoptr i64 %v23 to i8*
  %v27 = call i8* @roast_str_concat(i8* %v25, i8* %v26)
  %v24 = ptrtoint i8* %v27 to i64
  store i64 %v24, i64* %v2
  %v28 = load i64, i64* %v2
  %v29 = call i64 @roast_print(i64 %v28)
  store i64 %v29, i64* %v0
  br label %bb2
bb2:
  %v30 = call i8* @roast_list_new(i64 0)
  %v31 = ptrtoint i8* %v30 to i64
  store i64 %v31, i64* %v4
  %v32 = load i64, i64* %v4
  store i64 %v32, i64* %v3
  %v33 = inttoptr i64 %v32 to i8*
  call void @roast_incref(i8* %v33)
  %v34 = load i64, i64* @roast_global_87
  %v35 = call i64 @roast_range(i64 1, i64 %v34, i64 1)
  store i64 %v35, i64* %v5
  br label %bb3
bb3:
  %v36 = load i64, i64* %v5
  store i64 %v36, i64* %v6
  br label %bb4
bb4:
  %v37 = load i64, i64* %v6
  %v38 = inttoptr i64 %v37 to i8*
  %v39 = call i8* @roast_iter_new(i8* %v38)
  %v40 = ptrtoint i8* %v39 to i64
  store i64 %v40, i64* %v7
  br label %bb5
bb5:
  %v41 = load i64, i64* %v7
  %v42 = inttoptr i64 %v41 to i8*
  %v43 = alloca i1
  %v44 = call i64 @roast_iter_next(i8* %v42, i1* %v43)
  %v45 = load i1, i1* %v43
  store i64 %v44, i64* %v8
  br i1 %v45, label %bb7, label %bb6
bb6:
  %v46 = load i64, i64* %v8
  %v47 = call i64 @roast_str(i64 %v46)
  store i64 %v47, i64* %v10
  br label %bb8
bb7:
  %v48 = load i64, i64* %v3
  %v49 = call i64 @roast_len(i64 %v48)
  store i64 %v49, i64* %v15
  br label %bb11
bb8:
  %v50 = getelementptr [7 x i8], [7 x i8]* @.str.1, i64 0, i64 0
  %v51 = call i8* @roast_str_new(i8* %v50, i64 6)
  %v52 = ptrtoint i8* %v51 to i64
  %v53 = load i64, i64* %v10
  %v55 = inttoptr i64 %v52 to i8*
  %v56 = inttoptr i64 %v53 to i8*
  %v57 = call i8* @roast_str_concat(i8* %v55, i8* %v56)
  %v54 = ptrtoint i8* %v57 to i64
  store i64 %v54, i64* %v11
  %v58 = load i64, i64* %v11
  %v59 = call i64 @roast_print(i64 %v58)
  store i64 %v59, i64* %v9
  br label %bb9
bb9:
  %v60 = load i64, i64* %v3
  %v62 = inttoptr i64 %v60 to i8*
  %v63 = load i64, i64* %v8
  call void @roast_list_append(i8* %v62, i64 %v63)
  %v61 = add i64 0, 0
  store i64 %v61, i64* %v12
  br label %bb10
bb10:
  br label %bb5
bb11:
  %v64 = load i64, i64* %v15
  %v65 = call i64 @roast_str(i64 %v64)
  store i64 %v65, i64* %v14
  br label %bb12
bb12:
  %v66 = getelementptr [28 x i8], [28 x i8]* @.str.2, i64 0, i64 0
  %v67 = call i8* @roast_str_new(i8* %v66, i64 27)
  %v68 = ptrtoint i8* %v67 to i64
  %v69 = load i64, i64* %v14
  %v71 = inttoptr i64 %v68 to i8*
  %v72 = inttoptr i64 %v69 to i8*
  %v73 = call i8* @roast_str_concat(i8* %v71, i8* %v72)
  %v70 = ptrtoint i8* %v73 to i64
  store i64 %v70, i64* %v16
  %v74 = load i64, i64* %v16
  %v75 = getelementptr [7 x i8], [7 x i8]* @.str.3, i64 0, i64 0
  %v76 = call i8* @roast_str_new(i8* %v75, i64 6)
  %v77 = ptrtoint i8* %v76 to i64
  %v79 = inttoptr i64 %v74 to i8*
  %v80 = inttoptr i64 %v77 to i8*
  %v81 = call i8* @roast_str_concat(i8* %v79, i8* %v80)
  %v78 = ptrtoint i8* %v81 to i64
  store i64 %v78, i64* %v17
  %v82 = load i64, i64* %v17
  %v83 = call i64 @roast_print(i64 %v82)
  store i64 %v83, i64* %v13
  br label %bb13
bb13:
  %v84 = load i64, i64* %v3
  ret i64 %v84
}

define i64 @roast_fn_94() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  br label %bb0
bb0:
  %v8 = getelementptr [24 x i8], [24 x i8]* @.str.4, i64 0, i64 0
  %v9 = call i8* @roast_str_new(i8* %v8, i64 23)
  %v10 = ptrtoint i8* %v9 to i64
  %v11 = call i64 @roast_print(i64 %v10)
  store i64 %v11, i64* %v0
  br label %bb1
bb1:
  %v12 = call i64 @roast_fn_88()
  store i64 %v12, i64* %v2
  br label %bb2
bb2:
  %v13 = load i64, i64* %v2
  store i64 %v13, i64* %v1
  %v14 = inttoptr i64 %v13 to i8*
  call void @roast_incref(i8* %v14)
  %v15 = load i64, i64* %v1
  %v16 = call i64 @roast_len(i64 %v15)
  store i64 %v16, i64* %v5
  br label %bb3
bb3:
  %v17 = load i64, i64* %v5
  %v18 = call i64 @roast_str(i64 %v17)
  store i64 %v18, i64* %v4
  br label %bb4
bb4:
  %v19 = getelementptr [12 x i8], [12 x i8]* @.str.5, i64 0, i64 0
  %v20 = call i8* @roast_str_new(i8* %v19, i64 11)
  %v21 = ptrtoint i8* %v20 to i64
  %v22 = load i64, i64* %v4
  %v24 = inttoptr i64 %v21 to i8*
  %v25 = inttoptr i64 %v22 to i8*
  %v26 = call i8* @roast_str_concat(i8* %v24, i8* %v25)
  %v23 = ptrtoint i8* %v26 to i64
  store i64 %v23, i64* %v6
  %v27 = load i64, i64* %v6
  %v28 = getelementptr [7 x i8], [7 x i8]* @.str.3, i64 0, i64 0
  %v29 = call i8* @roast_str_new(i8* %v28, i64 6)
  %v30 = ptrtoint i8* %v29 to i64
  %v32 = inttoptr i64 %v27 to i8*
  %v33 = inttoptr i64 %v30 to i8*
  %v34 = call i8* @roast_str_concat(i8* %v32, i8* %v33)
  %v31 = ptrtoint i8* %v34 to i64
  store i64 %v31, i64* %v7
  %v35 = load i64, i64* %v7
  %v36 = call i64 @roast_print(i64 %v35)
  store i64 %v36, i64* %v3
  br label %bb5
bb5:
  %v37 = getelementptr [3 x i8], [3 x i8]* @.str.6, i64 0, i64 0
  %v38 = call i8* @roast_str_new(i8* %v37, i64 2)
  %v39 = ptrtoint i8* %v38 to i64
  ret i64 %v39
}

define i64 @roast_fn_159() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  br label %bb0
bb0:
  store i64 4, i64* %v0
  store i64 4, i64* @roast_global_87
  %v2 = call i64 @roast_fn_96()
  store i64 %v2, i64* %v1
  br label %bb1
bb1:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_159()
    ret i32 0
}

