; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.14 = private unnamed_addr constant [5 x i8] c"  d[\00"
@.str.8 = private unnamed_addr constant [17 x i8] c"v2 == 100: False\00"
@.str.6 = private unnamed_addr constant [16 x i8] c"v1 == 100: True\00"
@.str.13 = private unnamed_addr constant [7 x i8] c"  i = \00"
@.str.15 = private unnamed_addr constant [5 x i8] c"] = \00"
@.str.0 = private unnamed_addr constant [21 x i8] c"1. Setting values...\00"
@.str.16 = private unnamed_addr constant [21 x i8] c"    val == 100: True\00"
@.str.2 = private unnamed_addr constant [8 x i8] c"d[1] = \00"
@.str.7 = private unnamed_addr constant [16 x i8] c"v2 == 100: True\00"
@.str.9 = private unnamed_addr constant [16 x i8] c"v3 == 100: True\00"
@.str.3 = private unnamed_addr constant [8 x i8] c"d[2] = \00"
@.str.1 = private unnamed_addr constant [21 x i8] c"2. Getting values...\00"
@.str.11 = private unnamed_addr constant [22 x i8] c"4. Range iteration...\00"
@.str.10 = private unnamed_addr constant [17 x i8] c"v3 == 100: False\00"
@.str.5 = private unnamed_addr constant [23 x i8] c"3. Comparing values...\00"
@.str.4 = private unnamed_addr constant [8 x i8] c"d[3] = \00"
@.str.12 = private unnamed_addr constant [9 x i8] c"5. Done!\00"
@.str.17 = private unnamed_addr constant [22 x i8] c"    val == 100: False\00"

; Module-level global variables
@roast_global_87 = global i64 0

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_158() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  br label %bb0
bb0:
  %v3 = call i8* @roast_dict_new()
  %v4 = ptrtoint i8* %v3 to i64
  store i64 %v4, i64* %v1
  %v5 = load i64, i64* %v1
  store i64 %v5, i64* %v0
  store i64 %v5, i64* @roast_global_87
  %v6 = inttoptr i64 %v5 to i8*
  call void @roast_incref(i8* %v6)
  %v7 = call i64 @roast_fn_88()
  store i64 %v7, i64* %v2
  br label %bb1
bb1:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_158()
    ret i32 0
}

define i64 @roast_fn_88() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i64
  %v41 = alloca i64
  %v42 = alloca i64
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i64
  %v53 = alloca i64
  %v54 = alloca i64
  %v55 = alloca i64
  %v56 = alloca i64
  %v57 = alloca i64
  br label %bb0
bb0:
  %v58 = getelementptr [21 x i8], [21 x i8]* @.str.0, i64 0, i64 0
  %v59 = call i8* @roast_str_new(i8* %v58, i64 20)
  %v60 = ptrtoint i8* %v59 to i64
  %v61 = call i64 @roast_print(i64 %v60)
  store i64 %v61, i64* %v0
  br label %bb1
bb1:
  %v62 = load i64, i64* @roast_global_87
  store i64 %v62, i64* %v1
  store i64 %v62, i64* @roast_global_87
  store i64 1, i64* %v2
  %v63 = load i64, i64* %v1
  %v64 = load i64, i64* %v2
  %v65 = inttoptr i64 %v63 to i8*
  call void @roast_dict_set(i8* %v65, i64 %v64, i64 100)
  store i64 2, i64* %v3
  %v66 = load i64, i64* %v1
  %v67 = load i64, i64* %v3
  %v68 = inttoptr i64 %v66 to i8*
  call void @roast_dict_set(i8* %v68, i64 %v67, i64 200)
  store i64 3, i64* %v4
  %v69 = load i64, i64* %v1
  %v70 = load i64, i64* %v4
  %v71 = inttoptr i64 %v69 to i8*
  call void @roast_dict_set(i8* %v71, i64 %v70, i64 300)
  %v72 = getelementptr [21 x i8], [21 x i8]* @.str.1, i64 0, i64 0
  %v73 = call i8* @roast_str_new(i8* %v72, i64 20)
  %v74 = ptrtoint i8* %v73 to i64
  %v75 = call i64 @roast_print(i64 %v74)
  store i64 %v75, i64* %v5
  br label %bb2
bb2:
  %v76 = load i64, i64* %v1
  store i64 %v76, i64* %v7
  %v77 = inttoptr i64 %v76 to i8*
  call void @roast_incref(i8* %v77)
  store i64 1, i64* %v8
  %v78 = load i64, i64* %v7
  %v79 = load i64, i64* %v8
  %v81 = inttoptr i64 %v78 to i8*
  %v80 = call i64 @roast_dict_get(i8* %v81, i64 %v79)
  store i64 %v80, i64* %v6
  %v82 = load i64, i64* %v6
  %v83 = call i64 @roast_str(i64 %v82)
  store i64 %v83, i64* %v10
  br label %bb3
bb3:
  %v84 = getelementptr [8 x i8], [8 x i8]* @.str.2, i64 0, i64 0
  %v85 = call i8* @roast_str_new(i8* %v84, i64 7)
  %v86 = ptrtoint i8* %v85 to i64
  %v87 = load i64, i64* %v10
  %v89 = inttoptr i64 %v86 to i8*
  %v90 = inttoptr i64 %v87 to i8*
  %v91 = call i8* @roast_str_concat(i8* %v89, i8* %v90)
  %v88 = ptrtoint i8* %v91 to i64
  store i64 %v88, i64* %v11
  %v92 = load i64, i64* %v11
  %v93 = call i64 @roast_print(i64 %v92)
  store i64 %v93, i64* %v9
  br label %bb4
bb4:
  %v94 = load i64, i64* %v1
  store i64 %v94, i64* %v13
  %v95 = inttoptr i64 %v94 to i8*
  call void @roast_incref(i8* %v95)
  store i64 2, i64* %v14
  %v96 = load i64, i64* %v13
  %v97 = load i64, i64* %v14
  %v99 = inttoptr i64 %v96 to i8*
  %v98 = call i64 @roast_dict_get(i8* %v99, i64 %v97)
  store i64 %v98, i64* %v12
  %v100 = load i64, i64* %v12
  %v101 = call i64 @roast_str(i64 %v100)
  store i64 %v101, i64* %v16
  br label %bb5
bb5:
  %v102 = getelementptr [8 x i8], [8 x i8]* @.str.3, i64 0, i64 0
  %v103 = call i8* @roast_str_new(i8* %v102, i64 7)
  %v104 = ptrtoint i8* %v103 to i64
  %v105 = load i64, i64* %v16
  %v107 = inttoptr i64 %v104 to i8*
  %v108 = inttoptr i64 %v105 to i8*
  %v109 = call i8* @roast_str_concat(i8* %v107, i8* %v108)
  %v106 = ptrtoint i8* %v109 to i64
  store i64 %v106, i64* %v17
  %v110 = load i64, i64* %v17
  %v111 = call i64 @roast_print(i64 %v110)
  store i64 %v111, i64* %v15
  br label %bb6
bb6:
  %v112 = load i64, i64* %v1
  store i64 %v112, i64* %v19
  %v113 = inttoptr i64 %v112 to i8*
  call void @roast_incref(i8* %v113)
  store i64 3, i64* %v20
  %v114 = load i64, i64* %v19
  %v115 = load i64, i64* %v20
  %v117 = inttoptr i64 %v114 to i8*
  %v116 = call i64 @roast_dict_get(i8* %v117, i64 %v115)
  store i64 %v116, i64* %v18
  %v118 = load i64, i64* %v18
  %v119 = call i64 @roast_str(i64 %v118)
  store i64 %v119, i64* %v22
  br label %bb7
bb7:
  %v120 = getelementptr [8 x i8], [8 x i8]* @.str.4, i64 0, i64 0
  %v121 = call i8* @roast_str_new(i8* %v120, i64 7)
  %v122 = ptrtoint i8* %v121 to i64
  %v123 = load i64, i64* %v22
  %v125 = inttoptr i64 %v122 to i8*
  %v126 = inttoptr i64 %v123 to i8*
  %v127 = call i8* @roast_str_concat(i8* %v125, i8* %v126)
  %v124 = ptrtoint i8* %v127 to i64
  store i64 %v124, i64* %v23
  %v128 = load i64, i64* %v23
  %v129 = call i64 @roast_print(i64 %v128)
  store i64 %v129, i64* %v21
  br label %bb8
bb8:
  %v130 = getelementptr [23 x i8], [23 x i8]* @.str.5, i64 0, i64 0
  %v131 = call i8* @roast_str_new(i8* %v130, i64 22)
  %v132 = ptrtoint i8* %v131 to i64
  %v133 = call i64 @roast_print(i64 %v132)
  store i64 %v133, i64* %v24
  br label %bb9
bb9:
  %v134 = load i64, i64* %v6
  %v136 = icmp eq i64 %v134, 100
  %v135 = zext i1 %v136 to i64
  store i64 %v135, i64* %v25
  %v137 = load i64, i64* %v25
  store i64 %v137, i64* %v26
  %v138 = load i64, i64* %v26
  %v139 = icmp eq i64 %v138, 1
  br i1 %v139, label %bb10, label %bb11
bb10:
  %v140 = getelementptr [16 x i8], [16 x i8]* @.str.6, i64 0, i64 0
  %v141 = call i8* @roast_str_new(i8* %v140, i64 15)
  %v142 = ptrtoint i8* %v141 to i64
  %v143 = call i64 @roast_print(i64 %v142)
  store i64 %v143, i64* %v27
  br label %bb12
bb11:
  %v144 = load i64, i64* %v12
  %v146 = icmp eq i64 %v144, 100
  %v145 = zext i1 %v146 to i64
  store i64 %v145, i64* %v28
  %v147 = load i64, i64* %v28
  store i64 %v147, i64* %v29
  %v148 = load i64, i64* %v29
  %v149 = icmp eq i64 %v148, 1
  br i1 %v149, label %bb13, label %bb14
bb12:
  br label %bb11
bb13:
  %v150 = getelementptr [16 x i8], [16 x i8]* @.str.7, i64 0, i64 0
  %v151 = call i8* @roast_str_new(i8* %v150, i64 15)
  %v152 = ptrtoint i8* %v151 to i64
  %v153 = call i64 @roast_print(i64 %v152)
  store i64 %v153, i64* %v30
  br label %bb16
bb14:
  %v154 = getelementptr [17 x i8], [17 x i8]* @.str.8, i64 0, i64 0
  %v155 = call i8* @roast_str_new(i8* %v154, i64 16)
  %v156 = ptrtoint i8* %v155 to i64
  %v157 = call i64 @roast_print(i64 %v156)
  store i64 %v157, i64* %v31
  br label %bb17
bb15:
  %v158 = load i64, i64* %v18
  %v160 = icmp eq i64 %v158, 100
  %v159 = zext i1 %v160 to i64
  store i64 %v159, i64* %v32
  %v161 = load i64, i64* %v32
  store i64 %v161, i64* %v33
  %v162 = load i64, i64* %v33
  %v163 = icmp eq i64 %v162, 1
  br i1 %v163, label %bb18, label %bb19
bb16:
  br label %bb15
bb17:
  br label %bb15
bb18:
  %v164 = getelementptr [16 x i8], [16 x i8]* @.str.9, i64 0, i64 0
  %v165 = call i8* @roast_str_new(i8* %v164, i64 15)
  %v166 = ptrtoint i8* %v165 to i64
  %v167 = call i64 @roast_print(i64 %v166)
  store i64 %v167, i64* %v34
  br label %bb21
bb19:
  %v168 = getelementptr [17 x i8], [17 x i8]* @.str.10, i64 0, i64 0
  %v169 = call i8* @roast_str_new(i8* %v168, i64 16)
  %v170 = ptrtoint i8* %v169 to i64
  %v171 = call i64 @roast_print(i64 %v170)
  store i64 %v171, i64* %v35
  br label %bb22
bb20:
  %v172 = getelementptr [22 x i8], [22 x i8]* @.str.11, i64 0, i64 0
  %v173 = call i8* @roast_str_new(i8* %v172, i64 21)
  %v174 = ptrtoint i8* %v173 to i64
  %v175 = call i64 @roast_print(i64 %v174)
  store i64 %v175, i64* %v36
  br label %bb23
bb21:
  br label %bb20
bb22:
  br label %bb20
bb23:
  %v176 = call i64 @roast_range(i64 1, i64 4, i64 1)
  store i64 %v176, i64* %v37
  br label %bb24
bb24:
  %v177 = load i64, i64* %v37
  store i64 %v177, i64* %v38
  br label %bb25
bb25:
  %v178 = load i64, i64* %v38
  %v179 = inttoptr i64 %v178 to i8*
  %v180 = call i8* @roast_iter_new(i8* %v179)
  %v181 = ptrtoint i8* %v180 to i64
  store i64 %v181, i64* %v39
  br label %bb26
bb26:
  %v182 = load i64, i64* %v39
  %v183 = inttoptr i64 %v182 to i8*
  %v184 = alloca i1
  %v185 = call i64 @roast_iter_next(i8* %v183, i1* %v184)
  %v186 = load i1, i1* %v184
  store i64 %v185, i64* %v40
  br i1 %v186, label %bb28, label %bb27
bb27:
  %v187 = load i64, i64* %v40
  %v188 = call i64 @roast_str(i64 %v187)
  store i64 %v188, i64* %v42
  br label %bb29
bb28:
  %v189 = getelementptr [9 x i8], [9 x i8]* @.str.12, i64 0, i64 0
  %v190 = call i8* @roast_str_new(i8* %v189, i64 8)
  %v191 = ptrtoint i8* %v190 to i64
  %v192 = call i64 @roast_print(i64 %v191)
  store i64 %v192, i64* %v57
  br label %bb39
bb29:
  %v193 = getelementptr [7 x i8], [7 x i8]* @.str.13, i64 0, i64 0
  %v194 = call i8* @roast_str_new(i8* %v193, i64 6)
  %v195 = ptrtoint i8* %v194 to i64
  %v196 = load i64, i64* %v42
  %v198 = inttoptr i64 %v195 to i8*
  %v199 = inttoptr i64 %v196 to i8*
  %v200 = call i8* @roast_str_concat(i8* %v198, i8* %v199)
  %v197 = ptrtoint i8* %v200 to i64
  store i64 %v197, i64* %v43
  %v201 = load i64, i64* %v43
  %v202 = call i64 @roast_print(i64 %v201)
  store i64 %v202, i64* %v41
  br label %bb30
bb30:
  %v203 = load i64, i64* %v1
  store i64 %v203, i64* %v45
  %v204 = inttoptr i64 %v203 to i8*
  call void @roast_incref(i8* %v204)
  %v205 = load i64, i64* %v40
  store i64 %v205, i64* %v46
  %v206 = load i64, i64* %v45
  %v207 = load i64, i64* %v46
  %v209 = inttoptr i64 %v206 to i8*
  %v208 = call i64 @roast_dict_get(i8* %v209, i64 %v207)
  store i64 %v208, i64* %v44
  %v210 = load i64, i64* %v40
  %v211 = call i64 @roast_str(i64 %v210)
  store i64 %v211, i64* %v48
  br label %bb31
bb31:
  %v212 = getelementptr [5 x i8], [5 x i8]* @.str.14, i64 0, i64 0
  %v213 = call i8* @roast_str_new(i8* %v212, i64 4)
  %v214 = ptrtoint i8* %v213 to i64
  %v215 = load i64, i64* %v48
  %v217 = inttoptr i64 %v214 to i8*
  %v218 = inttoptr i64 %v215 to i8*
  %v219 = call i8* @roast_str_concat(i8* %v217, i8* %v218)
  %v216 = ptrtoint i8* %v219 to i64
  store i64 %v216, i64* %v49
  %v220 = load i64, i64* %v49
  %v221 = getelementptr [5 x i8], [5 x i8]* @.str.15, i64 0, i64 0
  %v222 = call i8* @roast_str_new(i8* %v221, i64 4)
  %v223 = ptrtoint i8* %v222 to i64
  %v225 = inttoptr i64 %v220 to i8*
  %v226 = inttoptr i64 %v223 to i8*
  %v227 = call i8* @roast_str_concat(i8* %v225, i8* %v226)
  %v224 = ptrtoint i8* %v227 to i64
  store i64 %v224, i64* %v50
  %v228 = load i64, i64* %v44
  %v229 = call i64 @roast_str(i64 %v228)
  store i64 %v229, i64* %v51
  br label %bb32
bb32:
  %v230 = load i64, i64* %v50
  %v231 = load i64, i64* %v51
  %v233 = inttoptr i64 %v230 to i8*
  %v234 = inttoptr i64 %v231 to i8*
  %v235 = call i8* @roast_str_concat(i8* %v233, i8* %v234)
  %v232 = ptrtoint i8* %v235 to i64
  store i64 %v232, i64* %v52
  %v236 = load i64, i64* %v52
  %v237 = call i64 @roast_print(i64 %v236)
  store i64 %v237, i64* %v47
  br label %bb33
bb33:
  %v238 = load i64, i64* %v44
  %v240 = icmp eq i64 %v238, 100
  %v239 = zext i1 %v240 to i64
  store i64 %v239, i64* %v53
  %v241 = load i64, i64* %v53
  store i64 %v241, i64* %v54
  %v242 = load i64, i64* %v54
  %v243 = icmp eq i64 %v242, 1
  br i1 %v243, label %bb34, label %bb35
bb34:
  %v244 = getelementptr [21 x i8], [21 x i8]* @.str.16, i64 0, i64 0
  %v245 = call i8* @roast_str_new(i8* %v244, i64 20)
  %v246 = ptrtoint i8* %v245 to i64
  %v247 = call i64 @roast_print(i64 %v246)
  store i64 %v247, i64* %v55
  br label %bb37
bb35:
  %v248 = getelementptr [22 x i8], [22 x i8]* @.str.17, i64 0, i64 0
  %v249 = call i8* @roast_str_new(i8* %v248, i64 21)
  %v250 = ptrtoint i8* %v249 to i64
  %v251 = call i64 @roast_print(i64 %v250)
  store i64 %v251, i64* %v56
  br label %bb38
bb36:
  br label %bb26
bb37:
  br label %bb36
bb38:
  br label %bb36
bb39:
  ret i64 0
}

