; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.10 = private unnamed_addr constant [18 x i8] c" items for user 1\00"
@.str.15 = private unnamed_addr constant [1 x i8] c"\00"
@.str.5 = private unnamed_addr constant [8 x i8] c"  Item \00"
@.str.12 = private unnamed_addr constant [7 x i8] c"Task 1\00"
@.str.2 = private unnamed_addr constant [9 x i8] c" (owner=\00"
@.str.7 = private unnamed_addr constant [19 x i8] c"    Matches user 1\00"
@.str.14 = private unnamed_addr constant [7 x i8] c"Task 3\00"
@.str.13 = private unnamed_addr constant [7 x i8] c"Task 2\00"
@.str.16 = private unnamed_addr constant [21 x i8] c"2. Checking items...\00"
@.str.0 = private unnamed_addr constant [12 x i8] c"Added item \00"
@.str.3 = private unnamed_addr constant [2 x i8] c")\00"
@.str.11 = private unnamed_addr constant [19 x i8] c"1. Adding items...\00"
@.str.9 = private unnamed_addr constant [7 x i8] c"Found \00"
@.str.1 = private unnamed_addr constant [3 x i8] c": \00"
@.str.18 = private unnamed_addr constant [9 x i8] c"3. Done!\00"
@.str.8 = private unnamed_addr constant [26 x i8] c"    Does not match user 1\00"
@.str.4 = private unnamed_addr constant [21 x i8] c"Checking items 1 to \00"
@.str.17 = private unnamed_addr constant [9 x i8] c"Result: \00"
@.str.6 = private unnamed_addr constant [13 x i8] c"    Owner = \00"

; Module-level global variables
@roast_global_87 = global i64 0
@roast_global_88 = global i64 0
@roast_global_89 = global i64 0

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_95() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  br label %bb0
bb0:
  %v28 = load i64, i64* @roast_global_89
  %v29 = call i64 @roast_str(i64 %v28)
  store i64 %v29, i64* %v1
  br label %bb1
bb1:
  %v30 = getelementptr [21 x i8], [21 x i8]* @.str.4, i64 0, i64 0
  %v31 = call i8* @roast_str_new(i8* %v30, i64 20)
  %v32 = ptrtoint i8* %v31 to i64
  %v33 = load i64, i64* %v1
  %v35 = inttoptr i64 %v32 to i8*
  %v36 = inttoptr i64 %v33 to i8*
  %v37 = call i8* @roast_str_concat(i8* %v35, i8* %v36)
  %v34 = ptrtoint i8* %v37 to i64
  store i64 %v34, i64* %v2
  %v38 = load i64, i64* %v2
  %v39 = call i64 @roast_print(i64 %v38)
  store i64 %v39, i64* %v0
  br label %bb2
bb2:
  store i64 0, i64* %v3
  %v40 = load i64, i64* @roast_global_89
  %v41 = call i64 @roast_range(i64 1, i64 %v40, i64 1)
  store i64 %v41, i64* %v4
  br label %bb3
bb3:
  %v42 = load i64, i64* %v4
  store i64 %v42, i64* %v5
  br label %bb4
bb4:
  %v43 = load i64, i64* %v5
  %v44 = inttoptr i64 %v43 to i8*
  %v45 = call i8* @roast_iter_new(i8* %v44)
  %v46 = ptrtoint i8* %v45 to i64
  store i64 %v46, i64* %v6
  br label %bb5
bb5:
  %v47 = load i64, i64* %v6
  %v48 = inttoptr i64 %v47 to i8*
  %v49 = alloca i1
  %v50 = call i64 @roast_iter_next(i8* %v48, i1* %v49)
  %v51 = load i1, i1* %v49
  store i64 %v50, i64* %v7
  br i1 %v51, label %bb7, label %bb6
bb6:
  %v52 = load i64, i64* %v7
  %v53 = call i64 @roast_str(i64 %v52)
  store i64 %v53, i64* %v9
  br label %bb8
bb7:
  %v54 = load i64, i64* %v3
  %v55 = call i64 @roast_str(i64 %v54)
  store i64 %v55, i64* %v25
  br label %bb19
bb8:
  %v56 = getelementptr [8 x i8], [8 x i8]* @.str.5, i64 0, i64 0
  %v57 = call i8* @roast_str_new(i8* %v56, i64 7)
  %v58 = ptrtoint i8* %v57 to i64
  %v59 = load i64, i64* %v9
  %v61 = inttoptr i64 %v58 to i8*
  %v62 = inttoptr i64 %v59 to i8*
  %v63 = call i8* @roast_str_concat(i8* %v61, i8* %v62)
  %v60 = ptrtoint i8* %v63 to i64
  store i64 %v60, i64* %v10
  %v64 = load i64, i64* %v10
  %v65 = call i64 @roast_print(i64 %v64)
  store i64 %v65, i64* %v8
  br label %bb9
bb9:
  %v66 = load i64, i64* %v7
  %v67 = load i64, i64* @roast_global_88
  %v69 = inttoptr i64 %v67 to i8*
  %v70 = call i1 @roast_dict_contains(i8* %v69, i64 %v66)
  %v68 = zext i1 %v70 to i64
  store i64 %v68, i64* %v11
  %v71 = load i64, i64* %v11
  store i64 %v71, i64* %v12
  %v72 = load i64, i64* %v12
  %v73 = icmp eq i64 %v72, 1
  br i1 %v73, label %bb10, label %bb11
bb10:
  %v74 = load i64, i64* @roast_global_88
  store i64 %v74, i64* %v14
  %v75 = load i64, i64* %v7
  store i64 %v75, i64* %v15
  %v76 = load i64, i64* %v14
  %v77 = load i64, i64* %v15
  %v79 = inttoptr i64 %v76 to i8*
  %v78 = call i64 @roast_dict_get(i8* %v79, i64 %v77)
  store i64 %v78, i64* %v13
  %v80 = load i64, i64* %v13
  %v81 = call i64 @roast_str(i64 %v80)
  store i64 %v81, i64* %v17
  br label %bb12
bb11:
  br label %bb5
bb12:
  %v82 = getelementptr [13 x i8], [13 x i8]* @.str.6, i64 0, i64 0
  %v83 = call i8* @roast_str_new(i8* %v82, i64 12)
  %v84 = ptrtoint i8* %v83 to i64
  %v85 = load i64, i64* %v17
  %v87 = inttoptr i64 %v84 to i8*
  %v88 = inttoptr i64 %v85 to i8*
  %v89 = call i8* @roast_str_concat(i8* %v87, i8* %v88)
  %v86 = ptrtoint i8* %v89 to i64
  store i64 %v86, i64* %v18
  %v90 = load i64, i64* %v18
  %v91 = call i64 @roast_print(i64 %v90)
  store i64 %v91, i64* %v16
  br label %bb13
bb13:
  %v92 = load i64, i64* %v13
  %v94 = icmp eq i64 %v92, 1
  %v93 = zext i1 %v94 to i64
  store i64 %v93, i64* %v19
  %v95 = load i64, i64* %v19
  store i64 %v95, i64* %v20
  %v96 = load i64, i64* %v20
  %v97 = icmp eq i64 %v96, 1
  br i1 %v97, label %bb14, label %bb15
bb14:
  %v98 = getelementptr [19 x i8], [19 x i8]* @.str.7, i64 0, i64 0
  %v99 = call i8* @roast_str_new(i8* %v98, i64 18)
  %v100 = ptrtoint i8* %v99 to i64
  %v101 = call i64 @roast_print(i64 %v100)
  store i64 %v101, i64* %v21
  br label %bb17
bb15:
  %v102 = getelementptr [26 x i8], [26 x i8]* @.str.8, i64 0, i64 0
  %v103 = call i8* @roast_str_new(i8* %v102, i64 25)
  %v104 = ptrtoint i8* %v103 to i64
  %v105 = call i64 @roast_print(i64 %v104)
  store i64 %v105, i64* %v23
  br label %bb18
bb16:
  br label %bb11
bb17:
  %v106 = load i64, i64* %v3
  %v107 = add i64 %v106, 1
  store i64 %v107, i64* %v22
  %v108 = load i64, i64* %v22
  store i64 %v108, i64* %v3
  br label %bb16
bb18:
  br label %bb16
bb19:
  %v109 = getelementptr [7 x i8], [7 x i8]* @.str.9, i64 0, i64 0
  %v110 = call i8* @roast_str_new(i8* %v109, i64 6)
  %v111 = ptrtoint i8* %v110 to i64
  %v112 = load i64, i64* %v25
  %v114 = inttoptr i64 %v111 to i8*
  %v115 = inttoptr i64 %v112 to i8*
  %v116 = call i8* @roast_str_concat(i8* %v114, i8* %v115)
  %v113 = ptrtoint i8* %v116 to i64
  store i64 %v113, i64* %v26
  %v117 = load i64, i64* %v26
  %v118 = getelementptr [18 x i8], [18 x i8]* @.str.10, i64 0, i64 0
  %v119 = call i8* @roast_str_new(i8* %v118, i64 17)
  %v120 = ptrtoint i8* %v119 to i64
  %v122 = inttoptr i64 %v117 to i8*
  %v123 = inttoptr i64 %v120 to i8*
  %v124 = call i8* @roast_str_concat(i8* %v122, i8* %v123)
  %v121 = ptrtoint i8* %v124 to i64
  store i64 %v121, i64* %v27
  %v125 = load i64, i64* %v27
  %v126 = call i64 @roast_print(i64 %v125)
  store i64 %v126, i64* %v24
  br label %bb20
bb20:
  %v127 = load i64, i64* %v3
  ret i64 %v127
}

define i64 @roast_fn_99() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  br label %bb0
bb0:
  %v13 = getelementptr [19 x i8], [19 x i8]* @.str.11, i64 0, i64 0
  %v14 = call i8* @roast_str_new(i8* %v13, i64 18)
  %v15 = ptrtoint i8* %v14 to i64
  %v16 = call i64 @roast_print(i64 %v15)
  store i64 %v16, i64* %v0
  br label %bb1
bb1:
  %v17 = getelementptr [7 x i8], [7 x i8]* @.str.12, i64 0, i64 0
  %v18 = call i8* @roast_str_new(i8* %v17, i64 6)
  %v19 = ptrtoint i8* %v18 to i64
  %v20 = call i64 @roast_fn_90(i64 1, i64 %v19)
  store i64 %v20, i64* %v1
  br label %bb2
bb2:
  %v21 = getelementptr [7 x i8], [7 x i8]* @.str.13, i64 0, i64 0
  %v22 = call i8* @roast_str_new(i8* %v21, i64 6)
  %v23 = ptrtoint i8* %v22 to i64
  %v24 = call i64 @roast_fn_90(i64 1, i64 %v23)
  store i64 %v24, i64* %v2
  br label %bb3
bb3:
  %v25 = getelementptr [7 x i8], [7 x i8]* @.str.14, i64 0, i64 0
  %v26 = call i8* @roast_str_new(i8* %v25, i64 6)
  %v27 = ptrtoint i8* %v26 to i64
  %v28 = call i64 @roast_fn_90(i64 2, i64 %v27)
  store i64 %v28, i64* %v3
  br label %bb4
bb4:
  %v29 = getelementptr [1 x i8], [1 x i8]* @.str.15, i64 0, i64 0
  %v30 = call i8* @roast_str_new(i8* %v29, i64 0)
  %v31 = ptrtoint i8* %v30 to i64
  %v32 = call i64 @roast_print(i64 %v31)
  store i64 %v32, i64* %v4
  br label %bb5
bb5:
  %v33 = getelementptr [21 x i8], [21 x i8]* @.str.16, i64 0, i64 0
  %v34 = call i8* @roast_str_new(i8* %v33, i64 20)
  %v35 = ptrtoint i8* %v34 to i64
  %v36 = call i64 @roast_print(i64 %v35)
  store i64 %v36, i64* %v5
  br label %bb6
bb6:
  %v37 = call i64 @roast_fn_95()
  store i64 %v37, i64* %v7
  br label %bb7
bb7:
  %v38 = load i64, i64* %v7
  store i64 %v38, i64* %v6
  %v39 = load i64, i64* %v6
  %v40 = call i64 @roast_str(i64 %v39)
  store i64 %v40, i64* %v9
  br label %bb8
bb8:
  %v41 = getelementptr [9 x i8], [9 x i8]* @.str.17, i64 0, i64 0
  %v42 = call i8* @roast_str_new(i8* %v41, i64 8)
  %v43 = ptrtoint i8* %v42 to i64
  %v44 = load i64, i64* %v9
  %v46 = inttoptr i64 %v43 to i8*
  %v47 = inttoptr i64 %v44 to i8*
  %v48 = call i8* @roast_str_concat(i8* %v46, i8* %v47)
  %v45 = ptrtoint i8* %v48 to i64
  store i64 %v45, i64* %v10
  %v49 = load i64, i64* %v10
  %v50 = call i64 @roast_print(i64 %v49)
  store i64 %v50, i64* %v8
  br label %bb9
bb9:
  %v51 = getelementptr [1 x i8], [1 x i8]* @.str.15, i64 0, i64 0
  %v52 = call i8* @roast_str_new(i8* %v51, i64 0)
  %v53 = ptrtoint i8* %v52 to i64
  %v54 = call i64 @roast_print(i64 %v53)
  store i64 %v54, i64* %v11
  br label %bb10
bb10:
  %v55 = getelementptr [9 x i8], [9 x i8]* @.str.18, i64 0, i64 0
  %v56 = call i8* @roast_str_new(i8* %v55, i64 8)
  %v57 = ptrtoint i8* %v56 to i64
  %v58 = call i64 @roast_print(i64 %v57)
  store i64 %v58, i64* %v12
  br label %bb11
bb11:
  ret i64 0
}

define i64 @roast_fn_163() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  br label %bb0
bb0:
  %v6 = call i8* @roast_dict_new()
  %v7 = ptrtoint i8* %v6 to i64
  store i64 %v7, i64* %v1
  %v8 = load i64, i64* %v1
  store i64 %v8, i64* %v0
  store i64 %v8, i64* @roast_global_87
  %v9 = inttoptr i64 %v8 to i8*
  call void @roast_incref(i8* %v9)
  %v10 = call i8* @roast_dict_new()
  %v11 = ptrtoint i8* %v10 to i64
  store i64 %v11, i64* %v3
  %v12 = load i64, i64* %v3
  store i64 %v12, i64* %v2
  store i64 %v12, i64* @roast_global_88
  %v13 = inttoptr i64 %v12 to i8*
  call void @roast_incref(i8* %v13)
  store i64 1, i64* %v4
  store i64 1, i64* @roast_global_89
  %v14 = call i64 @roast_fn_99()
  store i64 %v14, i64* %v5
  br label %bb1
bb1:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_163()
    ret i32 0
}

define i64 @roast_fn_90(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  br label %bb0
bb0:
  %v19 = load i64, i64* @roast_global_89
  store i64 %v19, i64* %v2
  %v20 = load i64, i64* @roast_global_89
  %v21 = add i64 %v20, 1
  store i64 %v21, i64* %v3
  %v22 = load i64, i64* @roast_global_89
  store i64 %v22, i64* %v4
  store i64 %v22, i64* @roast_global_89
  %v23 = load i64, i64* %v3
  store i64 %v23, i64* %v4
  store i64 %v23, i64* @roast_global_89
  %v24 = load i64, i64* @roast_global_87
  store i64 %v24, i64* %v5
  store i64 %v24, i64* @roast_global_87
  %v25 = load i64, i64* %v2
  store i64 %v25, i64* %v6
  %v26 = load i64, i64* %v1
  %v27 = load i64, i64* %v5
  %v28 = load i64, i64* %v6
  %v29 = inttoptr i64 %v27 to i8*
  call void @roast_dict_set(i8* %v29, i64 %v28, i64 %v26)
  %v30 = load i64, i64* @roast_global_88
  store i64 %v30, i64* %v7
  store i64 %v30, i64* @roast_global_88
  %v31 = load i64, i64* %v2
  store i64 %v31, i64* %v8
  %v32 = load i64, i64* %v0
  %v33 = load i64, i64* %v7
  %v34 = load i64, i64* %v8
  %v35 = inttoptr i64 %v33 to i8*
  call void @roast_dict_set(i8* %v35, i64 %v34, i64 %v32)
  %v36 = load i64, i64* %v2
  %v37 = call i64 @roast_str(i64 %v36)
  store i64 %v37, i64* %v10
  br label %bb1
bb1:
  %v38 = getelementptr [12 x i8], [12 x i8]* @.str.0, i64 0, i64 0
  %v39 = call i8* @roast_str_new(i8* %v38, i64 11)
  %v40 = ptrtoint i8* %v39 to i64
  %v41 = load i64, i64* %v10
  %v43 = inttoptr i64 %v40 to i8*
  %v44 = inttoptr i64 %v41 to i8*
  %v45 = call i8* @roast_str_concat(i8* %v43, i8* %v44)
  %v42 = ptrtoint i8* %v45 to i64
  store i64 %v42, i64* %v11
  %v46 = load i64, i64* %v11
  %v47 = getelementptr [3 x i8], [3 x i8]* @.str.1, i64 0, i64 0
  %v48 = call i8* @roast_str_new(i8* %v47, i64 2)
  %v49 = ptrtoint i8* %v48 to i64
  %v51 = inttoptr i64 %v46 to i8*
  %v52 = inttoptr i64 %v49 to i8*
  %v53 = call i8* @roast_str_concat(i8* %v51, i8* %v52)
  %v50 = ptrtoint i8* %v53 to i64
  store i64 %v50, i64* %v12
  %v54 = load i64, i64* %v1
  %v55 = call i64 @roast_str(i64 %v54)
  store i64 %v55, i64* %v13
  br label %bb2
bb2:
  %v56 = load i64, i64* %v12
  %v57 = load i64, i64* %v13
  %v59 = inttoptr i64 %v56 to i8*
  %v60 = inttoptr i64 %v57 to i8*
  %v61 = call i8* @roast_str_concat(i8* %v59, i8* %v60)
  %v58 = ptrtoint i8* %v61 to i64
  store i64 %v58, i64* %v14
  %v62 = load i64, i64* %v14
  %v63 = getelementptr [9 x i8], [9 x i8]* @.str.2, i64 0, i64 0
  %v64 = call i8* @roast_str_new(i8* %v63, i64 8)
  %v65 = ptrtoint i8* %v64 to i64
  %v67 = inttoptr i64 %v62 to i8*
  %v68 = inttoptr i64 %v65 to i8*
  %v69 = call i8* @roast_str_concat(i8* %v67, i8* %v68)
  %v66 = ptrtoint i8* %v69 to i64
  store i64 %v66, i64* %v15
  %v70 = load i64, i64* %v0
  %v71 = call i64 @roast_str(i64 %v70)
  store i64 %v71, i64* %v16
  br label %bb3
bb3:
  %v72 = load i64, i64* %v15
  %v73 = load i64, i64* %v16
  %v75 = inttoptr i64 %v72 to i8*
  %v76 = inttoptr i64 %v73 to i8*
  %v77 = call i8* @roast_str_concat(i8* %v75, i8* %v76)
  %v74 = ptrtoint i8* %v77 to i64
  store i64 %v74, i64* %v17
  %v78 = load i64, i64* %v17
  %v79 = getelementptr [2 x i8], [2 x i8]* @.str.3, i64 0, i64 0
  %v80 = call i8* @roast_str_new(i8* %v79, i64 1)
  %v81 = ptrtoint i8* %v80 to i64
  %v83 = inttoptr i64 %v78 to i8*
  %v84 = inttoptr i64 %v81 to i8*
  %v85 = call i8* @roast_str_concat(i8* %v83, i8* %v84)
  %v82 = ptrtoint i8* %v85 to i64
  store i64 %v82, i64* %v18
  %v86 = load i64, i64* %v18
  %v87 = call i64 @roast_print(i64 %v86)
  store i64 %v87, i64* %v9
  br label %bb4
bb4:
  %v88 = load i64, i64* %v2
  ret i64 %v88
}

