; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.20 = private unnamed_addr constant [16 x i8] c"Main: result = \00"
@.str.0 = private unnamed_addr constant [18 x i8] c"Inner: user_id = \00"
@.str.7 = private unnamed_addr constant [32 x i8] c"      val == user_id, appending\00"
@.str.10 = private unnamed_addr constant [7 x i8] c" items\00"
@.str.1 = private unnamed_addr constant [13 x i8] c", counter = \00"
@.str.9 = private unnamed_addr constant [28 x i8] c"Inner: returning list with \00"
@.str.6 = private unnamed_addr constant [5 x i8] c"] = \00"
@.str.5 = private unnamed_addr constant [11 x i8] c"    data2[\00"
@.str.17 = private unnamed_addr constant [2 x i8] c"C\00"
@.str.12 = private unnamed_addr constant [12 x i8] c"Outer: got \00"
@.str.2 = private unnamed_addr constant [7 x i8] c"  i = \00"
@.str.14 = private unnamed_addr constant [26 x i8] c"Setup: adding to dicts...\00"
@.str.11 = private unnamed_addr constant [27 x i8] c"Outer: calling inner(1)...\00"
@.str.8 = private unnamed_addr constant [21 x i8] c"      val != user_id\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"OK\00"
@.str.19 = private unnamed_addr constant [23 x i8] c"Main: calling outer...\00"
@.str.4 = private unnamed_addr constant [19 x i8] c"    i not in data2\00"
@.str.16 = private unnamed_addr constant [2 x i8] c"B\00"
@.str.15 = private unnamed_addr constant [2 x i8] c"A\00"
@.str.18 = private unnamed_addr constant [1 x i8] c"\00"
@.str.3 = private unnamed_addr constant [15 x i8] c"    i in data2\00"

; Module-level global variables
@roast_global_87 = global i64 0
@roast_global_88 = global i64 0
@roast_global_89 = global i64 0

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_98() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  br label %bb0
bb0:
  %v8 = getelementptr [27 x i8], [27 x i8]* @.str.11, i64 0, i64 0
  %v9 = call i8* @roast_str_new(i8* %v8, i64 26)
  %v10 = ptrtoint i8* %v9 to i64
  %v11 = call i64 @roast_print(i64 %v10)
  store i64 %v11, i64* %v0
  br label %bb1
bb1:
  %v12 = call i64 @roast_fn_90(i64 1)
  store i64 %v12, i64* %v2
  br label %bb2
bb2:
  %v13 = load i64, i64* %v2
  store i64 %v13, i64* %v1
  %v14 = inttoptr i64 %v13 to i8*
  call void @roast_incref(i8* %v14)
  %v15 = load i64, i64* %v1
  %v16 = call i64 @roast_len(i64 %v15)
  store i64 %v16, i64* %v5
  br label %bb3
bb3:
  %v17 = load i64, i64* %v5
  %v18 = call i64 @roast_str(i64 %v17)
  store i64 %v18, i64* %v4
  br label %bb4
bb4:
  %v19 = getelementptr [12 x i8], [12 x i8]* @.str.12, i64 0, i64 0
  %v20 = call i8* @roast_str_new(i8* %v19, i64 11)
  %v21 = ptrtoint i8* %v20 to i64
  %v22 = load i64, i64* %v4
  %v24 = inttoptr i64 %v21 to i8*
  %v25 = inttoptr i64 %v22 to i8*
  %v26 = call i8* @roast_str_concat(i8* %v24, i8* %v25)
  %v23 = ptrtoint i8* %v26 to i64
  store i64 %v23, i64* %v6
  %v27 = load i64, i64* %v6
  %v28 = getelementptr [7 x i8], [7 x i8]* @.str.10, i64 0, i64 0
  %v29 = call i8* @roast_str_new(i8* %v28, i64 6)
  %v30 = ptrtoint i8* %v29 to i64
  %v32 = inttoptr i64 %v27 to i8*
  %v33 = inttoptr i64 %v30 to i8*
  %v34 = call i8* @roast_str_concat(i8* %v32, i8* %v33)
  %v31 = ptrtoint i8* %v34 to i64
  store i64 %v31, i64* %v7
  %v35 = load i64, i64* %v7
  %v36 = call i64 @roast_print(i64 %v35)
  store i64 %v36, i64* %v3
  br label %bb5
bb5:
  %v37 = getelementptr [3 x i8], [3 x i8]* @.str.13, i64 0, i64 0
  %v38 = call i8* @roast_str_new(i8* %v37, i64 2)
  %v39 = ptrtoint i8* %v38 to i64
  ret i64 %v39
}

define i64 @roast_fn_163() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  br label %bb0
bb0:
  store i64 4, i64* %v0
  store i64 4, i64* @roast_global_87
  %v6 = call i8* @roast_dict_new()
  %v7 = ptrtoint i8* %v6 to i64
  store i64 %v7, i64* %v2
  %v8 = load i64, i64* %v2
  store i64 %v8, i64* %v1
  store i64 %v8, i64* @roast_global_88
  %v9 = inttoptr i64 %v8 to i8*
  call void @roast_incref(i8* %v9)
  %v10 = call i8* @roast_dict_new()
  %v11 = ptrtoint i8* %v10 to i64
  store i64 %v11, i64* %v4
  %v12 = load i64, i64* %v4
  store i64 %v12, i64* %v3
  store i64 %v12, i64* @roast_global_89
  %v13 = inttoptr i64 %v12 to i8*
  call void @roast_incref(i8* %v13)
  %v14 = call i64 @roast_fn_100()
  store i64 %v14, i64* %v5
  br label %bb1
bb1:
  ret i64 0
}

define i64 @roast_fn_90(i64 %arg0) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  store i64 %arg0, i64* %v0
  br label %bb0
bb0:
  %v39 = load i64, i64* %v0
  %v40 = call i64 @roast_str(i64 %v39)
  store i64 %v40, i64* %v2
  br label %bb1
bb1:
  %v41 = getelementptr [18 x i8], [18 x i8]* @.str.0, i64 0, i64 0
  %v42 = call i8* @roast_str_new(i8* %v41, i64 17)
  %v43 = ptrtoint i8* %v42 to i64
  %v44 = load i64, i64* %v2
  %v46 = inttoptr i64 %v43 to i8*
  %v47 = inttoptr i64 %v44 to i8*
  %v48 = call i8* @roast_str_concat(i8* %v46, i8* %v47)
  %v45 = ptrtoint i8* %v48 to i64
  store i64 %v45, i64* %v3
  %v49 = load i64, i64* %v3
  %v50 = getelementptr [13 x i8], [13 x i8]* @.str.1, i64 0, i64 0
  %v51 = call i8* @roast_str_new(i8* %v50, i64 12)
  %v52 = ptrtoint i8* %v51 to i64
  %v54 = inttoptr i64 %v49 to i8*
  %v55 = inttoptr i64 %v52 to i8*
  %v56 = call i8* @roast_str_concat(i8* %v54, i8* %v55)
  %v53 = ptrtoint i8* %v56 to i64
  store i64 %v53, i64* %v4
  %v57 = load i64, i64* @roast_global_87
  %v58 = call i64 @roast_str(i64 %v57)
  store i64 %v58, i64* %v5
  br label %bb2
bb2:
  %v59 = load i64, i64* %v4
  %v60 = load i64, i64* %v5
  %v62 = inttoptr i64 %v59 to i8*
  %v63 = inttoptr i64 %v60 to i8*
  %v64 = call i8* @roast_str_concat(i8* %v62, i8* %v63)
  %v61 = ptrtoint i8* %v64 to i64
  store i64 %v61, i64* %v6
  %v65 = load i64, i64* %v6
  %v66 = call i64 @roast_print(i64 %v65)
  store i64 %v66, i64* %v1
  br label %bb3
bb3:
  %v67 = call i8* @roast_list_new(i64 0)
  %v68 = ptrtoint i8* %v67 to i64
  store i64 %v68, i64* %v8
  %v69 = load i64, i64* %v8
  store i64 %v69, i64* %v7
  %v70 = inttoptr i64 %v69 to i8*
  call void @roast_incref(i8* %v70)
  %v71 = load i64, i64* @roast_global_87
  %v72 = call i64 @roast_range(i64 1, i64 %v71, i64 1)
  store i64 %v72, i64* %v9
  br label %bb4
bb4:
  %v73 = load i64, i64* %v9
  store i64 %v73, i64* %v10
  br label %bb5
bb5:
  %v74 = load i64, i64* %v10
  %v75 = inttoptr i64 %v74 to i8*
  %v76 = call i8* @roast_iter_new(i8* %v75)
  %v77 = ptrtoint i8* %v76 to i64
  store i64 %v77, i64* %v11
  br label %bb6
bb6:
  %v78 = load i64, i64* %v11
  %v79 = inttoptr i64 %v78 to i8*
  %v80 = alloca i1
  %v81 = call i64 @roast_iter_next(i8* %v79, i1* %v80)
  %v82 = load i1, i1* %v80
  store i64 %v81, i64* %v12
  br i1 %v82, label %bb8, label %bb7
bb7:
  %v83 = load i64, i64* %v12
  %v84 = call i64 @roast_str(i64 %v83)
  store i64 %v84, i64* %v14
  br label %bb9
bb8:
  %v85 = load i64, i64* %v7
  %v86 = call i64 @roast_len(i64 %v85)
  store i64 %v86, i64* %v36
  br label %bb25
bb9:
  %v87 = getelementptr [7 x i8], [7 x i8]* @.str.2, i64 0, i64 0
  %v88 = call i8* @roast_str_new(i8* %v87, i64 6)
  %v89 = ptrtoint i8* %v88 to i64
  %v90 = load i64, i64* %v14
  %v92 = inttoptr i64 %v89 to i8*
  %v93 = inttoptr i64 %v90 to i8*
  %v94 = call i8* @roast_str_concat(i8* %v92, i8* %v93)
  %v91 = ptrtoint i8* %v94 to i64
  store i64 %v91, i64* %v15
  %v95 = load i64, i64* %v15
  %v96 = call i64 @roast_print(i64 %v95)
  store i64 %v96, i64* %v13
  br label %bb10
bb10:
  %v97 = load i64, i64* %v12
  %v98 = load i64, i64* @roast_global_89
  %v100 = inttoptr i64 %v98 to i8*
  %v101 = call i1 @roast_dict_contains(i8* %v100, i64 %v97)
  %v99 = zext i1 %v101 to i64
  store i64 %v99, i64* %v16
  %v102 = load i64, i64* %v16
  store i64 %v102, i64* %v17
  %v103 = load i64, i64* %v17
  %v104 = icmp eq i64 %v103, 1
  br i1 %v104, label %bb11, label %bb12
bb11:
  %v105 = getelementptr [15 x i8], [15 x i8]* @.str.3, i64 0, i64 0
  %v106 = call i8* @roast_str_new(i8* %v105, i64 14)
  %v107 = ptrtoint i8* %v106 to i64
  %v108 = call i64 @roast_print(i64 %v107)
  store i64 %v108, i64* %v18
  br label %bb14
bb12:
  %v109 = getelementptr [19 x i8], [19 x i8]* @.str.4, i64 0, i64 0
  %v110 = call i8* @roast_str_new(i8* %v109, i64 18)
  %v111 = ptrtoint i8* %v110 to i64
  %v112 = call i64 @roast_print(i64 %v111)
  store i64 %v112, i64* %v33
  br label %bb24
bb13:
  br label %bb6
bb14:
  %v113 = load i64, i64* @roast_global_89
  store i64 %v113, i64* %v20
  %v114 = load i64, i64* %v12
  store i64 %v114, i64* %v21
  %v115 = load i64, i64* %v20
  %v116 = load i64, i64* %v21
  %v118 = inttoptr i64 %v115 to i8*
  %v117 = call i64 @roast_dict_get(i8* %v118, i64 %v116)
  store i64 %v117, i64* %v19
  %v119 = load i64, i64* %v12
  %v120 = call i64 @roast_str(i64 %v119)
  store i64 %v120, i64* %v23
  br label %bb15
bb15:
  %v121 = getelementptr [11 x i8], [11 x i8]* @.str.5, i64 0, i64 0
  %v122 = call i8* @roast_str_new(i8* %v121, i64 10)
  %v123 = ptrtoint i8* %v122 to i64
  %v124 = load i64, i64* %v23
  %v126 = inttoptr i64 %v123 to i8*
  %v127 = inttoptr i64 %v124 to i8*
  %v128 = call i8* @roast_str_concat(i8* %v126, i8* %v127)
  %v125 = ptrtoint i8* %v128 to i64
  store i64 %v125, i64* %v24
  %v129 = load i64, i64* %v24
  %v130 = getelementptr [5 x i8], [5 x i8]* @.str.6, i64 0, i64 0
  %v131 = call i8* @roast_str_new(i8* %v130, i64 4)
  %v132 = ptrtoint i8* %v131 to i64
  %v134 = inttoptr i64 %v129 to i8*
  %v135 = inttoptr i64 %v132 to i8*
  %v136 = call i8* @roast_str_concat(i8* %v134, i8* %v135)
  %v133 = ptrtoint i8* %v136 to i64
  store i64 %v133, i64* %v25
  %v137 = load i64, i64* %v19
  %v138 = call i64 @roast_str(i64 %v137)
  store i64 %v138, i64* %v26
  br label %bb16
bb16:
  %v139 = load i64, i64* %v25
  %v140 = load i64, i64* %v26
  %v142 = inttoptr i64 %v139 to i8*
  %v143 = inttoptr i64 %v140 to i8*
  %v144 = call i8* @roast_str_concat(i8* %v142, i8* %v143)
  %v141 = ptrtoint i8* %v144 to i64
  store i64 %v141, i64* %v27
  %v145 = load i64, i64* %v27
  %v146 = call i64 @roast_print(i64 %v145)
  store i64 %v146, i64* %v22
  br label %bb17
bb17:
  %v147 = load i64, i64* %v19
  %v148 = load i64, i64* %v0
  %v150 = icmp eq i64 %v147, %v148
  %v149 = zext i1 %v150 to i64
  store i64 %v149, i64* %v28
  %v151 = load i64, i64* %v28
  store i64 %v151, i64* %v29
  %v152 = load i64, i64* %v29
  %v153 = icmp eq i64 %v152, 1
  br i1 %v153, label %bb18, label %bb19
bb18:
  %v154 = getelementptr [32 x i8], [32 x i8]* @.str.7, i64 0, i64 0
  %v155 = call i8* @roast_str_new(i8* %v154, i64 31)
  %v156 = ptrtoint i8* %v155 to i64
  %v157 = call i64 @roast_print(i64 %v156)
  store i64 %v157, i64* %v30
  br label %bb21
bb19:
  %v158 = getelementptr [21 x i8], [21 x i8]* @.str.8, i64 0, i64 0
  %v159 = call i8* @roast_str_new(i8* %v158, i64 20)
  %v160 = ptrtoint i8* %v159 to i64
  %v161 = call i64 @roast_print(i64 %v160)
  store i64 %v161, i64* %v32
  br label %bb23
bb20:
  br label %bb13
bb21:
  %v162 = load i64, i64* %v7
  %v164 = inttoptr i64 %v162 to i8*
  %v165 = load i64, i64* %v12
  call void @roast_list_append(i8* %v164, i64 %v165)
  %v163 = add i64 0, 0
  store i64 %v163, i64* %v31
  br label %bb22
bb22:
  br label %bb20
bb23:
  br label %bb20
bb24:
  br label %bb13
bb25:
  %v166 = load i64, i64* %v36
  %v167 = call i64 @roast_str(i64 %v166)
  store i64 %v167, i64* %v35
  br label %bb26
bb26:
  %v168 = getelementptr [28 x i8], [28 x i8]* @.str.9, i64 0, i64 0
  %v169 = call i8* @roast_str_new(i8* %v168, i64 27)
  %v170 = ptrtoint i8* %v169 to i64
  %v171 = load i64, i64* %v35
  %v173 = inttoptr i64 %v170 to i8*
  %v174 = inttoptr i64 %v171 to i8*
  %v175 = call i8* @roast_str_concat(i8* %v173, i8* %v174)
  %v172 = ptrtoint i8* %v175 to i64
  store i64 %v172, i64* %v37
  %v176 = load i64, i64* %v37
  %v177 = getelementptr [7 x i8], [7 x i8]* @.str.10, i64 0, i64 0
  %v178 = call i8* @roast_str_new(i8* %v177, i64 6)
  %v179 = ptrtoint i8* %v178 to i64
  %v181 = inttoptr i64 %v176 to i8*
  %v182 = inttoptr i64 %v179 to i8*
  %v183 = call i8* @roast_str_concat(i8* %v181, i8* %v182)
  %v180 = ptrtoint i8* %v183 to i64
  store i64 %v180, i64* %v38
  %v184 = load i64, i64* %v38
  %v185 = call i64 @roast_print(i64 %v184)
  store i64 %v185, i64* %v34
  br label %bb27
bb27:
  %v186 = load i64, i64* %v7
  ret i64 %v186
}

define i64 @roast_fn_100() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  br label %bb0
bb0:
  %v16 = getelementptr [26 x i8], [26 x i8]* @.str.14, i64 0, i64 0
  %v17 = call i8* @roast_str_new(i8* %v16, i64 25)
  %v18 = ptrtoint i8* %v17 to i64
  %v19 = call i64 @roast_print(i64 %v18)
  store i64 %v19, i64* %v0
  br label %bb1
bb1:
  %v20 = load i64, i64* @roast_global_88
  store i64 %v20, i64* %v1
  store i64 %v20, i64* @roast_global_88
  store i64 1, i64* %v2
  %v21 = getelementptr [2 x i8], [2 x i8]* @.str.15, i64 0, i64 0
  %v22 = call i8* @roast_str_new(i8* %v21, i64 1)
  %v23 = ptrtoint i8* %v22 to i64
  %v24 = load i64, i64* %v1
  %v25 = load i64, i64* %v2
  %v26 = inttoptr i64 %v24 to i8*
  call void @roast_dict_set(i8* %v26, i64 %v25, i64 %v23)
  store i64 2, i64* %v3
  %v27 = getelementptr [2 x i8], [2 x i8]* @.str.16, i64 0, i64 0
  %v28 = call i8* @roast_str_new(i8* %v27, i64 1)
  %v29 = ptrtoint i8* %v28 to i64
  %v30 = load i64, i64* %v1
  %v31 = load i64, i64* %v3
  %v32 = inttoptr i64 %v30 to i8*
  call void @roast_dict_set(i8* %v32, i64 %v31, i64 %v29)
  store i64 3, i64* %v4
  %v33 = getelementptr [2 x i8], [2 x i8]* @.str.17, i64 0, i64 0
  %v34 = call i8* @roast_str_new(i8* %v33, i64 1)
  %v35 = ptrtoint i8* %v34 to i64
  %v36 = load i64, i64* %v1
  %v37 = load i64, i64* %v4
  %v38 = inttoptr i64 %v36 to i8*
  call void @roast_dict_set(i8* %v38, i64 %v37, i64 %v35)
  %v39 = load i64, i64* @roast_global_89
  store i64 %v39, i64* %v5
  store i64 %v39, i64* @roast_global_89
  %v40 = load i64, i64* %v2
  store i64 %v40, i64* %v6
  %v41 = load i64, i64* %v5
  %v42 = load i64, i64* %v6
  %v43 = inttoptr i64 %v41 to i8*
  call void @roast_dict_set(i8* %v43, i64 %v42, i64 1)
  %v44 = load i64, i64* %v3
  store i64 %v44, i64* %v7
  %v45 = load i64, i64* %v5
  %v46 = load i64, i64* %v7
  %v47 = inttoptr i64 %v45 to i8*
  call void @roast_dict_set(i8* %v47, i64 %v46, i64 1)
  %v48 = load i64, i64* %v4
  store i64 %v48, i64* %v8
  %v49 = load i64, i64* %v5
  %v50 = load i64, i64* %v8
  %v51 = inttoptr i64 %v49 to i8*
  call void @roast_dict_set(i8* %v51, i64 %v50, i64 2)
  %v52 = getelementptr [1 x i8], [1 x i8]* @.str.18, i64 0, i64 0
  %v53 = call i8* @roast_str_new(i8* %v52, i64 0)
  %v54 = ptrtoint i8* %v53 to i64
  %v55 = call i64 @roast_print(i64 %v54)
  store i64 %v55, i64* %v9
  br label %bb2
bb2:
  %v56 = getelementptr [23 x i8], [23 x i8]* @.str.19, i64 0, i64 0
  %v57 = call i8* @roast_str_new(i8* %v56, i64 22)
  %v58 = ptrtoint i8* %v57 to i64
  %v59 = call i64 @roast_print(i64 %v58)
  store i64 %v59, i64* %v10
  br label %bb3
bb3:
  %v60 = call i64 @roast_fn_98()
  store i64 %v60, i64* %v12
  br label %bb4
bb4:
  %v61 = load i64, i64* %v12
  store i64 %v61, i64* %v11
  %v62 = inttoptr i64 %v61 to i8*
  call void @roast_incref(i8* %v62)
  %v63 = load i64, i64* %v11
  %v64 = call i64 @roast_str(i64 %v63)
  store i64 %v64, i64* %v14
  br label %bb5
bb5:
  %v65 = getelementptr [16 x i8], [16 x i8]* @.str.20, i64 0, i64 0
  %v66 = call i8* @roast_str_new(i8* %v65, i64 15)
  %v67 = ptrtoint i8* %v66 to i64
  %v68 = load i64, i64* %v14
  %v70 = inttoptr i64 %v67 to i8*
  %v71 = inttoptr i64 %v68 to i8*
  %v72 = call i8* @roast_str_concat(i8* %v70, i8* %v71)
  %v69 = ptrtoint i8* %v72 to i64
  store i64 %v69, i64* %v15
  %v73 = load i64, i64* %v15
  %v74 = call i64 @roast_print(i64 %v73)
  store i64 %v74, i64* %v13
  br label %bb6
bb6:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_163()
    ret i32 0
}

