; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.15 = private unnamed_addr constant [9 x i8] c"  Item: \00"
@.str.0 = private unnamed_addr constant [12 x i8] c"Added item \00"
@.str.8 = private unnamed_addr constant [21 x i8] c"Returning list with \00"
@.str.9 = private unnamed_addr constant [7 x i8] c" items\00"
@.str.1 = private unnamed_addr constant [9 x i8] c" (owner=\00"
@.str.16 = private unnamed_addr constant [9 x i8] c"4. Done!\00"
@.str.13 = private unnamed_addr constant [5 x i8] c"Got \00"
@.str.3 = private unnamed_addr constant [24 x i8] c"Getting items for user \00"
@.str.11 = private unnamed_addr constant [1 x i8] c"\00"
@.str.7 = private unnamed_addr constant [21 x i8] c"    Adding to result\00"
@.str.14 = private unnamed_addr constant [35 x i8] c"3. Iterating over returned list...\00"
@.str.5 = private unnamed_addr constant [12 x i8] c"  Checking \00"
@.str.2 = private unnamed_addr constant [2 x i8] c")\00"
@.str.6 = private unnamed_addr constant [13 x i8] c"    Owner = \00"
@.str.12 = private unnamed_addr constant [31 x i8] c"2. Getting items for user 1...\00"
@.str.4 = private unnamed_addr constant [4 x i8] c"...\00"
@.str.10 = private unnamed_addr constant [19 x i8] c"1. Adding items...\00"

; Module-level global variables
@roast_global_87 = global i64 0
@roast_global_88 = global i64 0

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare void @roast_subscript_set(i64, i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind
declare i1 @roast_list_eq(i8*, i8*) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind
declare i1 @roast_dict_eq(i8*, i8*) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind
declare i64 @roast_floordiv(i64, i64) nounwind
declare i64 @roast_mod(i64, i64) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_print_value(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare void @roast_class_set_mro(i8*, i8*) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind
declare i64 @roast_open(i64, i64) nounwind
declare i64 @roast_file_read(i64) nounwind
declare i64 @roast_file_write(i64, i64) nounwind
declare void @roast_file_close(i64) nounwind
declare i64 @roast_file_readline(i64) nounwind

; TCP Server
declare i64 @roast_tcp_server_create(i8*, i64) nounwind
declare i64 @roast_tcp_server_accept(i64) nounwind
declare void @roast_tcp_server_close(i64) nounwind
declare i8* @roast_tcp_client_read(i64, i64) nounwind
declare i64 @roast_tcp_client_write(i64, i8*) nounwind
declare void @roast_tcp_client_close(i64) nounwind

; Python FFI
declare i64 @roast_py_import(i8*) nounwind
declare i64 @roast_py_getattr(i64, i8*) nounwind
declare i64 @roast_py_call(i64, i8*) nounwind
declare i8* @roast_py_to_str(i64) nounwind
declare i64 @roast_py_to_int(i64) nounwind

define i64 @roast_fn_163() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  br label %bb0
bb0:
  %v4 = call i8* @roast_dict_new()
  %v5 = ptrtoint i8* %v4 to i64
  store i64 %v5, i64* %v1
  %v6 = load i64, i64* %v1
  store i64 %v6, i64* %v0
  store i64 %v6, i64* @roast_global_87
  %v7 = inttoptr i64 %v6 to i8*
  call void @roast_incref(i8* %v7)
  store i64 1, i64* %v2
  store i64 1, i64* @roast_global_88
  %v8 = call i64 @roast_fn_99()
  store i64 %v8, i64* %v3
  br label %bb1
bb1:
  ret i64 0
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_fn_163()
    ret i32 0
}

define i64 @roast_fn_89(i64 %arg0) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  store i64 %arg0, i64* %v0
  br label %bb0
bb0:
  %v13 = load i64, i64* @roast_global_88
  store i64 %v13, i64* %v1
  %v14 = load i64, i64* @roast_global_88
  %v15 = add i64 %v14, 1
  store i64 %v15, i64* %v2
  %v16 = load i64, i64* @roast_global_88
  store i64 %v16, i64* %v3
  store i64 %v16, i64* @roast_global_88
  %v17 = load i64, i64* %v2
  store i64 %v17, i64* %v3
  store i64 %v17, i64* @roast_global_88
  %v18 = load i64, i64* @roast_global_87
  store i64 %v18, i64* %v4
  store i64 %v18, i64* @roast_global_87
  %v19 = load i64, i64* %v1
  store i64 %v19, i64* %v5
  %v20 = load i64, i64* %v0
  %v21 = load i64, i64* %v4
  %v22 = load i64, i64* %v5
  %v23 = inttoptr i64 %v21 to i8*
  call void @roast_dict_set(i8* %v23, i64 %v22, i64 %v20)
  %v24 = load i64, i64* %v1
  %v25 = call i64 @roast_str(i64 %v24)
  store i64 %v25, i64* %v7
  br label %bb1
bb1:
  %v26 = getelementptr [12 x i8], [12 x i8]* @.str.0, i64 0, i64 0
  %v27 = call i8* @roast_str_new(i8* %v26, i64 11)
  %v28 = ptrtoint i8* %v27 to i64
  %v29 = load i64, i64* %v7
  %v31 = inttoptr i64 %v28 to i8*
  %v32 = inttoptr i64 %v29 to i8*
  %v33 = call i8* @roast_str_concat(i8* %v31, i8* %v32)
  %v30 = ptrtoint i8* %v33 to i64
  store i64 %v30, i64* %v8
  %v34 = load i64, i64* %v8
  %v35 = getelementptr [9 x i8], [9 x i8]* @.str.1, i64 0, i64 0
  %v36 = call i8* @roast_str_new(i8* %v35, i64 8)
  %v37 = ptrtoint i8* %v36 to i64
  %v39 = inttoptr i64 %v34 to i8*
  %v40 = inttoptr i64 %v37 to i8*
  %v41 = call i8* @roast_str_concat(i8* %v39, i8* %v40)
  %v38 = ptrtoint i8* %v41 to i64
  store i64 %v38, i64* %v9
  %v42 = load i64, i64* %v0
  %v43 = call i64 @roast_str(i64 %v42)
  store i64 %v43, i64* %v10
  br label %bb2
bb2:
  %v44 = load i64, i64* %v9
  %v45 = load i64, i64* %v10
  %v47 = inttoptr i64 %v44 to i8*
  %v48 = inttoptr i64 %v45 to i8*
  %v49 = call i8* @roast_str_concat(i8* %v47, i8* %v48)
  %v46 = ptrtoint i8* %v49 to i64
  store i64 %v46, i64* %v11
  %v50 = load i64, i64* %v11
  %v51 = getelementptr [2 x i8], [2 x i8]* @.str.2, i64 0, i64 0
  %v52 = call i8* @roast_str_new(i8* %v51, i64 1)
  %v53 = ptrtoint i8* %v52 to i64
  %v55 = inttoptr i64 %v50 to i8*
  %v56 = inttoptr i64 %v53 to i8*
  %v57 = call i8* @roast_str_concat(i8* %v55, i8* %v56)
  %v54 = ptrtoint i8* %v57 to i64
  store i64 %v54, i64* %v12
  %v58 = load i64, i64* %v12
  %v59 = call i64 @roast_print(i64 %v58)
  store i64 %v59, i64* %v6
  br label %bb3
bb3:
  %v60 = load i64, i64* %v1
  ret i64 %v60
}

define i64 @roast_fn_93(i64 %arg0) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  store i64 %arg0, i64* %v0
  br label %bb0
bb0:
  %v31 = load i64, i64* %v0
  %v32 = call i64 @roast_str(i64 %v31)
  store i64 %v32, i64* %v2
  br label %bb1
bb1:
  %v33 = getelementptr [24 x i8], [24 x i8]* @.str.3, i64 0, i64 0
  %v34 = call i8* @roast_str_new(i8* %v33, i64 23)
  %v35 = ptrtoint i8* %v34 to i64
  %v36 = load i64, i64* %v2
  %v38 = inttoptr i64 %v35 to i8*
  %v39 = inttoptr i64 %v36 to i8*
  %v40 = call i8* @roast_str_concat(i8* %v38, i8* %v39)
  %v37 = ptrtoint i8* %v40 to i64
  store i64 %v37, i64* %v3
  %v41 = load i64, i64* %v3
  %v42 = getelementptr [4 x i8], [4 x i8]* @.str.4, i64 0, i64 0
  %v43 = call i8* @roast_str_new(i8* %v42, i64 3)
  %v44 = ptrtoint i8* %v43 to i64
  %v46 = inttoptr i64 %v41 to i8*
  %v47 = inttoptr i64 %v44 to i8*
  %v48 = call i8* @roast_str_concat(i8* %v46, i8* %v47)
  %v45 = ptrtoint i8* %v48 to i64
  store i64 %v45, i64* %v4
  %v49 = load i64, i64* %v4
  %v50 = call i64 @roast_print(i64 %v49)
  store i64 %v50, i64* %v1
  br label %bb2
bb2:
  %v51 = call i8* @roast_list_new(i64 0)
  %v52 = ptrtoint i8* %v51 to i64
  store i64 %v52, i64* %v6
  %v53 = load i64, i64* %v6
  store i64 %v53, i64* %v5
  %v54 = inttoptr i64 %v53 to i8*
  call void @roast_incref(i8* %v54)
  %v55 = load i64, i64* @roast_global_88
  %v56 = call i64 @roast_range(i64 1, i64 %v55, i64 1)
  store i64 %v56, i64* %v7
  br label %bb3
bb3:
  %v57 = load i64, i64* %v7
  store i64 %v57, i64* %v8
  br label %bb4
bb4:
  %v58 = load i64, i64* %v8
  %v59 = inttoptr i64 %v58 to i8*
  %v60 = call i8* @roast_iter_new(i8* %v59)
  %v61 = ptrtoint i8* %v60 to i64
  store i64 %v61, i64* %v9
  br label %bb5
bb5:
  %v62 = load i64, i64* %v9
  %v63 = inttoptr i64 %v62 to i8*
  %v64 = alloca i1
  %v65 = call i64 @roast_iter_next(i8* %v63, i1* %v64)
  %v66 = load i1, i1* %v64
  store i64 %v65, i64* %v10
  br i1 %v66, label %bb7, label %bb6
bb6:
  %v67 = load i64, i64* %v10
  %v68 = call i64 @roast_str(i64 %v67)
  store i64 %v68, i64* %v12
  br label %bb8
bb7:
  %v69 = load i64, i64* %v5
  %v70 = call i64 @roast_len(i64 %v69)
  store i64 %v70, i64* %v28
  br label %bb18
bb8:
  %v71 = getelementptr [12 x i8], [12 x i8]* @.str.5, i64 0, i64 0
  %v72 = call i8* @roast_str_new(i8* %v71, i64 11)
  %v73 = ptrtoint i8* %v72 to i64
  %v74 = load i64, i64* %v12
  %v76 = inttoptr i64 %v73 to i8*
  %v77 = inttoptr i64 %v74 to i8*
  %v78 = call i8* @roast_str_concat(i8* %v76, i8* %v77)
  %v75 = ptrtoint i8* %v78 to i64
  store i64 %v75, i64* %v13
  %v79 = load i64, i64* %v13
  %v80 = call i64 @roast_print(i64 %v79)
  store i64 %v80, i64* %v11
  br label %bb9
bb9:
  %v81 = load i64, i64* %v10
  %v82 = load i64, i64* @roast_global_87
  %v84 = inttoptr i64 %v82 to i8*
  %v85 = call i1 @roast_dict_contains(i8* %v84, i64 %v81)
  %v83 = zext i1 %v85 to i64
  store i64 %v83, i64* %v14
  %v86 = load i64, i64* %v14
  store i64 %v86, i64* %v15
  %v87 = load i64, i64* %v15
  %v88 = icmp eq i64 %v87, 1
  br i1 %v88, label %bb10, label %bb11
bb10:
  %v89 = load i64, i64* @roast_global_87
  store i64 %v89, i64* %v17
  %v90 = load i64, i64* %v10
  store i64 %v90, i64* %v18
  %v91 = load i64, i64* %v17
  %v92 = load i64, i64* %v18
  %v94 = inttoptr i64 %v91 to i8*
  %v93 = call i64 @roast_dict_get(i8* %v94, i64 %v92)
  store i64 %v93, i64* %v16
  %v95 = load i64, i64* %v16
  %v96 = call i64 @roast_str(i64 %v95)
  store i64 %v96, i64* %v20
  br label %bb12
bb11:
  br label %bb5
bb12:
  %v97 = getelementptr [13 x i8], [13 x i8]* @.str.6, i64 0, i64 0
  %v98 = call i8* @roast_str_new(i8* %v97, i64 12)
  %v99 = ptrtoint i8* %v98 to i64
  %v100 = load i64, i64* %v20
  %v102 = inttoptr i64 %v99 to i8*
  %v103 = inttoptr i64 %v100 to i8*
  %v104 = call i8* @roast_str_concat(i8* %v102, i8* %v103)
  %v101 = ptrtoint i8* %v104 to i64
  store i64 %v101, i64* %v21
  %v105 = load i64, i64* %v21
  %v106 = call i64 @roast_print(i64 %v105)
  store i64 %v106, i64* %v19
  br label %bb13
bb13:
  %v107 = load i64, i64* %v16
  %v108 = load i64, i64* %v0
  %v110 = icmp eq i64 %v107, %v108
  %v109 = zext i1 %v110 to i64
  store i64 %v109, i64* %v22
  %v111 = load i64, i64* %v22
  store i64 %v111, i64* %v23
  %v112 = load i64, i64* %v23
  %v113 = icmp eq i64 %v112, 1
  br i1 %v113, label %bb14, label %bb15
bb14:
  %v114 = getelementptr [21 x i8], [21 x i8]* @.str.7, i64 0, i64 0
  %v115 = call i8* @roast_str_new(i8* %v114, i64 20)
  %v116 = ptrtoint i8* %v115 to i64
  %v117 = call i64 @roast_print(i64 %v116)
  store i64 %v117, i64* %v24
  br label %bb16
bb15:
  br label %bb11
bb16:
  %v118 = load i64, i64* %v5
  %v120 = inttoptr i64 %v118 to i8*
  %v121 = load i64, i64* %v10
  call void @roast_list_append(i8* %v120, i64 %v121)
  %v119 = add i64 0, 0
  store i64 %v119, i64* %v25
  br label %bb17
bb17:
  br label %bb15
bb18:
  %v122 = load i64, i64* %v28
  %v123 = call i64 @roast_str(i64 %v122)
  store i64 %v123, i64* %v27
  br label %bb19
bb19:
  %v124 = getelementptr [21 x i8], [21 x i8]* @.str.8, i64 0, i64 0
  %v125 = call i8* @roast_str_new(i8* %v124, i64 20)
  %v126 = ptrtoint i8* %v125 to i64
  %v127 = load i64, i64* %v27
  %v129 = inttoptr i64 %v126 to i8*
  %v130 = inttoptr i64 %v127 to i8*
  %v131 = call i8* @roast_str_concat(i8* %v129, i8* %v130)
  %v128 = ptrtoint i8* %v131 to i64
  store i64 %v128, i64* %v29
  %v132 = load i64, i64* %v29
  %v133 = getelementptr [7 x i8], [7 x i8]* @.str.9, i64 0, i64 0
  %v134 = call i8* @roast_str_new(i8* %v133, i64 6)
  %v135 = ptrtoint i8* %v134 to i64
  %v137 = inttoptr i64 %v132 to i8*
  %v138 = inttoptr i64 %v135 to i8*
  %v139 = call i8* @roast_str_concat(i8* %v137, i8* %v138)
  %v136 = ptrtoint i8* %v139 to i64
  store i64 %v136, i64* %v30
  %v140 = load i64, i64* %v30
  %v141 = call i64 @roast_print(i64 %v140)
  store i64 %v141, i64* %v26
  br label %bb20
bb20:
  %v142 = load i64, i64* %v5
  ret i64 %v142
}

define i64 @roast_fn_99() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  br label %bb0
bb0:
  %v23 = getelementptr [19 x i8], [19 x i8]* @.str.10, i64 0, i64 0
  %v24 = call i8* @roast_str_new(i8* %v23, i64 18)
  %v25 = ptrtoint i8* %v24 to i64
  %v26 = call i64 @roast_print(i64 %v25)
  store i64 %v26, i64* %v0
  br label %bb1
bb1:
  %v27 = call i64 @roast_fn_89(i64 1)
  store i64 %v27, i64* %v1
  br label %bb2
bb2:
  %v28 = call i64 @roast_fn_89(i64 1)
  store i64 %v28, i64* %v2
  br label %bb3
bb3:
  %v29 = call i64 @roast_fn_89(i64 2)
  store i64 %v29, i64* %v3
  br label %bb4
bb4:
  %v30 = getelementptr [1 x i8], [1 x i8]* @.str.11, i64 0, i64 0
  %v31 = call i8* @roast_str_new(i8* %v30, i64 0)
  %v32 = ptrtoint i8* %v31 to i64
  %v33 = call i64 @roast_print(i64 %v32)
  store i64 %v33, i64* %v4
  br label %bb5
bb5:
  %v34 = getelementptr [31 x i8], [31 x i8]* @.str.12, i64 0, i64 0
  %v35 = call i8* @roast_str_new(i8* %v34, i64 30)
  %v36 = ptrtoint i8* %v35 to i64
  %v37 = call i64 @roast_print(i64 %v36)
  store i64 %v37, i64* %v5
  br label %bb6
bb6:
  %v38 = call i64 @roast_fn_93(i64 1)
  store i64 %v38, i64* %v7
  br label %bb7
bb7:
  %v39 = load i64, i64* %v7
  store i64 %v39, i64* %v6
  %v40 = inttoptr i64 %v39 to i8*
  call void @roast_incref(i8* %v40)
  %v41 = load i64, i64* %v6
  %v42 = call i64 @roast_len(i64 %v41)
  store i64 %v42, i64* %v10
  br label %bb8
bb8:
  %v43 = load i64, i64* %v10
  %v44 = call i64 @roast_str(i64 %v43)
  store i64 %v44, i64* %v9
  br label %bb9
bb9:
  %v45 = getelementptr [5 x i8], [5 x i8]* @.str.13, i64 0, i64 0
  %v46 = call i8* @roast_str_new(i8* %v45, i64 4)
  %v47 = ptrtoint i8* %v46 to i64
  %v48 = load i64, i64* %v9
  %v50 = inttoptr i64 %v47 to i8*
  %v51 = inttoptr i64 %v48 to i8*
  %v52 = call i8* @roast_str_concat(i8* %v50, i8* %v51)
  %v49 = ptrtoint i8* %v52 to i64
  store i64 %v49, i64* %v11
  %v53 = load i64, i64* %v11
  %v54 = getelementptr [7 x i8], [7 x i8]* @.str.9, i64 0, i64 0
  %v55 = call i8* @roast_str_new(i8* %v54, i64 6)
  %v56 = ptrtoint i8* %v55 to i64
  %v58 = inttoptr i64 %v53 to i8*
  %v59 = inttoptr i64 %v56 to i8*
  %v60 = call i8* @roast_str_concat(i8* %v58, i8* %v59)
  %v57 = ptrtoint i8* %v60 to i64
  store i64 %v57, i64* %v12
  %v61 = load i64, i64* %v12
  %v62 = call i64 @roast_print(i64 %v61)
  store i64 %v62, i64* %v8
  br label %bb10
bb10:
  %v63 = getelementptr [1 x i8], [1 x i8]* @.str.11, i64 0, i64 0
  %v64 = call i8* @roast_str_new(i8* %v63, i64 0)
  %v65 = ptrtoint i8* %v64 to i64
  %v66 = call i64 @roast_print(i64 %v65)
  store i64 %v66, i64* %v13
  br label %bb11
bb11:
  %v67 = getelementptr [35 x i8], [35 x i8]* @.str.14, i64 0, i64 0
  %v68 = call i8* @roast_str_new(i8* %v67, i64 34)
  %v69 = ptrtoint i8* %v68 to i64
  %v70 = call i64 @roast_print(i64 %v69)
  store i64 %v70, i64* %v14
  br label %bb12
bb12:
  %v71 = load i64, i64* %v6
  store i64 %v71, i64* %v15
  br label %bb13
bb13:
  %v72 = load i64, i64* %v6
  %v73 = inttoptr i64 %v72 to i8*
  %v74 = call i8* @roast_iter_new(i8* %v73)
  %v75 = ptrtoint i8* %v74 to i64
  store i64 %v75, i64* %v16
  br label %bb14
bb14:
  %v76 = load i64, i64* %v16
  %v77 = inttoptr i64 %v76 to i8*
  %v78 = alloca i1
  %v79 = call i64 @roast_iter_next(i8* %v77, i1* %v78)
  %v80 = load i1, i1* %v78
  store i64 %v79, i64* %v17
  br i1 %v80, label %bb16, label %bb15
bb15:
  %v81 = load i64, i64* %v17
  %v82 = call i64 @roast_str(i64 %v81)
  store i64 %v82, i64* %v19
  br label %bb17
bb16:
  %v83 = getelementptr [1 x i8], [1 x i8]* @.str.11, i64 0, i64 0
  %v84 = call i8* @roast_str_new(i8* %v83, i64 0)
  %v85 = ptrtoint i8* %v84 to i64
  %v86 = call i64 @roast_print(i64 %v85)
  store i64 %v86, i64* %v21
  br label %bb19
bb17:
  %v87 = getelementptr [9 x i8], [9 x i8]* @.str.15, i64 0, i64 0
  %v88 = call i8* @roast_str_new(i8* %v87, i64 8)
  %v89 = ptrtoint i8* %v88 to i64
  %v90 = load i64, i64* %v19
  %v92 = inttoptr i64 %v89 to i8*
  %v93 = inttoptr i64 %v90 to i8*
  %v94 = call i8* @roast_str_concat(i8* %v92, i8* %v93)
  %v91 = ptrtoint i8* %v94 to i64
  store i64 %v91, i64* %v20
  %v95 = load i64, i64* %v20
  %v96 = call i64 @roast_print(i64 %v95)
  store i64 %v96, i64* %v18
  br label %bb18
bb18:
  br label %bb14
bb19:
  %v97 = getelementptr [9 x i8], [9 x i8]* @.str.16, i64 0, i64 0
  %v98 = call i8* @roast_str_new(i8* %v97, i64 8)
  %v99 = ptrtoint i8* %v98 to i64
  %v100 = call i64 @roast_print(i64 %v99)
  store i64 %v100, i64* %v22
  br label %bb20
bb20:
  ret i64 0
}

