; Roast LLVM IR - Generated by roastc
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.str.23 = private unnamed_addr constant [7 x i8] c"config\00"
@.str.29 = private unnamed_addr constant [11 x i8] c"Scraping: \00"
@.str.5 = private unnamed_addr constant [6 x i8] c"title\00"
@.str.33 = private unnamed_addr constant [26 x i8] c"Starting batch scrape of \00"
@.str.6 = private unnamed_addr constant [11 x i8] c"link_count\00"
@.str.0 = private unnamed_addr constant [15 x i8] c"max_concurrent\00"
@.str.3 = private unnamed_addr constant [11 x i8] c"output_dir\00"
@.str.20 = private unnamed_addr constant [2 x i8] c"[\00"
@.str.11 = private unnamed_addr constant [11 x i8] c"github.com\00"
@.str.9 = private unnamed_addr constant [12 x i8] c"example.com\00"
@.str.39 = private unnamed_addr constant [41 x i8] c"========================================\00"
@.str.4 = private unnamed_addr constant [4 x i8] c"url\00"
@.str.12 = private unnamed_addr constant [37 x i8] c"{\22login\22: \22roast-lang\22, \22repos\22: 42}\00"
@.str.34 = private unnamed_addr constant [6 x i8] c" URLs\00"
@.str.7 = private unnamed_addr constant [8 x i8] c"success\00"
@.str.42 = private unnamed_addr constant [17 x i8] c"Successful:     \00"
@.str.14 = private unnamed_addr constant [15 x i8] c"</body></html>\00"
@.str.45 = private unnamed_addr constant [2 x i8] c"=\00"
@.str.18 = private unnamed_addr constant [6 x i8] c"href=\00"
@.str.21 = private unnamed_addr constant [9 x i8] c"] INFO: \00"
@.str.46 = private unnamed_addr constant [44 x i8] c"Roast Web Scraper - Native Compilation Demo\00"
@.str.19 = private unnamed_addr constant [5 x i8] c"name\00"
@.str.22 = private unnamed_addr constant [10 x i8] c"] ERROR: \00"
@.str.51 = private unnamed_addr constant [32 x i8] c"https://blog.example.com/post/1\00"
@.str.54 = private unnamed_addr constant [9 x i8] c" URLs...\00"
@.str.44 = private unnamed_addr constant [17 x i8] c"Total Links:    \00"
@.str.43 = private unnamed_addr constant [17 x i8] c"Failed:         \00"
@.str.25 = private unnamed_addr constant [7 x i8] c"parser\00"
@.str.24 = private unnamed_addr constant [7 x i8] c"client\00"
@.str.36 = private unnamed_addr constant [15 x i8] c" pages scraped\00"
@.str.40 = private unnamed_addr constant [26 x i8] c"       WEB SCRAPER REPORT\00"
@.str.49 = private unnamed_addr constant [35 x i8] c"https://api.github.com/users/roast\00"
@.str.1 = private unnamed_addr constant [8 x i8] c"timeout\00"
@.str.15 = private unnamed_addr constant [8 x i8] c"<title>\00"
@.str.52 = private unnamed_addr constant [25 x i8] c"https://news.example.com\00"
@.str.53 = private unnamed_addr constant [10 x i8] c"Scraping \00"
@.str.32 = private unnamed_addr constant [8 x i8] c" links)\00"
@.str.55 = private unnamed_addr constant [33 x i8] c"Scraping completed successfully!\00"
@.str.8 = private unnamed_addr constant [12 x i8] c"[HTTP] GET \00"
@.str.17 = private unnamed_addr constant [9 x i8] c"Untitled\00"
@.str.35 = private unnamed_addr constant [12 x i8] c"Completed: \00"
@.str.41 = private unnamed_addr constant [17 x i8] c"Total URLs:     \00"
@.str.30 = private unnamed_addr constant [10 x i8] c"Scraped: \00"
@.str.48 = private unnamed_addr constant [20 x i8] c"https://example.com\00"
@.str.28 = private unnamed_addr constant [14 x i8] c"results_count\00"
@.str.26 = private unnamed_addr constant [8 x i8] c"Scraper\00"
@.str.50 = private unnamed_addr constant [28 x i8] c"https://docs.roast-lang.org\00"
@.str.2 = private unnamed_addr constant [9 x i8] c"./output\00"
@.str.16 = private unnamed_addr constant [9 x i8] c"</title>\00"
@.str.10 = private unnamed_addr constant [72 x i8] c"<html><title>Example</title><body><h1>Example Domain</h1></body></html>\00"
@.str.27 = private unnamed_addr constant [7 x i8] c"logger\00"
@.str.31 = private unnamed_addr constant [3 x i8] c" (\00"
@.str.38 = private unnamed_addr constant [1 x i8] c"\00"
@.str.37 = private unnamed_addr constant [10 x i8] c"Processor\00"
@.str.47 = private unnamed_addr constant [39 x i8] c"   Features: Classes, OOP, Type Safety\00"
@.str.13 = private unnamed_addr constant [26 x i8] c"<html><body>Content from \00"

@.classname.Logger = private unnamed_addr constant [7 x i8] c"Logger\00"
@.classname.ResultProcessor = private unnamed_addr constant [16 x i8] c"ResultProcessor\00"
@.classname.Scraper = private unnamed_addr constant [8 x i8] c"Scraper\00"
@.classname.PageResult = private unnamed_addr constant [11 x i8] c"PageResult\00"
@.classname.HttpClient = private unnamed_addr constant [11 x i8] c"HttpClient\00"
@.classname.HtmlParser = private unnamed_addr constant [11 x i8] c"HtmlParser\00"
@.classname.ScraperConfig = private unnamed_addr constant [14 x i8] c"ScraperConfig\00"

@.class.Logger = global i8* null
@.class.ResultProcessor = global i8* null
@.class.Scraper = global i8* null
@.class.PageResult = global i8* null
@.class.HttpClient = global i8* null
@.class.HtmlParser = global i8* null
@.class.ScraperConfig = global i8* null

@.methodname.Logger.111 = private unnamed_addr constant [6 x i8] c"error\00"
@.methodname.Logger.109 = private unnamed_addr constant [5 x i8] c"info\00"
@.methodname.Logger.60 = private unnamed_addr constant [9 x i8] c"__init__\00"
@.methodname.ResultProcessor.126 = private unnamed_addr constant [16 x i8] c"generate_report\00"
@.methodname.ResultProcessor.60 = private unnamed_addr constant [9 x i8] c"__init__\00"
@.methodname.Scraper.60 = private unnamed_addr constant [9 x i8] c"__init__\00"
@.methodname.Scraper.120 = private unnamed_addr constant [11 x i8] c"scrape_all\00"
@.methodname.Scraper.118 = private unnamed_addr constant [12 x i8] c"scrape_page\00"
@.methodname.PageResult.60 = private unnamed_addr constant [9 x i8] c"__init__\00"
@.methodname.HttpClient.98 = private unnamed_addr constant [4 x i8] c"get\00"
@.methodname.HttpClient.60 = private unnamed_addr constant [9 x i8] c"__init__\00"
@.methodname.HtmlParser.60 = private unnamed_addr constant [9 x i8] c"__init__\00"
@.methodname.HtmlParser.101 = private unnamed_addr constant [14 x i8] c"extract_title\00"
@.methodname.HtmlParser.106 = private unnamed_addr constant [12 x i8] c"count_links\00"
@.methodname.ScraperConfig.60 = private unnamed_addr constant [9 x i8] c"__init__\00"

; C standard library
declare i32 @printf(i8*, ...) nounwind
declare i32 @puts(i8*) nounwind
declare i8* @malloc(i64) nounwind
declare i8* @realloc(i8*, i64) nounwind
declare void @free(i8*) nounwind
declare i8* @memcpy(i8*, i8*, i64) nounwind
declare i32 @memcmp(i8*, i8*, i64) nounwind
declare i64 @strlen(i8*) nounwind
declare double @pow(double, double) nounwind
declare double @sqrt(double) nounwind
declare double @floor(double) nounwind
declare double @ceil(double) nounwind
declare double @sin(double) nounwind
declare double @cos(double) nounwind

; Roast runtime library
declare void @roast_print_int(i64) nounwind
declare void @roast_print_float(double) nounwind
declare void @roast_print_str(i8*) nounwind
declare void @roast_print_roast_str(i8*) nounwind
declare void @roast_print_bool(i1) nounwind
declare void @roast_print_newline() nounwind
declare void @roast_print_space() nounwind

; Memory management
declare i8* @roast_alloc(i64) nounwind
declare void @roast_free(i8*) nounwind
declare void @roast_incref(i8*) nounwind
declare void @roast_decref(i8*) nounwind

; String operations
declare i8* @roast_str_new(i8*, i64) nounwind
declare i8* @roast_str_concat(i8*, i8*) nounwind
declare i64 @roast_str_len(i8*) nounwind
declare i1 @roast_str_eq(i8*, i8*) nounwind
declare i8* @roast_int_to_str(i64) nounwind
declare i8* @roast_float_to_str(double) nounwind
declare i64 @roast_str_to_int(i8*) nounwind
declare double @roast_str_to_float(i8*) nounwind
declare i8* @roast_str_slice(i8*, i64, i64) nounwind
declare i8* @roast_str_upper(i8*) nounwind
declare i8* @roast_str_lower(i8*) nounwind
declare i8* @roast_str_strip(i8*) nounwind
declare i8* @roast_str_lstrip(i8*) nounwind
declare i8* @roast_str_rstrip(i8*) nounwind
declare i8* @roast_str_split(i8*, i8*) nounwind
declare i8* @roast_str_join(i8*, i8*) nounwind
declare i64 @roast_str_find(i8*, i8*) nounwind
declare i64 @roast_str_rfind(i8*, i8*) nounwind
declare i8* @roast_str_replace(i8*, i8*, i8*) nounwind
declare i1 @roast_str_startswith(i8*, i8*) nounwind
declare i1 @roast_str_endswith(i8*, i8*) nounwind
declare i1 @roast_str_contains(i8*, i8*) nounwind
declare i8* @roast_str_index(i8*, i64) nounwind
declare i64 @roast_str_count(i8*, i8*) nounwind
declare i8* @roast_str_repeat(i8*, i64) nounwind
declare i8* @roast_str_format(i8*, i8*) nounwind

; List operations
declare i8* @roast_list_new(i64) nounwind
declare void @roast_list_append(i8*, i64) nounwind
declare i64 @roast_list_get(i8*, i64) nounwind
declare void @roast_list_set(i8*, i64, i64) nounwind
declare i64 @roast_list_len(i8*) nounwind
declare i64 @roast_list_pop(i8*) nounwind
declare i1 @roast_list_contains(i8*, i64) nounwind
declare i64 @roast_subscript_get(i64, i64) nounwind
declare i64 @roast_list_count(i8*, i64) nounwind
declare void @roast_list_sort(i8*) nounwind
declare i64 @roast_list_pop_at(i8*, i64) nounwind
declare void @roast_list_insert(i8*, i64, i64) nounwind
declare void @roast_list_remove(i8*, i64) nounwind
declare void @roast_list_clear(i8*) nounwind
declare void @roast_list_reverse(i8*) nounwind
declare i64 @roast_list_index(i8*, i64) nounwind
declare i8* @roast_list_copy(i8*) nounwind
declare void @roast_list_extend(i8*, i8*) nounwind
declare i8* @roast_list_slice(i8*, i64, i64, i64) nounwind

; Dict operations
declare i8* @roast_dict_new() nounwind
declare void @roast_dict_set(i8*, i64, i64) nounwind
declare i64 @roast_dict_get(i8*, i64) nounwind
declare i1 @roast_dict_contains(i8*, i64) nounwind
declare i64 @roast_dict_len(i8*) nounwind
declare void @roast_dict_delete(i8*, i64) nounwind
declare i8* @roast_dict_keys(i8*) nounwind
declare i8* @roast_dict_values(i8*) nounwind
declare i8* @roast_dict_items(i8*) nounwind
declare void @roast_dict_clear(i8*) nounwind
declare i64 @roast_dict_get_default(i8*, i64, i64) nounwind
declare i64 @roast_dict_pop(i8*, i64, i64) nounwind
declare void @roast_dict_update(i8*, i8*) nounwind
declare i8* @roast_dict_copy(i8*) nounwind
declare i64 @roast_dict_setdefault(i8*, i64, i64) nounwind

; Set operations
declare i8* @roast_set_new() nounwind
declare void @roast_set_add(i8*, i64) nounwind
declare void @roast_set_remove(i8*, i64) nounwind
declare i1 @roast_set_contains(i8*, i64) nounwind
declare i64 @roast_set_len(i8*) nounwind

; Tuple operations
declare i8* @roast_tuple_new(i64) nounwind
declare void @roast_tuple_set(i8*, i64, i64) nounwind
declare i64 @roast_tuple_get(i8*, i64) nounwind
declare i64 @roast_tuple_len(i8*) nounwind

; BigInt operations
declare i8* @roast_bigint_from_i64(i64) nounwind
declare i8* @roast_bigint_add(i8*, i8*) nounwind
declare i8* @roast_bigint_sub(i8*, i8*) nounwind
declare i8* @roast_bigint_mul(i8*, i8*) nounwind
declare i8* @roast_bigint_to_str(i8*) nounwind
declare void @roast_bigint_print(i8*) nounwind

; Iterator operations
declare i8* @roast_iter_new(i8*) nounwind
declare i64 @roast_iter_next(i8*, i1*) nounwind
declare i8* @roast_range_new(i64, i64, i64) nounwind

; Object operations
declare i8* @roast_object_new(i8*) nounwind
declare i8* @roast_class_new(i8*, i8*) nounwind
declare void @roast_class_add_method(i8*, i8*, i64) nounwind
declare i64 @roast_object_getattr(i8*, i8*) nounwind
declare i64 @roast_object_getattr_auto(i8*, i8*, i64) nounwind
declare void @roast_object_setattr(i8*, i8*, i64) nounwind
declare i1 @roast_object_hasattr(i8*, i8*) nounwind
declare i64 @roast_object_call_method0(i64, i8*) nounwind
declare i64 @roast_object_call_method1(i64, i8*, i64) nounwind
declare i64 @roast_object_call_method2(i64, i8*, i64, i64) nounwind

; Dunder method operations
declare i8* @roast_object_str(i64) nounwind
declare i8* @roast_object_repr(i64) nounwind
declare i64 @roast_object_eq(i64, i64) nounwind
declare i64 @roast_object_hash(i64) nounwind
declare i64 @roast_object_add(i64, i64) nounwind
declare i64 @roast_object_sub(i64, i64) nounwind
declare i64 @roast_object_mul(i64, i64) nounwind
declare i64 @roast_object_lt(i64, i64) nounwind
declare i64 @roast_object_le(i64, i64) nounwind
declare i64 @roast_object_gt(i64, i64) nounwind
declare i64 @roast_object_ge(i64, i64) nounwind
declare i64 @roast_object_bool(i64) nounwind
declare i64 @roast_object_len(i64) nounwind
declare i64 @roast_object_getitem(i64, i64) nounwind
declare void @roast_object_setitem(i64, i64, i64) nounwind
declare i64 @roast_object_contains(i64, i64) nounwind
declare i8* @roast_object_iter(i64) nounwind

; Closure operations
declare i8* @roast_closure_new(i8*, i64, i8*) nounwind
declare i64 @roast_closure_call(i8*, i64*, i64) nounwind

; Math operations
declare i64 @roast_pow_int(i64, i64) nounwind
declare double @roast_pow_float(double, double) nounwind
declare i64 @roast_abs_int(i64) nounwind
declare double @roast_abs_float(double) nounwind

; Async operations
declare i64 @roast_await(i8*) nounwind
declare i64 @roast_asyncio_run(i64) nounwind
declare i64 @roast_asyncio_sleep(double) nounwind
; Reference counting
declare i64 @roast_rc_create(i64) nounwind
declare i64 @roast_rc_get(i64) nounwind

; Error handling
declare i32 @setjmp(i8*) nounwind returns_twice
declare void @longjmp(i8*, i32) noreturn nounwind
declare i8* @roast_exception_push_frame() nounwind
declare void @roast_exception_pop_frame() nounwind
declare void @roast_assert(i1, i8*) nounwind
declare void @roast_raise(i64)
declare void @roast_raise_with_message(i64, i64)
declare void @roast_reraise()
declare i64 @roast_try_begin() nounwind
declare void @roast_try_end() nounwind
declare i64 @roast_get_exception() nounwind
declare i64 @roast_get_exception_type() nounwind
declare i64 @roast_exception_matches(i64, i8*) nounwind
declare i64 @roast_exception_new(i64, i64) nounwind
declare i64 @roast_exception_get_type(i64) nounwind
declare i8* @roast_exception_create(i64, i64) nounwind

; super() and varargs
declare i8* @roast_super_new(i8*, i8*) nounwind
declare i64 @roast_super_getattr(i8*, i8*) nounwind
declare i8* @roast_pack_varargs(i64*, i64, i64) nounwind
declare i64 @roast_pack_kwargs(i8**, i64*, i64) nounwind
declare i64 @roast_args_len(i8*) nounwind

; Property support
declare i8* @roast_property_new(i64, i64) nounwind
declare i64 @roast_property_get(i8*, i64) nounwind
declare void @roast_property_set(i8*, i64, i64) nounwind
declare i64 @roast_is_property(i64) nounwind

; Type constants
@roast_type_int = external global i64
@roast_type_float = external global i64
@roast_type_str = external global i64
@roast_type_bool = external global i64
@roast_type_list = external global i64
@roast_type_dict = external global i64
@roast_type_none = external global i64

; Builtin functions
declare i64 @roast_print(i64) nounwind
declare i64 @roast_len(i64) nounwind
declare i64 @roast_type(i64) nounwind
declare i64 @roast_int(i64) nounwind
declare i64 @roast_float(i64) nounwind
declare i64 @roast_str(i64) nounwind
declare i64 @roast_bool(i64) nounwind
declare i64 @roast_list(i64) nounwind
declare i64 @roast_dict(i64) nounwind
declare i64 @roast_set(i64) nounwind
declare i64 @roast_tuple(i64) nounwind
declare i64 @roast_range(i64, i64, i64) nounwind
declare i64 @roast_abs(i64) nounwind
declare i64 @roast_min(i64, i64) nounwind
declare i64 @roast_max(i64, i64) nounwind
declare i64 @roast_min_list(i64) nounwind
declare i64 @roast_max_list(i64) nounwind
declare i64 @roast_sum(i64) nounwind
declare i64 @roast_sorted(i64) nounwind
declare i64 @roast_reversed(i64) nounwind
declare i64 @roast_enumerate(i64, i64) nounwind
declare i64 @roast_zip(i64, i64) nounwind
declare i64 @roast_map(i64, i64) nounwind
declare i64 @roast_filter(i64, i64) nounwind
declare i64 @roast_input(i64) nounwind
declare i64 @roast_ord(i64) nounwind
declare i64 @roast_chr(i64) nounwind
declare i64 @roast_repr(i64) nounwind
declare i64 @roast_hash(i64) nounwind
declare i64 @roast_id(i64) nounwind
declare i64 @roast_isinstance(i64, i64) nounwind
declare i64 @roast_isinstance_by_name(i64, i8*) nounwind
declare i64 @roast_issubclass(i64, i64) nounwind
declare i64 @roast_hasattr(i64, i64) nounwind
declare i64 @roast_getattr(i64, i64) nounwind
declare i64 @roast_setattr(i64, i64, i64) nounwind
declare i64 @roast_all(i64) nounwind
declare i64 @roast_any(i64) nounwind
declare i64 @roast_pow(i64, i64) nounwind

; Class initialization
define internal void @roast_init_classes() {
entry:
  %class.Logger = call i8* @roast_class_new(i8* getelementptr ([7 x i8], [7 x i8]* @.classname.Logger, i32 0, i32 0), i8* null)
  store i8* %class.Logger, i8** @.class.Logger
  %method_ptr.Logger.111 = ptrtoint i64 (i64, ...)* @roast_fn_Logger_111 to i64
  call void @roast_class_add_method(i8* %class.Logger, i8* getelementptr ([6 x i8], [6 x i8]* @.methodname.Logger.111, i32 0, i32 0), i64 %method_ptr.Logger.111)
  %method_ptr.Logger.109 = ptrtoint i64 (i64, ...)* @roast_fn_Logger_109 to i64
  call void @roast_class_add_method(i8* %class.Logger, i8* getelementptr ([5 x i8], [5 x i8]* @.methodname.Logger.109, i32 0, i32 0), i64 %method_ptr.Logger.109)
  %method_ptr.Logger.60 = ptrtoint i64 (i64, ...)* @roast_fn_Logger_60 to i64
  call void @roast_class_add_method(i8* %class.Logger, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.Logger.60, i32 0, i32 0), i64 %method_ptr.Logger.60)
  %class.ResultProcessor = call i8* @roast_class_new(i8* getelementptr ([16 x i8], [16 x i8]* @.classname.ResultProcessor, i32 0, i32 0), i8* null)
  store i8* %class.ResultProcessor, i8** @.class.ResultProcessor
  %method_ptr.ResultProcessor.126 = ptrtoint i64 (i64, ...)* @roast_fn_ResultProcessor_126 to i64
  call void @roast_class_add_method(i8* %class.ResultProcessor, i8* getelementptr ([16 x i8], [16 x i8]* @.methodname.ResultProcessor.126, i32 0, i32 0), i64 %method_ptr.ResultProcessor.126)
  %method_ptr.ResultProcessor.60 = ptrtoint i64 (i64, ...)* @roast_fn_ResultProcessor_60 to i64
  call void @roast_class_add_method(i8* %class.ResultProcessor, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.ResultProcessor.60, i32 0, i32 0), i64 %method_ptr.ResultProcessor.60)
  %class.Scraper = call i8* @roast_class_new(i8* getelementptr ([8 x i8], [8 x i8]* @.classname.Scraper, i32 0, i32 0), i8* null)
  store i8* %class.Scraper, i8** @.class.Scraper
  %method_ptr.Scraper.60 = ptrtoint i64 (i64, ...)* @roast_fn_Scraper_60 to i64
  call void @roast_class_add_method(i8* %class.Scraper, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.Scraper.60, i32 0, i32 0), i64 %method_ptr.Scraper.60)
  %method_ptr.Scraper.120 = ptrtoint i64 (i64, ...)* @roast_fn_Scraper_120 to i64
  call void @roast_class_add_method(i8* %class.Scraper, i8* getelementptr ([11 x i8], [11 x i8]* @.methodname.Scraper.120, i32 0, i32 0), i64 %method_ptr.Scraper.120)
  %method_ptr.Scraper.118 = ptrtoint i64 (i64, ...)* @roast_fn_Scraper_118 to i64
  call void @roast_class_add_method(i8* %class.Scraper, i8* getelementptr ([12 x i8], [12 x i8]* @.methodname.Scraper.118, i32 0, i32 0), i64 %method_ptr.Scraper.118)
  %class.PageResult = call i8* @roast_class_new(i8* getelementptr ([11 x i8], [11 x i8]* @.classname.PageResult, i32 0, i32 0), i8* null)
  store i8* %class.PageResult, i8** @.class.PageResult
  %method_ptr.PageResult.60 = ptrtoint i64 (i64, ...)* @roast_fn_PageResult_60 to i64
  call void @roast_class_add_method(i8* %class.PageResult, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.PageResult.60, i32 0, i32 0), i64 %method_ptr.PageResult.60)
  %class.HttpClient = call i8* @roast_class_new(i8* getelementptr ([11 x i8], [11 x i8]* @.classname.HttpClient, i32 0, i32 0), i8* null)
  store i8* %class.HttpClient, i8** @.class.HttpClient
  %method_ptr.HttpClient.98 = ptrtoint i64 (i64, ...)* @roast_fn_HttpClient_98 to i64
  call void @roast_class_add_method(i8* %class.HttpClient, i8* getelementptr ([4 x i8], [4 x i8]* @.methodname.HttpClient.98, i32 0, i32 0), i64 %method_ptr.HttpClient.98)
  %method_ptr.HttpClient.60 = ptrtoint i64 (i64, ...)* @roast_fn_HttpClient_60 to i64
  call void @roast_class_add_method(i8* %class.HttpClient, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.HttpClient.60, i32 0, i32 0), i64 %method_ptr.HttpClient.60)
  %class.HtmlParser = call i8* @roast_class_new(i8* getelementptr ([11 x i8], [11 x i8]* @.classname.HtmlParser, i32 0, i32 0), i8* null)
  store i8* %class.HtmlParser, i8** @.class.HtmlParser
  %method_ptr.HtmlParser.60 = ptrtoint i64 (i64, ...)* @roast_fn_HtmlParser_60 to i64
  call void @roast_class_add_method(i8* %class.HtmlParser, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.HtmlParser.60, i32 0, i32 0), i64 %method_ptr.HtmlParser.60)
  %method_ptr.HtmlParser.101 = ptrtoint i64 (i64, ...)* @roast_fn_HtmlParser_101 to i64
  call void @roast_class_add_method(i8* %class.HtmlParser, i8* getelementptr ([14 x i8], [14 x i8]* @.methodname.HtmlParser.101, i32 0, i32 0), i64 %method_ptr.HtmlParser.101)
  %method_ptr.HtmlParser.106 = ptrtoint i64 (i64, ...)* @roast_fn_HtmlParser_106 to i64
  call void @roast_class_add_method(i8* %class.HtmlParser, i8* getelementptr ([12 x i8], [12 x i8]* @.methodname.HtmlParser.106, i32 0, i32 0), i64 %method_ptr.HtmlParser.106)
  %class.ScraperConfig = call i8* @roast_class_new(i8* getelementptr ([14 x i8], [14 x i8]* @.classname.ScraperConfig, i32 0, i32 0), i8* null)
  store i8* %class.ScraperConfig, i8** @.class.ScraperConfig
  %method_ptr.ScraperConfig.60 = ptrtoint i64 (i64, ...)* @roast_fn_ScraperConfig_60 to i64
  call void @roast_class_add_method(i8* %class.ScraperConfig, i8* getelementptr ([9 x i8], [9 x i8]* @.methodname.ScraperConfig.60, i32 0, i32 0), i64 %method_ptr.ScraperConfig.60)
  ret void
}

define i64 @roast_fn_Scraper_118(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i64
  %v41 = alloca i64
  %v42 = alloca i64
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i64
  %v53 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v54 = load i64, i64* %v0
  %v55 = getelementptr [7 x i8], [7 x i8]* @.str.27, i64 0, i64 0
  %v56 = inttoptr i64 %v54 to i8*
  %v57 = call i64 @roast_object_getattr_auto(i8* %v56, i8* %v55, i64 %v54)
  store i64 %v57, i64* %v3
  %v58 = load i64, i64* %v1
  %v59 = call i64 @roast_str(i64 %v58)
  store i64 %v59, i64* %v4
  br label %bb1
bb1:
  %v60 = getelementptr [11 x i8], [11 x i8]* @.str.29, i64 0, i64 0
  %v61 = call i8* @roast_str_new(i8* %v60, i64 10)
  %v62 = ptrtoint i8* %v61 to i64
  %v63 = load i64, i64* %v4
  %v65 = inttoptr i64 %v62 to i8*
  %v66 = inttoptr i64 %v63 to i8*
  %v67 = call i8* @roast_str_concat(i8* %v65, i8* %v66)
  %v64 = ptrtoint i8* %v67 to i64
  store i64 %v64, i64* %v5
  %v68 = load i64, i64* %v3
  %v70 = load i64, i64* %v5
  %v69 = call i64 @roast_fn_Logger_109(i64 %v68, i64 %v70)
  store i64 %v69, i64* %v2
  br label %bb2
bb2:
  %v71 = load i64, i64* %v0
  %v72 = getelementptr [7 x i8], [7 x i8]* @.str.24, i64 0, i64 0
  %v73 = inttoptr i64 %v71 to i8*
  %v74 = call i64 @roast_object_getattr_auto(i8* %v73, i8* %v72, i64 %v71)
  store i64 %v74, i64* %v8
  %v75 = load i64, i64* %v8
  %v77 = load i64, i64* %v1
  %v76 = call i64 @roast_fn_HttpClient_98(i64 %v75, i64 %v77)
  store i64 %v76, i64* %v7
  br label %bb3
bb3:
  %v78 = load i64, i64* %v7
  store i64 %v78, i64* %v6
  %v79 = inttoptr i64 %v78 to i8*
  call void @roast_incref(i8* %v79)
  %v80 = load i64, i64* %v0
  %v81 = getelementptr [7 x i8], [7 x i8]* @.str.25, i64 0, i64 0
  %v82 = inttoptr i64 %v80 to i8*
  %v83 = call i64 @roast_object_getattr_auto(i8* %v82, i8* %v81, i64 %v80)
  store i64 %v83, i64* %v11
  %v84 = load i64, i64* %v11
  %v86 = load i64, i64* %v6
  %v85 = call i64 @roast_fn_HtmlParser_101(i64 %v84, i64 %v86)
  store i64 %v85, i64* %v10
  br label %bb4
bb4:
  %v87 = load i64, i64* %v10
  store i64 %v87, i64* %v9
  %v88 = inttoptr i64 %v87 to i8*
  call void @roast_incref(i8* %v88)
  %v89 = load i64, i64* %v0
  %v90 = getelementptr [7 x i8], [7 x i8]* @.str.25, i64 0, i64 0
  %v91 = inttoptr i64 %v89 to i8*
  %v92 = call i64 @roast_object_getattr_auto(i8* %v91, i8* %v90, i64 %v89)
  store i64 %v92, i64* %v14
  %v93 = load i64, i64* %v14
  %v95 = load i64, i64* %v6
  %v94 = call i64 @roast_fn_HtmlParser_106(i64 %v93, i64 %v95)
  store i64 %v94, i64* %v13
  br label %bb5
bb5:
  %v96 = load i64, i64* %v13
  store i64 %v96, i64* %v12
  %v97 = load i64, i64* %v0
  %v98 = getelementptr [14 x i8], [14 x i8]* @.str.28, i64 0, i64 0
  %v99 = inttoptr i64 %v97 to i8*
  %v100 = call i64 @roast_object_getattr_auto(i8* %v99, i8* %v98, i64 %v97)
  store i64 %v100, i64* %v15
  %v101 = load i64, i64* %v15
  %v102 = add i64 %v101, 1
  store i64 %v102, i64* %v16
  %v103 = load i64, i64* %v0
  %v104 = inttoptr i64 %v103 to i8*
  %v105 = load i64, i64* %v16
  %v106 = getelementptr [14 x i8], [14 x i8]* @.str.28, i64 0, i64 0
  call void @roast_object_setattr(i8* %v104, i8* %v106, i64 %v105)
  %v107 = load i64, i64* %v0
  %v108 = getelementptr [7 x i8], [7 x i8]* @.str.27, i64 0, i64 0
  %v109 = inttoptr i64 %v107 to i8*
  %v110 = call i64 @roast_object_getattr_auto(i8* %v109, i8* %v108, i64 %v107)
  store i64 %v110, i64* %v18
  %v111 = load i64, i64* %v9
  %v112 = call i64 @roast_str(i64 %v111)
  store i64 %v112, i64* %v19
  br label %bb6
bb6:
  %v113 = getelementptr [10 x i8], [10 x i8]* @.str.30, i64 0, i64 0
  %v114 = call i8* @roast_str_new(i8* %v113, i64 9)
  %v115 = ptrtoint i8* %v114 to i64
  %v116 = load i64, i64* %v19
  %v118 = inttoptr i64 %v115 to i8*
  %v119 = inttoptr i64 %v116 to i8*
  %v120 = call i8* @roast_str_concat(i8* %v118, i8* %v119)
  %v117 = ptrtoint i8* %v120 to i64
  store i64 %v117, i64* %v20
  %v121 = load i64, i64* %v20
  %v122 = getelementptr [3 x i8], [3 x i8]* @.str.31, i64 0, i64 0
  %v123 = call i8* @roast_str_new(i8* %v122, i64 2)
  %v124 = ptrtoint i8* %v123 to i64
  %v126 = inttoptr i64 %v121 to i8*
  %v127 = inttoptr i64 %v124 to i8*
  %v128 = call i8* @roast_str_concat(i8* %v126, i8* %v127)
  %v125 = ptrtoint i8* %v128 to i64
  store i64 %v125, i64* %v21
  %v129 = load i64, i64* %v12
  %v130 = call i64 @roast_str(i64 %v129)
  store i64 %v130, i64* %v22
  br label %bb7
bb7:
  %v131 = load i64, i64* %v21
  %v132 = load i64, i64* %v22
  %v134 = inttoptr i64 %v131 to i8*
  %v135 = inttoptr i64 %v132 to i8*
  %v136 = call i8* @roast_str_concat(i8* %v134, i8* %v135)
  %v133 = ptrtoint i8* %v136 to i64
  store i64 %v133, i64* %v23
  %v137 = load i64, i64* %v23
  %v138 = getelementptr [8 x i8], [8 x i8]* @.str.32, i64 0, i64 0
  %v139 = call i8* @roast_str_new(i8* %v138, i64 7)
  %v140 = ptrtoint i8* %v139 to i64
  %v142 = inttoptr i64 %v137 to i8*
  %v143 = inttoptr i64 %v140 to i8*
  %v144 = call i8* @roast_str_concat(i8* %v142, i8* %v143)
  %v141 = ptrtoint i8* %v144 to i64
  store i64 %v141, i64* %v24
  %v145 = load i64, i64* %v18
  %v147 = load i64, i64* %v24
  %v146 = call i64 @roast_fn_Logger_109(i64 %v145, i64 %v147)
  store i64 %v146, i64* %v17
  br label %bb8
bb8:
  %v148 = load i64, i64* %v1
  %v149 = load i64, i64* %v9
  %v150 = load i64, i64* %v12
  %v151 = call i64 @roast_fn_92(i64 %v148, i64 %v149, i64 %v150)
  store i64 %v151, i64* %v25
  br label %bb9
bb9:
  %v152 = load i64, i64* %v6
  %v153 = inttoptr i64 %v152 to i8*
  call void @roast_decref(i8* %v153)
  %v154 = load i64, i64* %v9
  %v155 = inttoptr i64 %v154 to i8*
  call void @roast_decref(i8* %v155)
  %v156 = load i64, i64* %v25
  ret i64 %v156
}


define i64 @roast_fn_125() {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.ResultProcessor
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_ResultProcessor_60(i64 %self_i64)

    ; Return the object (as i64)
    ret i64 %self_i64
}

define i64 @roast_fn_191() {
entry:
  %v0 = alloca i64
  %v1 = call i64 @roast_fn_134()
  store i64 %v1, i64* %v0
  br label %bb1
bb1:
  ret i64 0
}

define i64 @roast_fn_Logger_109(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v9 = load i64, i64* %v0
  %v10 = getelementptr [5 x i8], [5 x i8]* @.str.19, i64 0, i64 0
  %v11 = inttoptr i64 %v9 to i8*
  %v12 = call i64 @roast_object_getattr_auto(i8* %v11, i8* %v10, i64 %v9)
  store i64 %v12, i64* %v4
  %v13 = load i64, i64* %v4
  %v14 = call i64 @roast_str(i64 %v13)
  store i64 %v14, i64* %v3
  br label %bb1
bb1:
  %v15 = getelementptr [2 x i8], [2 x i8]* @.str.20, i64 0, i64 0
  %v16 = call i8* @roast_str_new(i8* %v15, i64 1)
  %v17 = ptrtoint i8* %v16 to i64
  %v18 = load i64, i64* %v3
  %v20 = inttoptr i64 %v17 to i8*
  %v21 = inttoptr i64 %v18 to i8*
  %v22 = call i8* @roast_str_concat(i8* %v20, i8* %v21)
  %v19 = ptrtoint i8* %v22 to i64
  store i64 %v19, i64* %v5
  %v23 = load i64, i64* %v5
  %v24 = getelementptr [9 x i8], [9 x i8]* @.str.21, i64 0, i64 0
  %v25 = call i8* @roast_str_new(i8* %v24, i64 8)
  %v26 = ptrtoint i8* %v25 to i64
  %v28 = inttoptr i64 %v23 to i8*
  %v29 = inttoptr i64 %v26 to i8*
  %v30 = call i8* @roast_str_concat(i8* %v28, i8* %v29)
  %v27 = ptrtoint i8* %v30 to i64
  store i64 %v27, i64* %v6
  %v31 = load i64, i64* %v1
  %v32 = call i64 @roast_str(i64 %v31)
  store i64 %v32, i64* %v7
  br label %bb2
bb2:
  %v33 = load i64, i64* %v6
  %v34 = load i64, i64* %v7
  %v36 = inttoptr i64 %v33 to i8*
  %v37 = inttoptr i64 %v34 to i8*
  %v38 = call i8* @roast_str_concat(i8* %v36, i8* %v37)
  %v35 = ptrtoint i8* %v38 to i64
  store i64 %v35, i64* %v8
  %v39 = load i64, i64* %v8
  %v40 = call i64 @roast_print(i64 %v39)
  store i64 %v40, i64* %v2
  br label %bb3
bb3:
  ret i64 0
}

define i64 @roast_fn_131() {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i64
  %v41 = alloca i64
  %v42 = alloca i64
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i64
  %v53 = alloca i64
  %v54 = alloca i64
  %v55 = alloca i64
  %v56 = alloca i64
  %v57 = alloca i64
  %v58 = alloca i64
  %v59 = alloca i64
  %v60 = alloca i64
  %v61 = alloca i64
  %v62 = alloca i64
  %v63 = alloca i64
  %v64 = alloca i64
  %v65 = alloca i64
  %v66 = alloca i64
  %v67 = alloca i64
  %v68 = alloca i64
  %v69 = alloca i64
  %v70 = alloca i64
  %v71 = alloca i64
  %v72 = alloca i64
  %v73 = alloca i64
  %v74 = alloca i64
  %v75 = alloca i64
  %v76 = alloca i64
  %v77 = alloca i64
  %v78 = alloca i64
  %v79 = alloca i64
  %v80 = alloca i64
  %v81 = alloca i64
  %v82 = alloca i64
  %v83 = alloca i64
  %v84 = alloca i64
  %v85 = alloca i64
  %v86 = alloca i64
  %v87 = alloca i64
  %v88 = alloca i64
  %v89 = alloca i64
  %v90 = alloca i64
  %v91 = alloca i64
  %v92 = alloca i64
  %v93 = alloca i64
  %v94 = alloca i64
  %v95 = alloca i64
  %v96 = alloca i64
  %v97 = alloca i64
  %v98 = alloca i64
  %v99 = alloca i64
  %v100 = alloca i64
  %v101 = alloca i64
  %v102 = alloca i64
  %v103 = alloca i64
  %v104 = alloca i64
  %v105 = alloca i64
  %v106 = alloca i64
  %v107 = alloca i64
  %v108 = alloca i64
  %v109 = alloca i64
  %v110 = alloca i64
  %v111 = alloca i64
  %v112 = alloca i64
  %v113 = alloca i64
  %v114 = alloca i64
  %v115 = alloca i64
  %v116 = alloca i64
  %v117 = alloca i64
  %v118 = alloca i64
  %v119 = alloca i64
  %v120 = alloca i64
  %v121 = alloca i64
  %v122 = alloca i64
  %v123 = alloca i64
  %v124 = alloca i64
  %v125 = alloca i64
  %v126 = alloca i64
  %v127 = alloca i64
  %v128 = alloca i64
  %v129 = alloca i64
  %v130 = alloca i64
  %v131 = alloca i64
  %v132 = alloca i64
  %v133 = alloca i64
  %v134 = alloca i64
  %v135 = alloca i64
  %v136 = alloca i64
  %v137 = alloca i64
  %v138 = alloca i64
  %v139 = alloca i64
  %v140 = alloca i64
  %v141 = alloca i64
  %v142 = alloca i64
  %v143 = alloca i64
  %v144 = alloca i64
  %v145 = alloca i64
  %v146 = alloca i64
  %v147 = alloca i64
  %v148 = alloca i64
  %v149 = alloca i64
  %v150 = alloca i64
  %v151 = alloca i64
  %v152 = alloca i64
  %v153 = alloca i64
  %v154 = alloca i64
  %v155 = alloca i64
  %v156 = alloca i64
  %v157 = alloca i64
  %v158 = alloca i64
  %v159 = alloca i64
  %v160 = alloca i64
  %v161 = alloca i64
  %v162 = alloca i64
  %v163 = alloca i64
  %v164 = alloca i64
  %v165 = alloca i64
  %v166 = alloca i64
  %v167 = alloca i64
  %v168 = alloca i64
  %v169 = alloca i64
  %v170 = alloca i64
  %v171 = alloca i64
  %v172 = alloca i64
  %v173 = alloca i64
  %v174 = getelementptr [2 x i8], [2 x i8]* @.str.45, i64 0, i64 0
  %v175 = call i8* @roast_str_new(i8* %v174, i64 1)
  %v176 = ptrtoint i8* %v175 to i64
  %v178 = inttoptr i64 %v176 to i8*
  %v179 = call i8* @roast_str_repeat(i8* %v178, i64 60)
  %v177 = ptrtoint i8* %v179 to i64
  store i64 %v177, i64* %v1
  %v180 = load i64, i64* %v1
  %v181 = call i64 @roast_print(i64 %v180)
  store i64 %v181, i64* %v0
  br label %bb1
bb1:
  %v182 = getelementptr [44 x i8], [44 x i8]* @.str.46, i64 0, i64 0
  %v183 = call i8* @roast_str_new(i8* %v182, i64 43)
  %v184 = ptrtoint i8* %v183 to i64
  %v185 = call i64 @roast_print(i64 %v184)
  store i64 %v185, i64* %v2
  br label %bb2
bb2:
  %v186 = getelementptr [39 x i8], [39 x i8]* @.str.47, i64 0, i64 0
  %v187 = call i8* @roast_str_new(i8* %v186, i64 38)
  %v188 = ptrtoint i8* %v187 to i64
  %v189 = call i64 @roast_print(i64 %v188)
  store i64 %v189, i64* %v3
  br label %bb3
bb3:
  %v190 = getelementptr [2 x i8], [2 x i8]* @.str.45, i64 0, i64 0
  %v191 = call i8* @roast_str_new(i8* %v190, i64 1)
  %v192 = ptrtoint i8* %v191 to i64
  %v194 = inttoptr i64 %v192 to i8*
  %v195 = call i8* @roast_str_repeat(i8* %v194, i64 60)
  %v193 = ptrtoint i8* %v195 to i64
  store i64 %v193, i64* %v5
  %v196 = load i64, i64* %v5
  %v197 = call i64 @roast_print(i64 %v196)
  store i64 %v197, i64* %v4
  br label %bb4
bb4:
  %v198 = getelementptr [1 x i8], [1 x i8]* @.str.38, i64 0, i64 0
  %v199 = call i8* @roast_str_new(i8* %v198, i64 0)
  %v200 = ptrtoint i8* %v199 to i64
  %v201 = call i64 @roast_print(i64 %v200)
  store i64 %v201, i64* %v6
  br label %bb5
bb5:
  %v202 = call i64 @roast_fn_88()
  store i64 %v202, i64* %v8
  br label %bb6
bb6:
  %v203 = load i64, i64* %v8
  store i64 %v203, i64* %v7
  %v204 = inttoptr i64 %v203 to i8*
  call void @roast_incref(i8* %v204)
  %v205 = load i64, i64* %v7
  %v206 = call i64 @roast_fn_112(i64 %v205)
  store i64 %v206, i64* %v10
  br label %bb7
bb7:
  %v207 = load i64, i64* %v10
  store i64 %v207, i64* %v9
  %v208 = inttoptr i64 %v207 to i8*
  call void @roast_incref(i8* %v208)
  %v209 = call i8* @roast_list_new(i64 5)
  %v210 = getelementptr [20 x i8], [20 x i8]* @.str.48, i64 0, i64 0
  %v211 = call i8* @roast_str_new(i8* %v210, i64 19)
  %v212 = ptrtoint i8* %v211 to i64
  call void @roast_list_append(i8* %v209, i64 %v212)
  %v213 = getelementptr [35 x i8], [35 x i8]* @.str.49, i64 0, i64 0
  %v214 = call i8* @roast_str_new(i8* %v213, i64 34)
  %v215 = ptrtoint i8* %v214 to i64
  call void @roast_list_append(i8* %v209, i64 %v215)
  %v216 = getelementptr [28 x i8], [28 x i8]* @.str.50, i64 0, i64 0
  %v217 = call i8* @roast_str_new(i8* %v216, i64 27)
  %v218 = ptrtoint i8* %v217 to i64
  call void @roast_list_append(i8* %v209, i64 %v218)
  %v219 = getelementptr [32 x i8], [32 x i8]* @.str.51, i64 0, i64 0
  %v220 = call i8* @roast_str_new(i8* %v219, i64 31)
  %v221 = ptrtoint i8* %v220 to i64
  call void @roast_list_append(i8* %v209, i64 %v221)
  %v222 = getelementptr [25 x i8], [25 x i8]* @.str.52, i64 0, i64 0
  %v223 = call i8* @roast_str_new(i8* %v222, i64 24)
  %v224 = ptrtoint i8* %v223 to i64
  call void @roast_list_append(i8* %v209, i64 %v224)
  %v225 = ptrtoint i8* %v209 to i64
  store i64 %v225, i64* %v12
  %v226 = load i64, i64* %v12
  store i64 %v226, i64* %v11
  %v227 = inttoptr i64 %v226 to i8*
  call void @roast_incref(i8* %v227)
  %v228 = load i64, i64* %v11
  %v229 = call i64 @roast_len(i64 %v228)
  store i64 %v229, i64* %v15
  br label %bb8
bb8:
  %v230 = load i64, i64* %v15
  %v231 = call i64 @roast_str(i64 %v230)
  store i64 %v231, i64* %v14
  br label %bb9
bb9:
  %v232 = getelementptr [10 x i8], [10 x i8]* @.str.53, i64 0, i64 0
  %v233 = call i8* @roast_str_new(i8* %v232, i64 9)
  %v234 = ptrtoint i8* %v233 to i64
  %v235 = load i64, i64* %v14
  %v237 = inttoptr i64 %v234 to i8*
  %v238 = inttoptr i64 %v235 to i8*
  %v239 = call i8* @roast_str_concat(i8* %v237, i8* %v238)
  %v236 = ptrtoint i8* %v239 to i64
  store i64 %v236, i64* %v16
  %v240 = load i64, i64* %v16
  %v241 = getelementptr [9 x i8], [9 x i8]* @.str.54, i64 0, i64 0
  %v242 = call i8* @roast_str_new(i8* %v241, i64 8)
  %v243 = ptrtoint i8* %v242 to i64
  %v245 = inttoptr i64 %v240 to i8*
  %v246 = inttoptr i64 %v243 to i8*
  %v247 = call i8* @roast_str_concat(i8* %v245, i8* %v246)
  %v244 = ptrtoint i8* %v247 to i64
  store i64 %v244, i64* %v17
  %v248 = load i64, i64* %v17
  %v249 = call i64 @roast_print(i64 %v248)
  store i64 %v249, i64* %v13
  br label %bb10
bb10:
  %v250 = getelementptr [1 x i8], [1 x i8]* @.str.38, i64 0, i64 0
  %v251 = call i8* @roast_str_new(i8* %v250, i64 0)
  %v252 = ptrtoint i8* %v251 to i64
  %v253 = call i64 @roast_print(i64 %v252)
  store i64 %v253, i64* %v18
  br label %bb11
bb11:
  %v254 = load i64, i64* %v9
  %v256 = load i64, i64* %v11
  %v255 = call i64 @roast_fn_Scraper_120(i64 %v254, i64 %v256)
  store i64 %v255, i64* %v20
  br label %bb12
bb12:
  %v257 = load i64, i64* %v20
  store i64 %v257, i64* %v19
  %v258 = inttoptr i64 %v257 to i8*
  call void @roast_incref(i8* %v258)
  %v259 = call i64 @roast_fn_125()
  store i64 %v259, i64* %v22
  br label %bb13
bb13:
  %v260 = load i64, i64* %v22
  store i64 %v260, i64* %v21
  %v261 = inttoptr i64 %v260 to i8*
  call void @roast_incref(i8* %v261)
  %v262 = load i64, i64* %v21
  %v264 = load i64, i64* %v19
  %v263 = call i64 @roast_fn_ResultProcessor_126(i64 %v262, i64 %v264)
  store i64 %v263, i64* %v23
  br label %bb14
bb14:
  %v265 = getelementptr [1 x i8], [1 x i8]* @.str.38, i64 0, i64 0
  %v266 = call i8* @roast_str_new(i8* %v265, i64 0)
  %v267 = ptrtoint i8* %v266 to i64
  %v268 = call i64 @roast_print(i64 %v267)
  store i64 %v268, i64* %v24
  br label %bb15
bb15:
  %v269 = getelementptr [2 x i8], [2 x i8]* @.str.45, i64 0, i64 0
  %v270 = call i8* @roast_str_new(i8* %v269, i64 1)
  %v271 = ptrtoint i8* %v270 to i64
  %v273 = inttoptr i64 %v271 to i8*
  %v274 = call i8* @roast_str_repeat(i8* %v273, i64 60)
  %v272 = ptrtoint i8* %v274 to i64
  store i64 %v272, i64* %v26
  %v275 = load i64, i64* %v26
  %v276 = call i64 @roast_print(i64 %v275)
  store i64 %v276, i64* %v25
  br label %bb16
bb16:
  %v277 = getelementptr [33 x i8], [33 x i8]* @.str.55, i64 0, i64 0
  %v278 = call i8* @roast_str_new(i8* %v277, i64 32)
  %v279 = ptrtoint i8* %v278 to i64
  %v280 = call i64 @roast_print(i64 %v279)
  store i64 %v280, i64* %v27
  br label %bb17
bb17:
  %v281 = getelementptr [2 x i8], [2 x i8]* @.str.45, i64 0, i64 0
  %v282 = call i8* @roast_str_new(i8* %v281, i64 1)
  %v283 = ptrtoint i8* %v282 to i64
  %v285 = inttoptr i64 %v283 to i8*
  %v286 = call i8* @roast_str_repeat(i8* %v285, i64 60)
  %v284 = ptrtoint i8* %v286 to i64
  store i64 %v284, i64* %v29
  %v287 = load i64, i64* %v29
  %v288 = call i64 @roast_print(i64 %v287)
  store i64 %v288, i64* %v28
  br label %bb18
bb18:
  %v289 = load i64, i64* %v7
  %v290 = inttoptr i64 %v289 to i8*
  call void @roast_decref(i8* %v290)
  %v291 = load i64, i64* %v9
  %v292 = inttoptr i64 %v291 to i8*
  call void @roast_decref(i8* %v292)
  %v293 = load i64, i64* %v11
  %v294 = inttoptr i64 %v293 to i8*
  call void @roast_decref(i8* %v294)
  %v295 = load i64, i64* %v19
  %v296 = inttoptr i64 %v295 to i8*
  call void @roast_decref(i8* %v296)
  %v297 = load i64, i64* %v21
  %v298 = inttoptr i64 %v297 to i8*
  call void @roast_decref(i8* %v298)
  ret i64 0
}

define i64 @roast_fn_ResultProcessor_60(i64 %arg0) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  store i64 %arg0, i64* %v0
  %v6 = getelementptr [10 x i8], [10 x i8]* @.str.37, i64 0, i64 0
  %v7 = call i8* @roast_str_new(i8* %v6, i64 9)
  %v8 = ptrtoint i8* %v7 to i64
  %v9 = call i64 @roast_fn_107(i64 %v8)
  store i64 %v9, i64* %v1
  br label %bb1
bb1:
  %v10 = load i64, i64* %v0
  %v11 = inttoptr i64 %v10 to i8*
  %v12 = load i64, i64* %v1
  %v13 = getelementptr [7 x i8], [7 x i8]* @.str.27, i64 0, i64 0
  call void @roast_object_setattr(i8* %v11, i8* %v13, i64 %v12)
  ret i64 0
}


define i64 @roast_fn_107(i64 %arg0) {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.Logger
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_Logger_60(i64 %self_i64, i64 %arg0)

    ; Return the object (as i64)
    ret i64 %self_i64
}


define i32 @main(i32 %argc, i8** %argv) {
entry:
    call void @roast_init_classes()
    call void @roast_fn_191()
    ret i32 0
}

define i64 @roast_fn_HttpClient_98(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v12 = load i64, i64* %v1
  %v13 = call i64 @roast_str(i64 %v12)
  store i64 %v13, i64* %v3
  br label %bb1
bb1:
  %v14 = getelementptr [12 x i8], [12 x i8]* @.str.8, i64 0, i64 0
  %v15 = call i8* @roast_str_new(i8* %v14, i64 11)
  %v16 = ptrtoint i8* %v15 to i64
  %v17 = load i64, i64* %v3
  %v19 = inttoptr i64 %v16 to i8*
  %v20 = inttoptr i64 %v17 to i8*
  %v21 = call i8* @roast_str_concat(i8* %v19, i8* %v20)
  %v18 = ptrtoint i8* %v21 to i64
  store i64 %v18, i64* %v4
  %v22 = load i64, i64* %v4
  %v23 = call i64 @roast_print(i64 %v22)
  store i64 %v23, i64* %v2
  br label %bb2
bb2:
  %v24 = getelementptr [12 x i8], [12 x i8]* @.str.9, i64 0, i64 0
  %v25 = call i8* @roast_str_new(i8* %v24, i64 11)
  %v26 = ptrtoint i8* %v25 to i64
  %v27 = load i64, i64* %v1
  %v29 = inttoptr i64 %v27 to i8*
  %v31 = inttoptr i64 %v26 to i8*
  %v30 = call i1 @roast_str_contains(i8* %v29, i8* %v31)
  %v28 = zext i1 %v30 to i64
  store i64 %v28, i64* %v5
  %v32 = load i64, i64* %v5
  store i64 %v32, i64* %v6
  %v33 = load i64, i64* %v6
  %v34 = icmp eq i64 %v33, 1
  br i1 %v34, label %bb3, label %bb4
bb3:
  %v35 = getelementptr [72 x i8], [72 x i8]* @.str.10, i64 0, i64 0
  %v36 = call i8* @roast_str_new(i8* %v35, i64 71)
  %v37 = ptrtoint i8* %v36 to i64
  ret i64 %v37
bb4:
  %v38 = getelementptr [11 x i8], [11 x i8]* @.str.11, i64 0, i64 0
  %v39 = call i8* @roast_str_new(i8* %v38, i64 10)
  %v40 = ptrtoint i8* %v39 to i64
  %v41 = load i64, i64* %v1
  %v43 = inttoptr i64 %v41 to i8*
  %v45 = inttoptr i64 %v40 to i8*
  %v44 = call i1 @roast_str_contains(i8* %v43, i8* %v45)
  %v42 = zext i1 %v44 to i64
  store i64 %v42, i64* %v7
  %v46 = load i64, i64* %v7
  store i64 %v46, i64* %v8
  %v47 = load i64, i64* %v8
  %v48 = icmp eq i64 %v47, 1
  br i1 %v48, label %bb6, label %bb7
bb5:
  %v49 = load i64, i64* %v0
  ret i64 %v49
bb6:
  %v50 = getelementptr [37 x i8], [37 x i8]* @.str.12, i64 0, i64 0
  %v51 = call i8* @roast_str_new(i8* %v50, i64 36)
  %v52 = ptrtoint i8* %v51 to i64
  ret i64 %v52
bb7:
  %v53 = load i64, i64* %v1
  %v54 = call i64 @roast_str(i64 %v53)
  store i64 %v54, i64* %v9
  br label %bb9
bb8:
  br label %bb5
bb9:
  %v55 = getelementptr [26 x i8], [26 x i8]* @.str.13, i64 0, i64 0
  %v56 = call i8* @roast_str_new(i8* %v55, i64 25)
  %v57 = ptrtoint i8* %v56 to i64
  %v58 = load i64, i64* %v9
  %v60 = inttoptr i64 %v57 to i8*
  %v61 = inttoptr i64 %v58 to i8*
  %v62 = call i8* @roast_str_concat(i8* %v60, i8* %v61)
  %v59 = ptrtoint i8* %v62 to i64
  store i64 %v59, i64* %v10
  %v63 = load i64, i64* %v10
  %v64 = getelementptr [15 x i8], [15 x i8]* @.str.14, i64 0, i64 0
  %v65 = call i8* @roast_str_new(i8* %v64, i64 14)
  %v66 = ptrtoint i8* %v65 to i64
  %v68 = inttoptr i64 %v63 to i8*
  %v69 = inttoptr i64 %v66 to i8*
  %v70 = call i8* @roast_str_concat(i8* %v68, i8* %v69)
  %v67 = ptrtoint i8* %v70 to i64
  store i64 %v67, i64* %v11
  %v71 = load i64, i64* %v11
  ret i64 %v71
}

define i64 @roast_fn_ScraperConfig_60(i64 %arg0) {
entry:
  %v0 = alloca i64
  store i64 %arg0, i64* %v0
  %v1 = load i64, i64* %v0
  %v2 = inttoptr i64 %v1 to i8*
  %v3 = getelementptr [15 x i8], [15 x i8]* @.str.0, i64 0, i64 0
  call void @roast_object_setattr(i8* %v2, i8* %v3, i64 5)
  %v4 = load i64, i64* %v0
  %v5 = inttoptr i64 %v4 to i8*
  %v6 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  call void @roast_object_setattr(i8* %v5, i8* %v6, i64 30)
  %v7 = load i64, i64* %v0
  %v8 = inttoptr i64 %v7 to i8*
  %v9 = getelementptr [9 x i8], [9 x i8]* @.str.2, i64 0, i64 0
  %v10 = call i8* @roast_str_new(i8* %v9, i64 8)
  %v11 = ptrtoint i8* %v10 to i64
  %v12 = getelementptr [11 x i8], [11 x i8]* @.str.3, i64 0, i64 0
  call void @roast_object_setattr(i8* %v8, i8* %v12, i64 %v11)
  ret i64 0
}

define i64 @roast_fn_Scraper_120(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i64
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i64
  %v41 = alloca i64
  %v42 = alloca i64
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i64
  %v53 = alloca i64
  %v54 = alloca i64
  %v55 = alloca i64
  %v56 = alloca i64
  %v57 = alloca i64
  %v58 = alloca i64
  %v59 = alloca i64
  %v60 = alloca i64
  %v61 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v62 = load i64, i64* %v0
  %v63 = getelementptr [7 x i8], [7 x i8]* @.str.27, i64 0, i64 0
  %v64 = inttoptr i64 %v62 to i8*
  %v65 = call i64 @roast_object_getattr_auto(i8* %v64, i8* %v63, i64 %v62)
  store i64 %v65, i64* %v3
  %v66 = load i64, i64* %v1
  %v67 = call i64 @roast_len(i64 %v66)
  store i64 %v67, i64* %v5
  br label %bb1
bb1:
  %v68 = load i64, i64* %v5
  %v69 = call i64 @roast_str(i64 %v68)
  store i64 %v69, i64* %v4
  br label %bb2
bb2:
  %v70 = getelementptr [26 x i8], [26 x i8]* @.str.33, i64 0, i64 0
  %v71 = call i8* @roast_str_new(i8* %v70, i64 25)
  %v72 = ptrtoint i8* %v71 to i64
  %v73 = load i64, i64* %v4
  %v75 = inttoptr i64 %v72 to i8*
  %v76 = inttoptr i64 %v73 to i8*
  %v77 = call i8* @roast_str_concat(i8* %v75, i8* %v76)
  %v74 = ptrtoint i8* %v77 to i64
  store i64 %v74, i64* %v6
  %v78 = load i64, i64* %v6
  %v79 = getelementptr [6 x i8], [6 x i8]* @.str.34, i64 0, i64 0
  %v80 = call i8* @roast_str_new(i8* %v79, i64 5)
  %v81 = ptrtoint i8* %v80 to i64
  %v83 = inttoptr i64 %v78 to i8*
  %v84 = inttoptr i64 %v81 to i8*
  %v85 = call i8* @roast_str_concat(i8* %v83, i8* %v84)
  %v82 = ptrtoint i8* %v85 to i64
  store i64 %v82, i64* %v7
  %v86 = load i64, i64* %v3
  %v88 = load i64, i64* %v7
  %v87 = call i64 @roast_fn_Logger_109(i64 %v86, i64 %v88)
  store i64 %v87, i64* %v2
  br label %bb3
bb3:
  %v89 = call i8* @roast_list_new(i64 0)
  %v90 = ptrtoint i8* %v89 to i64
  store i64 %v90, i64* %v9
  %v91 = load i64, i64* %v9
  store i64 %v91, i64* %v8
  %v92 = inttoptr i64 %v91 to i8*
  call void @roast_incref(i8* %v92)
  %v93 = load i64, i64* %v1
  store i64 %v93, i64* %v10
  br label %bb4
bb4:
  %v94 = load i64, i64* %v10
  %v95 = inttoptr i64 %v94 to i8*
  %v96 = call i8* @roast_iter_new(i8* %v95)
  %v97 = ptrtoint i8* %v96 to i64
  store i64 %v97, i64* %v11
  br label %bb5
bb5:
  %v98 = load i64, i64* %v11
  %v99 = inttoptr i64 %v98 to i8*
  %v100 = alloca i1
  %v101 = call i64 @roast_iter_next(i8* %v99, i1* %v100)
  %v102 = load i1, i1* %v100
  store i64 %v101, i64* %v12
  br i1 %v102, label %bb7, label %bb6
bb6:
  %v103 = load i64, i64* %v0
  %v105 = load i64, i64* %v12
  %v104 = call i64 @roast_fn_Scraper_118(i64 %v103, i64 %v105)
  store i64 %v104, i64* %v14
  br label %bb8
bb7:
  %v106 = load i64, i64* %v0
  %v107 = getelementptr [7 x i8], [7 x i8]* @.str.27, i64 0, i64 0
  %v108 = inttoptr i64 %v106 to i8*
  %v109 = call i64 @roast_object_getattr_auto(i8* %v108, i8* %v107, i64 %v106)
  store i64 %v109, i64* %v17
  %v110 = load i64, i64* %v8
  %v111 = call i64 @roast_len(i64 %v110)
  store i64 %v111, i64* %v19
  br label %bb10
bb8:
  %v112 = load i64, i64* %v14
  store i64 %v112, i64* %v13
  %v113 = inttoptr i64 %v112 to i8*
  call void @roast_incref(i8* %v113)
  %v114 = load i64, i64* %v8
  %v116 = inttoptr i64 %v114 to i8*
  %v117 = load i64, i64* %v13
  call void @roast_list_append(i8* %v116, i64 %v117)
  %v115 = add i64 0, 0
  store i64 %v115, i64* %v15
  br label %bb9
bb9:
  br label %bb5
bb10:
  %v118 = load i64, i64* %v19
  %v119 = call i64 @roast_str(i64 %v118)
  store i64 %v119, i64* %v18
  br label %bb11
bb11:
  %v120 = getelementptr [12 x i8], [12 x i8]* @.str.35, i64 0, i64 0
  %v121 = call i8* @roast_str_new(i8* %v120, i64 11)
  %v122 = ptrtoint i8* %v121 to i64
  %v123 = load i64, i64* %v18
  %v125 = inttoptr i64 %v122 to i8*
  %v126 = inttoptr i64 %v123 to i8*
  %v127 = call i8* @roast_str_concat(i8* %v125, i8* %v126)
  %v124 = ptrtoint i8* %v127 to i64
  store i64 %v124, i64* %v20
  %v128 = load i64, i64* %v20
  %v129 = getelementptr [15 x i8], [15 x i8]* @.str.36, i64 0, i64 0
  %v130 = call i8* @roast_str_new(i8* %v129, i64 14)
  %v131 = ptrtoint i8* %v130 to i64
  %v133 = inttoptr i64 %v128 to i8*
  %v134 = inttoptr i64 %v131 to i8*
  %v135 = call i8* @roast_str_concat(i8* %v133, i8* %v134)
  %v132 = ptrtoint i8* %v135 to i64
  store i64 %v132, i64* %v21
  %v136 = load i64, i64* %v17
  %v138 = load i64, i64* %v21
  %v137 = call i64 @roast_fn_Logger_109(i64 %v136, i64 %v138)
  store i64 %v137, i64* %v16
  br label %bb12
bb12:
  %v139 = load i64, i64* %v8
  %v140 = inttoptr i64 %v139 to i8*
  call void @roast_decref(i8* %v140)
  %v141 = load i64, i64* %v13
  %v142 = inttoptr i64 %v141 to i8*
  call void @roast_decref(i8* %v142)
  %v143 = load i64, i64* %v8
  ret i64 %v143
}

define i64 @roast_fn_HtmlParser_101(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v15 = getelementptr [8 x i8], [8 x i8]* @.str.15, i64 0, i64 0
  %v16 = call i8* @roast_str_new(i8* %v15, i64 7)
  %v17 = ptrtoint i8* %v16 to i64
  %v18 = load i64, i64* %v1
  %v20 = inttoptr i64 %v18 to i8*
  %v22 = inttoptr i64 %v17 to i8*
  %v21 = call i1 @roast_str_contains(i8* %v20, i8* %v22)
  %v19 = zext i1 %v21 to i64
  store i64 %v19, i64* %v2
  %v23 = getelementptr [9 x i8], [9 x i8]* @.str.16, i64 0, i64 0
  %v24 = call i8* @roast_str_new(i8* %v23, i64 8)
  %v25 = ptrtoint i8* %v24 to i64
  %v26 = load i64, i64* %v1
  %v28 = inttoptr i64 %v26 to i8*
  %v30 = inttoptr i64 %v25 to i8*
  %v29 = call i1 @roast_str_contains(i8* %v28, i8* %v30)
  %v27 = zext i1 %v29 to i64
  store i64 %v27, i64* %v3
  %v31 = load i64, i64* %v2
  %v32 = load i64, i64* %v3
  %v33 = and i64 %v31, %v32
  store i64 %v33, i64* %v4
  %v34 = load i64, i64* %v4
  store i64 %v34, i64* %v5
  %v35 = load i64, i64* %v5
  %v36 = icmp eq i64 %v35, 1
  br i1 %v36, label %bb1, label %bb2
bb1:
  %v37 = load i64, i64* %v1
  %v39 = inttoptr i64 %v37 to i8*
  %v40 = getelementptr [8 x i8], [8 x i8]* @.str.15, i64 0, i64 0
  %v41 = call i8* @roast_str_new(i8* %v40, i64 7)
  %v42 = ptrtoint i8* %v41 to i64
  %v43 = inttoptr i64 %v42 to i8*
  %v38 = call i64 @roast_str_find(i8* %v39, i8* %v43)
  store i64 %v38, i64* %v7
  br label %bb3
bb2:
  %v44 = getelementptr [9 x i8], [9 x i8]* @.str.17, i64 0, i64 0
  %v45 = call i8* @roast_str_new(i8* %v44, i64 8)
  %v46 = ptrtoint i8* %v45 to i64
  ret i64 %v46
bb3:
  %v47 = load i64, i64* %v7
  %v48 = add i64 %v47, 7
  store i64 %v48, i64* %v8
  %v49 = load i64, i64* %v8
  store i64 %v49, i64* %v6
  %v50 = load i64, i64* %v1
  %v52 = inttoptr i64 %v50 to i8*
  %v53 = getelementptr [9 x i8], [9 x i8]* @.str.16, i64 0, i64 0
  %v54 = call i8* @roast_str_new(i8* %v53, i64 8)
  %v55 = ptrtoint i8* %v54 to i64
  %v56 = inttoptr i64 %v55 to i8*
  %v51 = call i64 @roast_str_find(i8* %v52, i8* %v56)
  store i64 %v51, i64* %v10
  br label %bb4
bb4:
  %v57 = load i64, i64* %v10
  store i64 %v57, i64* %v9
  %v58 = load i64, i64* %v1
  store i64 %v58, i64* %v11
  %v59 = inttoptr i64 %v58 to i8*
  call void @roast_incref(i8* %v59)
  %v60 = load i64, i64* %v6
  store i64 %v60, i64* %v12
  %v61 = load i64, i64* %v9
  store i64 %v61, i64* %v13
  store i64 0, i64* %v14
  %v62 = load i64, i64* %v11
  %v63 = load i64, i64* %v12
  %v64 = load i64, i64* %v13
  %v65 = load i64, i64* %v14
  %v67 = inttoptr i64 %v62 to i8*
  %v68 = call i8* @roast_str_slice(i8* %v67, i64 %v63, i64 %v64)
  %v66 = ptrtoint i8* %v68 to i64
  ret i64 %v66
}

define i64 @roast_fn_PageResult_60(i64 %arg0, i64 %arg1, i64 %arg2, i64 %arg3) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  store i64 %arg2, i64* %v2
  store i64 %arg3, i64* %v3
  %v4 = load i64, i64* %v0
  %v5 = inttoptr i64 %v4 to i8*
  %v6 = load i64, i64* %v1
  %v7 = getelementptr [4 x i8], [4 x i8]* @.str.4, i64 0, i64 0
  call void @roast_object_setattr(i8* %v5, i8* %v7, i64 %v6)
  %v8 = load i64, i64* %v0
  %v9 = inttoptr i64 %v8 to i8*
  %v10 = load i64, i64* %v2
  %v11 = getelementptr [6 x i8], [6 x i8]* @.str.5, i64 0, i64 0
  call void @roast_object_setattr(i8* %v9, i8* %v11, i64 %v10)
  %v12 = load i64, i64* %v0
  %v13 = inttoptr i64 %v12 to i8*
  %v14 = load i64, i64* %v3
  %v15 = getelementptr [11 x i8], [11 x i8]* @.str.6, i64 0, i64 0
  call void @roast_object_setattr(i8* %v13, i8* %v15, i64 %v14)
  %v16 = load i64, i64* %v0
  %v17 = inttoptr i64 %v16 to i8*
  %v18 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  call void @roast_object_setattr(i8* %v17, i8* %v18, i64 1)
  ret i64 0
}

define i64 @roast_fn_Logger_60(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v2 = load i64, i64* %v0
  %v3 = inttoptr i64 %v2 to i8*
  %v4 = load i64, i64* %v1
  %v5 = getelementptr [5 x i8], [5 x i8]* @.str.19, i64 0, i64 0
  call void @roast_object_setattr(i8* %v3, i8* %v5, i64 %v4)
  ret i64 0
}


define i64 @roast_fn_92(i64 %arg0, i64 %arg1, i64 %arg2) {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.PageResult
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_PageResult_60(i64 %self_i64, i64 %arg0, i64 %arg1, i64 %arg2)

    ; Return the object (as i64)
    ret i64 %self_i64
}

define i64 @roast_fn_HttpClient_60(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v2 = load i64, i64* %v0
  %v3 = inttoptr i64 %v2 to i8*
  %v4 = load i64, i64* %v1
  %v5 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  call void @roast_object_setattr(i8* %v3, i8* %v5, i64 %v4)
  ret i64 0
}


define i64 @roast_fn_112(i64 %arg0) {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.Scraper
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_Scraper_60(i64 %self_i64, i64 %arg0)

    ; Return the object (as i64)
    ret i64 %self_i64
}


define i64 @roast_fn_97(i64 %arg0) {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.HttpClient
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_HttpClient_60(i64 %self_i64, i64 %arg0)

    ; Return the object (as i64)
    ret i64 %self_i64
}


define i64 @roast_fn_100() {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.HtmlParser
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_HtmlParser_60(i64 %self_i64)

    ; Return the object (as i64)
    ret i64 %self_i64
}

define i64 @roast_fn_Logger_111(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v9 = load i64, i64* %v0
  %v10 = getelementptr [5 x i8], [5 x i8]* @.str.19, i64 0, i64 0
  %v11 = inttoptr i64 %v9 to i8*
  %v12 = call i64 @roast_object_getattr_auto(i8* %v11, i8* %v10, i64 %v9)
  store i64 %v12, i64* %v4
  %v13 = load i64, i64* %v4
  %v14 = call i64 @roast_str(i64 %v13)
  store i64 %v14, i64* %v3
  br label %bb1
bb1:
  %v15 = getelementptr [2 x i8], [2 x i8]* @.str.20, i64 0, i64 0
  %v16 = call i8* @roast_str_new(i8* %v15, i64 1)
  %v17 = ptrtoint i8* %v16 to i64
  %v18 = load i64, i64* %v3
  %v20 = inttoptr i64 %v17 to i8*
  %v21 = inttoptr i64 %v18 to i8*
  %v22 = call i8* @roast_str_concat(i8* %v20, i8* %v21)
  %v19 = ptrtoint i8* %v22 to i64
  store i64 %v19, i64* %v5
  %v23 = load i64, i64* %v5
  %v24 = getelementptr [10 x i8], [10 x i8]* @.str.22, i64 0, i64 0
  %v25 = call i8* @roast_str_new(i8* %v24, i64 9)
  %v26 = ptrtoint i8* %v25 to i64
  %v28 = inttoptr i64 %v23 to i8*
  %v29 = inttoptr i64 %v26 to i8*
  %v30 = call i8* @roast_str_concat(i8* %v28, i8* %v29)
  %v27 = ptrtoint i8* %v30 to i64
  store i64 %v27, i64* %v6
  %v31 = load i64, i64* %v1
  %v32 = call i64 @roast_str(i64 %v31)
  store i64 %v32, i64* %v7
  br label %bb2
bb2:
  %v33 = load i64, i64* %v6
  %v34 = load i64, i64* %v7
  %v36 = inttoptr i64 %v33 to i8*
  %v37 = inttoptr i64 %v34 to i8*
  %v38 = call i8* @roast_str_concat(i8* %v36, i8* %v37)
  %v35 = ptrtoint i8* %v38 to i64
  store i64 %v35, i64* %v8
  %v39 = load i64, i64* %v8
  %v40 = call i64 @roast_print(i64 %v39)
  store i64 %v40, i64* %v2
  br label %bb3
bb3:
  ret i64 0
}

define i64 @roast_fn_134() {
entry:
  %v0 = alloca i64
  %v1 = call i64 @roast_fn_131()
  store i64 %v1, i64* %v0
  br label %bb1
bb1:
  ret i64 0
}

define i64 @roast_fn_Scraper_60(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v25 = load i64, i64* %v0
  %v26 = inttoptr i64 %v25 to i8*
  %v27 = load i64, i64* %v1
  %v28 = getelementptr [7 x i8], [7 x i8]* @.str.23, i64 0, i64 0
  call void @roast_object_setattr(i8* %v26, i8* %v28, i64 %v27)
  %v29 = call i64 @roast_fn_97(i64 30)
  store i64 %v29, i64* %v2
  br label %bb1
bb1:
  %v30 = load i64, i64* %v0
  %v31 = inttoptr i64 %v30 to i8*
  %v32 = load i64, i64* %v2
  %v33 = getelementptr [7 x i8], [7 x i8]* @.str.24, i64 0, i64 0
  call void @roast_object_setattr(i8* %v31, i8* %v33, i64 %v32)
  %v34 = call i64 @roast_fn_100()
  store i64 %v34, i64* %v3
  br label %bb2
bb2:
  %v35 = load i64, i64* %v0
  %v36 = inttoptr i64 %v35 to i8*
  %v37 = load i64, i64* %v3
  %v38 = getelementptr [7 x i8], [7 x i8]* @.str.25, i64 0, i64 0
  call void @roast_object_setattr(i8* %v36, i8* %v38, i64 %v37)
  %v39 = getelementptr [8 x i8], [8 x i8]* @.str.26, i64 0, i64 0
  %v40 = call i8* @roast_str_new(i8* %v39, i64 7)
  %v41 = ptrtoint i8* %v40 to i64
  %v42 = call i64 @roast_fn_107(i64 %v41)
  store i64 %v42, i64* %v4
  br label %bb3
bb3:
  %v43 = load i64, i64* %v0
  %v44 = inttoptr i64 %v43 to i8*
  %v45 = load i64, i64* %v4
  %v46 = getelementptr [7 x i8], [7 x i8]* @.str.27, i64 0, i64 0
  call void @roast_object_setattr(i8* %v44, i8* %v46, i64 %v45)
  %v47 = load i64, i64* %v0
  %v48 = inttoptr i64 %v47 to i8*
  %v49 = getelementptr [14 x i8], [14 x i8]* @.str.28, i64 0, i64 0
  call void @roast_object_setattr(i8* %v48, i8* %v49, i64 0)
  ret i64 0
}

define i64 @roast_fn_ResultProcessor_126(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i64
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i64
  %v17 = alloca i64
  %v18 = alloca i64
  %v19 = alloca i64
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca i64
  %v23 = alloca i64
  %v24 = alloca i64
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i64
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v32 = load i64, i64* %v1
  %v33 = call i64 @roast_len(i64 %v32)
  store i64 %v33, i64* %v3
  br label %bb1
bb1:
  %v34 = load i64, i64* %v3
  store i64 %v34, i64* %v2
  store i64 0, i64* %v4
  %v35 = load i64, i64* %v4
  store i64 %v35, i64* %v5
  %v36 = load i64, i64* %v1
  store i64 %v36, i64* %v6
  br label %bb2
bb2:
  %v37 = load i64, i64* %v6
  %v38 = inttoptr i64 %v37 to i8*
  %v39 = call i8* @roast_iter_new(i8* %v38)
  %v40 = ptrtoint i8* %v39 to i64
  store i64 %v40, i64* %v7
  br label %bb3
bb3:
  %v41 = load i64, i64* %v7
  %v42 = inttoptr i64 %v41 to i8*
  %v43 = alloca i1
  %v44 = call i64 @roast_iter_next(i8* %v42, i1* %v43)
  %v45 = load i1, i1* %v43
  store i64 %v44, i64* %v8
  br i1 %v45, label %bb5, label %bb4
bb4:
  %v46 = load i64, i64* %v8
  %v47 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %v48 = inttoptr i64 %v46 to i8*
  %v49 = call i64 @roast_object_getattr_auto(i8* %v48, i8* %v47, i64 %v46)
  store i64 %v49, i64* %v9
  %v50 = load i64, i64* %v9
  store i64 %v50, i64* %v10
  %v51 = load i64, i64* %v9
  %v52 = icmp eq i64 %v51, 1
  br i1 %v52, label %bb6, label %bb7
bb5:
  %v53 = getelementptr [1 x i8], [1 x i8]* @.str.38, i64 0, i64 0
  %v54 = call i8* @roast_str_new(i8* %v53, i64 0)
  %v55 = ptrtoint i8* %v54 to i64
  %v56 = call i64 @roast_print(i64 %v55)
  store i64 %v56, i64* %v14
  br label %bb8
bb6:
  %v57 = load i64, i64* %v4
  %v58 = add i64 %v57, 1
  store i64 %v58, i64* %v11
  %v59 = load i64, i64* %v11
  store i64 %v59, i64* %v4
  %v60 = load i64, i64* %v8
  %v61 = getelementptr [11 x i8], [11 x i8]* @.str.6, i64 0, i64 0
  %v62 = inttoptr i64 %v60 to i8*
  %v63 = call i64 @roast_object_getattr_auto(i8* %v62, i8* %v61, i64 %v60)
  store i64 %v63, i64* %v12
  %v64 = load i64, i64* %v4
  %v65 = load i64, i64* %v12
  %v66 = add i64 %v64, %v65
  store i64 %v66, i64* %v13
  %v67 = load i64, i64* %v13
  store i64 %v67, i64* %v5
  br label %bb7
bb7:
  br label %bb3
bb8:
  %v68 = getelementptr [41 x i8], [41 x i8]* @.str.39, i64 0, i64 0
  %v69 = call i8* @roast_str_new(i8* %v68, i64 40)
  %v70 = ptrtoint i8* %v69 to i64
  %v71 = call i64 @roast_print(i64 %v70)
  store i64 %v71, i64* %v15
  br label %bb9
bb9:
  %v72 = getelementptr [26 x i8], [26 x i8]* @.str.40, i64 0, i64 0
  %v73 = call i8* @roast_str_new(i8* %v72, i64 25)
  %v74 = ptrtoint i8* %v73 to i64
  %v75 = call i64 @roast_print(i64 %v74)
  store i64 %v75, i64* %v16
  br label %bb10
bb10:
  %v76 = getelementptr [41 x i8], [41 x i8]* @.str.39, i64 0, i64 0
  %v77 = call i8* @roast_str_new(i8* %v76, i64 40)
  %v78 = ptrtoint i8* %v77 to i64
  %v79 = call i64 @roast_print(i64 %v78)
  store i64 %v79, i64* %v17
  br label %bb11
bb11:
  %v80 = load i64, i64* %v2
  %v81 = call i64 @roast_str(i64 %v80)
  store i64 %v81, i64* %v19
  br label %bb12
bb12:
  %v82 = getelementptr [17 x i8], [17 x i8]* @.str.41, i64 0, i64 0
  %v83 = call i8* @roast_str_new(i8* %v82, i64 16)
  %v84 = ptrtoint i8* %v83 to i64
  %v85 = load i64, i64* %v19
  %v87 = inttoptr i64 %v84 to i8*
  %v88 = inttoptr i64 %v85 to i8*
  %v89 = call i8* @roast_str_concat(i8* %v87, i8* %v88)
  %v86 = ptrtoint i8* %v89 to i64
  store i64 %v86, i64* %v20
  %v90 = load i64, i64* %v20
  %v91 = call i64 @roast_print(i64 %v90)
  store i64 %v91, i64* %v18
  br label %bb13
bb13:
  %v92 = load i64, i64* %v4
  %v93 = call i64 @roast_str(i64 %v92)
  store i64 %v93, i64* %v22
  br label %bb14
bb14:
  %v94 = getelementptr [17 x i8], [17 x i8]* @.str.42, i64 0, i64 0
  %v95 = call i8* @roast_str_new(i8* %v94, i64 16)
  %v96 = ptrtoint i8* %v95 to i64
  %v97 = load i64, i64* %v22
  %v99 = inttoptr i64 %v96 to i8*
  %v100 = inttoptr i64 %v97 to i8*
  %v101 = call i8* @roast_str_concat(i8* %v99, i8* %v100)
  %v98 = ptrtoint i8* %v101 to i64
  store i64 %v98, i64* %v23
  %v102 = load i64, i64* %v23
  %v103 = call i64 @roast_print(i64 %v102)
  store i64 %v103, i64* %v21
  br label %bb15
bb15:
  %v104 = load i64, i64* %v2
  %v105 = load i64, i64* %v4
  %v106 = sub i64 %v104, %v105
  store i64 %v106, i64* %v26
  %v107 = load i64, i64* %v26
  %v108 = call i64 @roast_str(i64 %v107)
  store i64 %v108, i64* %v25
  br label %bb16
bb16:
  %v109 = getelementptr [17 x i8], [17 x i8]* @.str.43, i64 0, i64 0
  %v110 = call i8* @roast_str_new(i8* %v109, i64 16)
  %v111 = ptrtoint i8* %v110 to i64
  %v112 = load i64, i64* %v25
  %v114 = inttoptr i64 %v111 to i8*
  %v115 = inttoptr i64 %v112 to i8*
  %v116 = call i8* @roast_str_concat(i8* %v114, i8* %v115)
  %v113 = ptrtoint i8* %v116 to i64
  store i64 %v113, i64* %v27
  %v117 = load i64, i64* %v27
  %v118 = call i64 @roast_print(i64 %v117)
  store i64 %v118, i64* %v24
  br label %bb17
bb17:
  %v119 = load i64, i64* %v4
  %v120 = call i64 @roast_str(i64 %v119)
  store i64 %v120, i64* %v29
  br label %bb18
bb18:
  %v121 = getelementptr [17 x i8], [17 x i8]* @.str.44, i64 0, i64 0
  %v122 = call i8* @roast_str_new(i8* %v121, i64 16)
  %v123 = ptrtoint i8* %v122 to i64
  %v124 = load i64, i64* %v29
  %v126 = inttoptr i64 %v123 to i8*
  %v127 = inttoptr i64 %v124 to i8*
  %v128 = call i8* @roast_str_concat(i8* %v126, i8* %v127)
  %v125 = ptrtoint i8* %v128 to i64
  store i64 %v125, i64* %v30
  %v129 = load i64, i64* %v30
  %v130 = call i64 @roast_print(i64 %v129)
  store i64 %v130, i64* %v28
  br label %bb19
bb19:
  %v131 = getelementptr [41 x i8], [41 x i8]* @.str.39, i64 0, i64 0
  %v132 = call i8* @roast_str_new(i8* %v131, i64 40)
  %v133 = ptrtoint i8* %v132 to i64
  %v134 = call i64 @roast_print(i64 %v133)
  store i64 %v134, i64* %v31
  br label %bb20
bb20:
  ret i64 0
}


define i64 @roast_fn_88() {
entry:
    ; Load class pointer from global
    %class_ptr = load i8*, i8** @.class.ScraperConfig
    ; Create a new object with the class pointer
    %obj = call i8* @roast_object_new(i8* %class_ptr)

    ; Convert object pointer to i64 for storage and passing
    %self_i64 = ptrtoint i8* %obj to i64

    ; Call __init__ with self and all arguments
    call i64 @roast_fn_ScraperConfig_60(i64 %self_i64)

    ; Return the object (as i64)
    ret i64 %self_i64
}

define i64 @roast_fn_HtmlParser_106(i64 %arg0, i64 %arg1) {
entry:
  %v0 = alloca i64
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  store i64 %arg0, i64* %v0
  store i64 %arg1, i64* %v1
  %v4 = getelementptr [6 x i8], [6 x i8]* @.str.18, i64 0, i64 0
  %v5 = call i8* @roast_str_new(i8* %v4, i64 5)
  %v6 = ptrtoint i8* %v5 to i64
  %v7 = load i64, i64* %v1
  %v9 = inttoptr i64 %v7 to i8*
  %v11 = inttoptr i64 %v6 to i8*
  %v10 = call i1 @roast_str_contains(i8* %v9, i8* %v11)
  %v8 = zext i1 %v10 to i64
  store i64 %v8, i64* %v2
  %v12 = load i64, i64* %v2
  store i64 %v12, i64* %v3
  %v13 = load i64, i64* %v3
  %v14 = icmp eq i64 %v13, 1
  br i1 %v14, label %bb1, label %bb2
bb1:
  ret i64 2
bb2:
  ret i64 0
}

define i64 @roast_fn_HtmlParser_60(i64 %arg0) {
entry:
  %v0 = alloca i64
  store i64 %arg0, i64* %v0
  ret i64 0
}

