//! Lockfile management.

use std::collections::HashMap;
use std::path::Path;
use std::fs;
use serde::{Deserialize, Serialize};
use crate::deps::{DependencyGraph, ResolvedDependency, ResolvedSource};
use crate::{Error, Result};

/// Lockfile version.
pub const LOCKFILE_VERSION: u32 = 1;

/// Package lockfile (roast.lock).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
    /// Lockfile version.
    pub version: u32,
    
    /// Locked packages.
    #[serde(default)]
    pub packages: Vec<LockedPackage>,
    
    /// Metadata.
    #[serde(default)]
    pub metadata: LockMetadata,
}

/// Locked package entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    /// Package name.
    pub name: String,
    
    /// Locked version.
    pub version: String,
    
    /// Source information.
    pub source: String,
    
    /// Checksum.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    
    /// Dependencies of this package.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
    
    /// Enabled features.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub features: Vec<String>,
}

/// Lockfile metadata.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LockMetadata {
    /// When the lockfile was generated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
    
    /// Roast version used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub roast_version: Option<String>,
    
    /// Kitchen version used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kitchen_version: Option<String>,
}

impl Lockfile {
    /// Create a new empty lockfile.
    pub fn new() -> Self {
        Self {
            version: LOCKFILE_VERSION,
            packages: Vec::new(),
            metadata: LockMetadata {
                generated_at: Some(chrono::Utc::now().to_rfc3339()),
                roast_version: Some("0.1.0".to_string()),
                kitchen_version: Some(crate::VERSION.to_string()),
            },
        }
    }
    
    /// Load from file.
    pub fn load(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)?;
        let lockfile: Lockfile = toml::from_str(&content)?;
        
        if lockfile.version > LOCKFILE_VERSION {
            return Err(Error::InvalidConfig(format!(
                "Lockfile version {} is too new (max supported: {})",
                lockfile.version, LOCKFILE_VERSION
            )));
        }
        
        Ok(lockfile)
    }
    
    /// Save to file.
    pub fn save(&self, path: &Path) -> Result<()> {
        let content = toml::to_string_pretty(self)
            .map_err(|e| Error::InvalidConfig(e.to_string()))?;
        
        // Add header comment
        let content = format!(
            "# This file is automatically @generated by Kitchen.\n\
             # It is not intended for manual editing.\n\n{}",
            content
        );
        
        fs::write(path, content)?;
        Ok(())
    }
    
    /// Create from dependency graph.
    pub fn from_graph(graph: &DependencyGraph) -> Self {
        let packages: Vec<LockedPackage> = graph.packages.values()
            .map(|dep| LockedPackage::from_resolved(dep))
            .collect();
        
        Self {
            version: LOCKFILE_VERSION,
            packages,
            metadata: LockMetadata {
                generated_at: Some(chrono::Utc::now().to_rfc3339()),
                roast_version: Some("0.1.0".to_string()),
                kitchen_version: Some(crate::VERSION.to_string()),
            },
        }
    }
    
    /// Get version for a package.
    pub fn get_version(&self, name: &str) -> Option<&str> {
        self.packages.iter()
            .find(|p| p.name == name)
            .map(|p| p.version.as_str())
    }
    
    /// Get locked versions as a map.
    pub fn locked_versions(&self) -> HashMap<String, semver::Version> {
        self.packages.iter()
            .filter_map(|p| {
                semver::Version::parse(&p.version).ok()
                    .map(|v| (p.name.clone(), v))
            })
            .collect()
    }
    
    /// Check if lockfile is up to date with config.
    pub fn is_up_to_date(&self, config: &crate::config::ProjectConfig) -> bool {
        // Check that all dependencies in config are in lockfile
        for name in config.dependencies.keys() {
            if self.get_version(name).is_none() {
                return false;
            }
        }
        
        for name in config.dev_dependencies.keys() {
            if self.get_version(name).is_none() {
                return false;
            }
        }
        
        true
    }
    
    /// Add a package.
    pub fn add(&mut self, package: LockedPackage) {
        // Remove existing entry
        self.packages.retain(|p| p.name != package.name);
        self.packages.push(package);
        self.packages.sort_by(|a, b| a.name.cmp(&b.name));
    }
    
    /// Remove a package.
    pub fn remove(&mut self, name: &str) {
        self.packages.retain(|p| p.name != name);
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

impl LockedPackage {
    /// Create from resolved dependency.
    pub fn from_resolved(dep: &ResolvedDependency) -> Self {
        let source = match &dep.source {
            ResolvedSource::Registry { registry } => {
                format!("registry+{}", registry)
            }
            ResolvedSource::Git { url, rev, .. } => {
                if let Some(rev) = rev {
                    format!("git+{}#{}", url, rev)
                } else {
                    format!("git+{}", url)
                }
            }
            ResolvedSource::Path { path } => {
                format!("path+{}", path)
            }
        };
        
        Self {
            name: dep.name.clone(),
            version: dep.version.clone(),
            source,
            checksum: dep.checksum.clone(),
            dependencies: dep.dependencies.clone(),
            features: dep.features.clone(),
        }
    }
}

/// Check if a lockfile exists for a project.
pub fn lockfile_exists(project_root: &Path) -> bool {
    project_root.join("roast.lock").exists()
}

/// Load lockfile for a project.
pub fn load_lockfile(project_root: &Path) -> Result<Option<Lockfile>> {
    let path = project_root.join("roast.lock");
    
    if !path.exists() {
        return Ok(None);
    }
    
    Ok(Some(Lockfile::load(&path)?))
}

