[package]
name = "roast-package-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Package manager for Roast (roastpkg)"

[dependencies]
roast-common.workspace = true
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
walkdir.workspace = true
indexmap.workspace = true
petgraph.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
dirs = "5"
serde_json = "1"
sha2 = "0.10"
hex = "0.4"
chrono = "0.4"
base64 = "0.22"

[[bin]]
name = "roastpkg"
path = "src/main.rs"

